// ============================================================
// KOVA — Expanded demo catalog families (DEMO DATA ONLY)
// Extends the hand-written ITEMS in seed-data.ts so each of the
// five sellers carries 200+ distinct products. Every entry is a
// real product family with structured attributes (material,
// dimensions, features, variants) — descriptions are composed
// from these fields by seed.ts, never filler text.
// Variant counts per family × families per seller ≥ 200 products.
// ============================================================

import type { SeedItem } from './seed-data';

export const LARGE_ITEMS: SeedItem[] = [
  // ═══ ALABI TECHHUB — electronics, mobile & computer accessories ═══════
  {
    name: 'Bluetooth Party Speaker', category: 'electronics', type: 'PHYSICAL',
    price: 26500, seller: 'alabi-techhub',
    material: 'Fabric-wrapped cabinet, rubber feet',
    dimensions: '19 × 9 × 9.5 cm, 1.1 kg',
    colours: ['Charcoal', 'Steel Blue', 'Rust Orange'],
    namedVariants: ['— 20W', '— 40W Dual Driver (₦41500)'],
    features: [
      'Passive bass radiator gives the low end real weight without a subwoofer',
      'Pairs with a second unit for true stereo in TWS mode',
      'IPX5 shell handles poolside splashes and rainy-day transport',
      'USB-C charging with powerbank-out to top up a phone',
    ],
    includes: ['Shoulder strap', 'USB-C cable', 'Quick-start card'],
  },
  {
    name: 'USB-C 7-in-1 Hub', category: 'electronics', type: 'PHYSICAL',
    price: 16900, seller: 'alabi-techhub',
    material: 'Aluminium shell, braided 18 cm host cable',
    dimensions: '11 × 3.5 × 1.4 cm, 68 g',
    colours: ['Space Grey', 'Silver'],
    features: [
      '4K@60Hz HDMI output for external monitors and projectors',
      '100 W USB-C power pass-through keeps the laptop charging',
      'Two USB-A 3.0 ports plus SD and microSD card readers',
      'Gigabit Ethernet for stable video calls where Wi-Fi struggles',
    ],
    includes: ['Travel pouch'],
  },
  {
    name: '1080p Streaming Webcam', category: 'electronics', type: 'PHYSICAL',
    price: 21900, seller: 'alabi-techhub',
    material: 'Glass lens, ABS body with privacy shutter',
    dimensions: '8 × 5.5 × 6 cm on clip mount',
    colours: ['Black'],
    namedVariants: ['— Standard', '— Tripod Bundle (₦26900)'],
    features: [
      'Full HD 1080p at 30 fps with automatic low-light correction',
      'Dual noise-reducing microphones tuned for voice',
      '90° field of view suits desk framing without wide-angle distortion',
      'Clip mounts on monitors or stands on a shelf; built-in privacy shutter',
    ],
    includes: ['1.5 m USB-A cable', 'User guide'],
  },
  {
    name: 'Aluminium Laptop Stand', category: 'electronics', type: 'PHYSICAL',
    price: 14500, seller: 'alabi-techhub',
    material: '6-series aluminium, silicone grip pads',
    dimensions: 'Folds to 26 × 5 × 2 cm; holds 10–17" laptops',
    colours: ['Space Grey', 'Silver', 'Champagne'],
    features: [
      'Six height settings raise the screen toward eye level to ease neck strain',
      'Open-frame design lets laptop fans breathe',
      'Holds up to 10 kg without flexing',
      'Folds flat into the included sleeve for commute or travel',
    ],
    includes: ['Felt travel sleeve'],
  },
  {
    name: '15W Wireless Charging Pad', category: 'electronics', type: 'PHYSICAL',
    price: 8900, seller: 'alabi-techhub',
    material: 'Fabric-top surface, anti-slip silicone base',
    dimensions: '10 × 10 × 0.7 cm',
    colours: ['Black', 'Oat', 'Sage'],
    features: [
      'Qi-certified 15 W fast charge for iPhone and Android',
      'Case-friendly up to 5 mm — no need to strip the phone naked',
      'Breathing LED shows charge state and dims at night',
      'Foreign-object detection shuts off when keys or coins land on it',
    ],
    includes: ['1 m USB-C cable', 'Wall adapter'],
  },
  {
    name: 'Smart Wi-Fi Plug', category: 'electronics', type: 'PHYSICAL',
    price: 7500, seller: 'alabi-techhub',
    material: 'Flame-retardant PC housing',
    dimensions: 'Fits single socket; 6 × 5.5 × 5 cm',
    colours: ['White'],
    namedVariants: ['— Single Pack', '— 2 Pack (₦13500)', '— 4 Pack (₦24500)'],
    features: [
      'Turns any appliance smart — works with the vendor app over 2.4 GHz Wi-Fi',
      'Schedules and countdown timers for water heaters and pumps',
      '16 A rating suits kettles, irons and small AC units',
      'Works with voice assistants that support the Tuya ecosystem',
    ],
  },
  {
    name: 'Fitness Activity Band', category: 'electronics', type: 'PHYSICAL',
    price: 15900, seller: 'alabi-techhub',
    material: 'Polycarbonate body, TPU strap',
    dimensions: 'Watch face 4 × 2 cm; strap fits 14–21 cm wrists',
    colours: ['Black', 'Rose', 'Navy'],
    features: [
      'Tracks steps, distance, sleep stages and all-day heart rate',
      '14 sport modes from running to jump rope',
      'Up to 10 days of typical use per charge (magnetic pogo charger)',
      'Call and app notifications mirrored from the phone',
    ],
    includes: ['Magnetic charging cable'],
  },
  {
    name: 'Bluetooth FM Transmitter', category: 'electronics', type: 'PHYSICAL',
    price: 9500, seller: 'alabi-techhub',
    material: 'ABS body, matte display',
    dimensions: '7.5 × 4 × 3.5 cm, 12 V socket powered',
    colours: ['Black'],
    features: [
      'Streams phone audio to older cars through an empty FM frequency',
      'Dual USB ports (2.4 A + 1 A) charge driver and passenger',
      'Hands-free calls through the built-in microphone',
      'Voltage readout helps watch the battery on long trips',
    ],
  },
  {
    name: 'Phone Gimbal Stabilizer', category: 'electronics', type: 'PHYSICAL',
    price: 44900, seller: 'alabi-techhub',
    material: 'Aluminium arms, textured polymer grip',
    dimensions: 'Folded 16 × 8 × 4 cm; payload up to 280 g',
    colours: ['Slate'],
    namedVariants: ['— Standard', '— Creator Kit with Tripod (₦52900)'],
    features: [
      'Three-axis stabilization smooths walking shots and pans',
      'Gesture control starts recording without touching the phone',
      'Active tracking keeps a subject centered as they move',
      'Folds compact enough for a jacket pocket',
    ],
    includes: ['Tripod base', 'Wrist strap', 'Pouch'],
  },
  {
    name: 'USB Condenser Microphone', category: 'electronics', type: 'PHYSICAL',
    price: 32900, seller: 'alabi-techhub',
    material: 'Steel grille, die-cast zinc body',
    dimensions: 'Stand height 22 cm; mic body 15 × 4.5 cm',
    colours: ['Black', 'Nickel'],
    features: [
      'Cardioid capsule focuses on the speaker and rejects room noise',
      'Zero-latency headphone jack for monitoring your own voice',
      'Tap-to-mute with an LED status ring',
      'Plug-and-play with computers — no audio interface needed',
    ],
    includes: ['Scissor-arm stand', 'Shock mount', 'Pop filter', '2.5 m USB cable'],
  },
  {
    name: 'Laptop Cooling Pad', category: 'electronics', type: 'PHYSICAL',
    price: 11900, seller: 'alabi-techhub',
    material: 'Mesh deck, ABS frame',
    dimensions: 'Fits 12–17" laptops; 5 adjustable angles',
    colours: ['Black'],
    namedVariants: ['— 5-Fan', '— 6-Fan RGB (₦14500)'],
    features: [
      'Five fans push cool air across the hot underside of the chassis',
      'Stepless height adjustment from flat to 18° typing angle',
      'Dual USB pass-through keeps a port free',
      'Runs whisper-quiet below 26 dB on the low setting',
    ],
    includes: ['USB-A to USB-B cable'],
  },
  {
    name: 'Wireless Lavalier Microphone Set', category: 'electronics', type: 'PHYSICAL',
    price: 38500, seller: 'alabi-techhub',
    material: 'ABS transmitters, windscreen foam',
    dimensions: 'Tx 6 × 2.5 cm each; case 17 × 9 × 4 cm',
    colours: ['Black'],
    namedVariants: ['— Single Mic', '— Dual Mic Interview Kit (₦52900)'],
    features: [
      '2.4 GHz wireless with 65 m line-of-sight range for walk-and-talk video',
      'Noise cancellation and reverb modes selectable on the transmitter',
      'Charging case delivers two full recharges in the field',
      'Receiver works with phones (USB-C/Lightning per variant) and cameras',
    ],
    includes: ['Charging case', 'Furry windscreens', 'Cables per kit'],
  },
  {
    name: 'Smart Watch with Calling', category: 'electronics', type: 'PHYSICAL',
    price: 38900, seller: 'alabi-techhub',
    material: 'Alloy case, silicone strap (extra mesh strap included)',
    dimensions: 'Case 44 mm; fits 15–22 cm wrists',
    colours: ['Midnight Black', 'Silver', 'Gold'],
    namedVariants: ['— Silicone Strap', '— Mesh Strap Edition (₦41900)'],
    features: [
      'Place and answer calls from the wrist via Bluetooth to the phone',
      '1.9" AMOLED-style display with 100+ watch faces',
      'SpO2, heart-rate and sleep tracking with weekly reports',
      'IP68 splash-proof for rain and handwashing',
    ],
    includes: ['Magnetic charger', 'Spare strap'],
  },
  {
    name: 'Magnetic Power Bank', category: 'electronics', type: 'PHYSICAL',
    price: 23900, seller: 'alabi-techhub',
    material: 'Aluminium back, magnet array, matte finish',
    dimensions: '10.5 × 6.6 × 1.5 cm, 5000 mAh',
    colours: ['Graphite', 'Mist Blue'],
    namedVariants: ['— 5000 mAh', '— 10000 mAh (₦34900)'],
    features: [
      'Snaps to MagSafe-compatible phones for cable-free top-ups',
      'Also charges anything via the built-in USB-C cable loop',
      'LED percentage display — no guessing the remaining charge',
      'Pass-through charging tops the bank and phone overnight from one socket',
    ],
  },
  {
    name: 'HDMI 2.0 Cable', category: 'electronics', type: 'PHYSICAL',
    price: 6500, seller: 'alabi-techhub',
    material: 'Braided nylon jacket, gold-plated connectors',
    dimensions: 'Available in three lengths',
    colours: ['Black braid'],
    namedVariants: ['— 1.5 m', '— 3 m', '— 5 m (₦9500)'],
    features: [
      'Certified 18 Gbps bandwidth carries 4K@60 HDR without dropouts',
      'Ethernet channel and ARC supported for soundbars',
      'Braided jacket and ferrite cores resist interference',
      'Tested for 10,000-bend flex life',
    ],
  },
  {
    name: 'USB Card Reader', category: 'electronics', type: 'PHYSICAL',
    price: 5500, seller: 'alabi-techhub',
    material: 'Aluminium shell',
    dimensions: '6.5 × 2 × 1 cm',
    colours: ['Gunmetal'],
    namedVariants: ['— SD + microSD', '— CFexpress Pro (₦18900)'],
    features: [
      'Reads SD and microSD simultaneously — copy from both cards at once',
      'USB 3.2 Gen 1 speeds offload a 32 GB card in a few minutes',
      'Pop-out design protects the ports in a camera bag',
      'Works with phones that support USB-C storage access',
    ],
  },
  {
    name: 'Office Headset with Boom Mic', category: 'electronics', type: 'PHYSICAL',
    price: 18500, seller: 'alabi-techhub',
    material: 'Protein-leather pads, steel slider',
    dimensions: 'Single-ear 180 g',
    colours: ['Black'],
    namedVariants: ['— USB-A', '— USB-C + 3.5mm (₦21500)'],
    features: [
      'Noise-cancelling boom mic so callers hear you, not the generator',
      'Padded earpad stays comfortable through back-to-back calls',
      'In-line volume and mute within thumb reach',
      'Certified to work with the usual meeting apps',
    ],
  },
  {
    name: 'Wi-Fi Range Extender', category: 'electronics', type: 'PHYSICAL',
    price: 13900, seller: 'alabi-techhub',
    material: 'Wall-plug PC shell, dual antennas',
    dimensions: '9 × 6 × 4 cm (indoor wall plug)',
    colours: ['White'],
    features: [
      'Repeats the router signal into rooms the Wi-Fi barely reaches',
      'Dual-band AC1200 with a smart signal indicator for placement',
      'Ethernet port can also act as a wired access point',
      'WPS one-press pairing where the router supports it',
    ],
  },
  {
    name: 'Precision Stylus for Tablets', category: 'electronics', type: 'PHYSICAL',
    price: 16900, seller: 'alabi-techhub',
    material: 'Anodised aluminium barrel, 1.5 mm POM tip',
    dimensions: '16.5 cm long, 14 g',
    colours: ['White', 'Black'],
    namedVariants: ['— Standard', '— With Tilt Support (₦21900)'],
    features: [
      'Palm rejection lets you rest your hand while writing',
      'Magnetic attachment charges on the tablet edge where supported',
      '8 hours of writing per 40-minute charge',
      'Tilt support shades like a pencil in sketching apps (Pro variant)',
    ],
    includes: ['Spare nibs ×2', 'Nib tool'],
  },
  {
    name: 'Car Dash Camera', category: 'electronics', type: 'PHYSICAL',
    price: 29900, seller: 'alabi-techhub',
    material: 'Heat-resistant housing, supercapacitor power',
    dimensions: '6 × 4 × 3.5 cm windshield mount',
    colours: ['Black'],
    namedVariants: ['— Front Only', '— Front + Rear Kit (₦42900)'],
    features: [
      '1080p@30 with a 170° lens capturing three lanes',
      'Supercapacitors survive Nigerian heat better than lithium packs',
      'G-sensor locks emergency clips so loop recording cannot overwrite them',
      'Wi-Fi app preview to pull footage to a phone without pulling the card',
    ],
    includes: ['32 GB microSD', 'Electrostatic mount film', 'Car charger'],
  },
  {
    name: 'Tablet Keyboard Folio Case', category: 'electronics', type: 'PHYSICAL',
    price: 24900, seller: 'alabi-techhub',
    material: 'PU leather folio, ABS keywell',
    dimensions: 'Fits 10.2–10.9" tablets',
    colours: ['Black', 'Burgundy'],
    features: [
      'Low-profile keys with a proper row of shortcuts',
      'Pencil holder keeps the stylus with the kit',
      'Multiple viewing angles with a magnetic latch',
      'Six-month battery on a single charge (USB-C)',
    ],
  },
  {
    name: '4G LTE Mobile Router', category: 'electronics', type: 'PHYSICAL',
    price: 49900, seller: 'alabi-techhub',
    material: 'Matte plastic shell, 2400 mAh battery',
    dimensions: '11 × 6.5 × 1.8 cm, 180 g',
    colours: ['Black'],
    namedVariants: ['— Cat4 150 Mbps', '— Cat6 300 Mbps (₦64900)'],
    features: [
      'Shares a data SIM as Wi-Fi for up to 10 devices',
      'Unlock-any-SIM firmware works with the major Nigerian networks',
      'Battery covers a workday; USB-C keeps it running plugged in',
      'Screen shows signal, data used and connected devices',
    ],
    includes: ['SIM tray tool', 'USB-C cable'],
  },
  {
    name: 'Under-Desk Cable Management Tray', category: 'electronics', type: 'PHYSICAL',
    price: 8900, seller: 'alabi-techhub',
    material: 'Powder-coated steel mesh',
    dimensions: '40 × 11 × 6 cm (2 sizes)',
    colours: ['Black'],
    namedVariants: ['— 40 cm', '— 60 cm (₦11500)'],
    features: [
      'Keeps power strips and cable spaghetti off the floor and out of sight',
      'Ventilated mesh never traps adapter heat',
      'Screws or clamps to desk edges up to 4 cm thick',
      'Holds up to 8 kg of adapters and cabling',
    ],
    includes: ['Mounting screws', 'Cable ties ×6'],
  },
  {
    name: 'Travel Power Strip with USB', category: 'electronics', type: 'PHYSICAL',
    price: 11900, seller: 'alabi-techhub',
    material: 'Flame-retardant housing, 1.8 m cord',
    dimensions: 'Three sockets + 2 USB-A; 15 × 5 × 3 cm',
    colours: ['White', 'Black'],
    features: [
      'Three universal sockets turn one hotel outlet into a workstation',
      'Two USB-A ports handle watches and phones without their bricks',
      'Surge protection guards laptops from grid spikes',
      'Compact cube shape packs flat in luggage',
    ],
  },
  {
    name: 'Bluetooth Audio Receiver for Home Stereos', category: 'electronics', type: 'PHYSICAL',
    price: 10500, seller: 'alabi-techhub',
    material: 'Aluminium case',
    dimensions: '6 × 4.5 × 1.5 cm',
    colours: ['Space Grey'],
    features: [
      'Gives an old amplifier Bluetooth through its AUX or RCA input',
      'aptX-capable codec when the phone supports it',
      'NFC tap-to-pair for quick connections',
      'Powered by any USB socket — no wall wart in the box to bin',
    ],
    includes: ['3.5 mm cable', 'RCA adapter'],
  },
  {
    name: 'Mechanical Numpad Macro Pad', category: 'electronics', type: 'PHYSICAL',
    price: 17500, seller: 'alabi-techhub',
    material: 'Acrylic case, PBT keycaps',
    dimensions: '12 × 9 × 3.5 cm, 5 keys + knob',
    colours: ['Clear Acrylic', 'Smoked'],
    features: [
      'Five programmable keys and a rotary knob for scenes, mute or scrubbing',
      'Open-source firmware remaps every control per layer',
      'Hot-swap sockets accept any 3/5-pin switch',
      'USB-C with a braided detachable cable',
    ],
    includes: ['Spare switches ×2', 'Keycap puller'],
  },

  // ═══ AMARA LUXE ATELIER — fashion, bags, shoes, accessories ═══════════
  {
    name: 'Ankara Print Wrap Dress', category: 'fashion', type: 'PHYSICAL',
    price: 24500, seller: 'amara-luxe-atelier',
    material: '100% cotton Ankara, lined bodice',
    dimensions: 'Knee-length; true to size (UK 8–18)',
    colours: ['Indigo Geometric', 'Coral Bloom', 'Forest Fan', 'Sunburst Amber'],
    sizes: ['UK 8', 'UK 10', 'UK 12', 'UK 14', 'UK 16'],
    features: [
      'True wrap construction adjusts to the waist rather than a fixed seam',
      'Sleeve tabs hold a rolled cuff in place all day',
      'Fully lined bodice means no separate slip needed',
      'Side-seam pockets deep enough for a phone',
    ],
    care: 'Cold hand wash first time, then gentle machine cycle in a laundry bag.',
  },
  {
    name: 'Embroidered Kaftan', category: 'fashion', type: 'PHYSICAL',
    price: 28500, seller: 'amara-luxe-atelier',
    material: 'Chiffon overlay over crepe lining',
    dimensions: 'Ankle-length free size (fits up to UK 20)',
    colours: ['Champagne', 'Royal Blue', 'Emerald'],
    features: [
      'Hand-guided machine embroidery along the placket and cuffs',
      'Crepe lining keeps the sheer overlay modest and cool',
      'Drawcord ties adjust the fit without tailoring',
      'Packs small and shakes out creases when hung in steam',
    ],
    care: 'Dry clean recommended to protect the embroidery thread.',
  },
  {
    name: 'Men\'s Senator Two-Piece Set', category: 'fashion', type: 'PHYSICAL',
    price: 39500, seller: 'amara-luxe-atelier',
    material: 'Italian-styled cashmere-blend senator fabric',
    dimensions: 'Top and trousers; sizes 46–58 (chest)',
    colours: ['Black', 'Wine', 'Royal Blue', 'Ivory'],
    sizes: ['46', '48', '50', '52', '54', '56'],
    features: [
      'Ankara-free classic cut with a mandarin collar and hidden buttons',
      'Trousers carry a half-lined seat for shape without bulk',
      'Fabric has a soft fall that resists wrinkling at events',
      'Local tailoring finish — overlocked inside seams, bar-tacked stress points',
    ],
    care: 'Dry clean; steam rather than iron the collar.',
  },
  {
    name: 'Cord Two-Piece Set', category: 'fashion', type: 'PHYSICAL',
    price: 21500, seller: 'amara-luxe-atelier',
    material: 'Corduroy with a touch of stretch',
    dimensions: 'Cropped top + high-waist trousers (UK 8–16)',
    colours: ['Camel', 'Sage', 'Chocolate', 'Dusty Pink'],
    sizes: ['UK 8', 'UK 10', 'UK 12', 'UK 14', 'UK 16'],
    features: [
      'Wide-wale cord that reads vintage but cuts modern',
      'Elasticated back waist with a flat front for comfort',
      'Top ties at the front with generous cap sleeves',
      'Sold as a set; pieces mix back with denim and tees',
    ],
    care: 'Turn inside out, wash cool, hang dry to keep the wale crisp.',
  },
  {
    name: 'Silk-Touch Headwrap Collection', category: 'fashion', type: 'PHYSICAL',
    price: 8500, seller: 'amara-luxe-atelier',
    material: 'Satin-edged georgette, 72 × 180 cm',
    dimensions: 'One size; generous 1.8 m length for full wraps',
    colours: ['Terracotta', 'Peacock', 'Noir Gold Edge', 'Pearl'],
    features: [
      'Satin edge grips without snagging edges or lines',
      'Matte face with a subtle sheen that photographs well',
      'Long enough for full coverage and padded styles',
      'Hand-finished hems, no raw edges',
    ],
  },
  {
    name: 'Full-Grain Leather Slides', category: 'fashion', type: 'PHYSICAL',
    price: 22500, seller: 'amara-luxe-atelier',
    material: 'Full-grain leather straps, cushioned rubber sole',
    dimensions: 'Sizes 38–46',
    colours: ['Tan', 'Black', 'Cognac'],
    sizes: ['38', '39', '40', '41', '42', '43', '44', '45'],
    features: [
      'Straps are cut from a single hide piece — no glued seams to split',
      'Memory-foam footbed under a suede lining',
      'Stitched and screwed sole, resoleable at a cobbler',
      'Runs true to size; half sizes should size up',
    ],
    care: 'Condition leather every few months; keep out of prolonged soak.',
  },
  {
    name: 'Structured Leather Tote', category: 'fashion', type: 'PHYSICAL',
    price: 46500, seller: 'amara-luxe-atelier',
    material: 'Pebbled full-grain leather, brass hardware',
    dimensions: '36 × 28 × 13 cm; fits a 15" laptop',
    colours: ['Black', 'Cognac', 'Bottle Green'],
    features: [
      'Holds shape empty thanks to reinforced base panel',
      'Interior zip pocket plus twin slip pockets',
      'Magnetic top closure that stays shut when overfilled',
      'Handles sized to sit on the shoulder without slipping',
    ],
    includes: ['Dust bag'],
  },
  {
    name: 'Beaded Evening Clutch', category: 'fashion', type: 'PHYSICAL',
    price: 17500, seller: 'amara-luxe-atelier',
    material: 'Glass beads hand-sewn on canvas frame',
    dimensions: '24 × 14 × 6 cm',
    colours: ['Gold', 'Silver Mist', 'Onyx'],
    features: [
      'Seed-bead lattice takes a bead artisan about a day per piece',
      'Detachable chain tucks inside for a handheld look',
      'Suede-lined interior with a card slot',
      'Kiss-lock frame closes with a satisfying snap',
    ],
  },
  {
    name: 'Woven Leather Belt', category: 'fashion', type: 'PHYSICAL',
    price: 11500, seller: 'amara-luxe-atelier',
    material: 'Hand-woven leather straps, solid brass buckle',
    dimensions: 'Width 3.5 cm; sizes 85–115 cm',
    colours: ['Tan', 'Dark Brown', 'Black'],
    sizes: ['85', '95', '105', '115'],
    features: [
      'Woven construction adjusts anywhere — no punched holes to crack',
      'Solid brass buckle that patinas rather than flakes',
      'Edge-painted straps against fraying',
      'Suits chinos and senator trousers alike',
    ],
  },
  {
    name: 'Statement Brass Earrings', category: 'fashion', type: 'PHYSICAL',
    price: 9500, seller: 'amara-luxe-atelier',
    material: 'Hand-cut brass, stainless posts',
    dimensions: 'Drop length 6–7 cm, featherweight',
    colours: ['Polished Gold-Tone', 'Antique Brass'],
    features: [
      'Cut and filed by hand — each pair differs slightly in texture',
      'Stainless steel posts suit sensitive ears',
      'Large look at under 8 g per earring',
      'Arrives on a branded card ready to gift',
    ],
  },
  {
    name: 'Minimalist Alloy Watch', category: 'fashion', type: 'PHYSICAL',
    price: 32500, seller: 'amara-luxe-atelier',
    material: '316L stainless case, sapphire-coated glass, leather strap',
    dimensions: 'Case 38 mm (unisex); lug 20 mm',
    colours: ['Silver/Black Dial', 'Gold/White Dial', 'Gunmetal/Blue Dial'],
    features: [
      'Japanese quartz movement with a two-year cell life',
      'Sapphire-coated glass shrugs off desk-knife scratches',
      'Quick-release strap swaps without tools',
      '5 ATM splash-proof rating',
    ],
    includes: ['Spare mesh strap', 'Travel pouch'],
  },
  {
    name: 'Polarized Acetate Sunglasses', category: 'fashion', type: 'PHYSICAL',
    price: 15500, seller: 'amara-luxe-atelier',
    material: 'Italian acetate frames, polarized CR-39 lenses',
    dimensions: 'Lens 52 mm; unisex fit',
    colours: ['Tortoise', 'Matte Black', 'Crystal Rose'],
    features: [
      'Polarized lenses cut road and water glare properly, not just dimly',
      'Acetate frames adjust with gentle heat instead of snapping',
      'UV400 protection against UVA/UVB',
      'Spring hinges survive being shoved on with one hand',
    ],
    includes: ['Hard case', 'Microfibre pouch'],
  },
  {
    name: 'Hand-Loomed Cotton Kaftan Top', category: 'fashion', type: 'PHYSICAL',
    price: 13500, seller: 'amara-luxe-atelier',
    material: 'Hand-loomed cotton, boxy cut',
    dimensions: 'Free size to UK 18; length 68 cm',
    colours: ['White Stripe', 'Indigo Stripe', 'Clay'],
    features: [
      'Woven on hand looms in small batches — slight irregularities are the point',
      'Boxy cut skims rather than clings in the heat',
      'Split hem sides for movement',
      'Breathes through dry-season afternoons',
    ],
    care: 'Machine wash cool; the cotton softens with every wash.',
  },
  {
    name: 'Pleated Midi Skirt', category: 'fashion', type: 'PHYSICAL',
    price: 16500, seller: 'amara-luxe-atelier',
    material: 'Recycled chiffon pleats, satin waistband',
    dimensions: 'Waist 64–86 cm elasticated; length 84 cm',
    colours: ['Emerald', 'Rust', 'Dusty Blue', 'Black'],
    sizes: ['S', 'M', 'L', 'XL'],
    features: [
      'Heat-set pleats survive wash cycles without re-ironing',
      'Concealed side zip with a fully elasticated back panel',
      'Swings properly when walking — weighty hem, not limp chiffon',
      'Satin-covered waistband sits flat under tops',
    ],
  },
  {
    name: 'Tailored Oxford Shirt', category: 'fashion', type: 'PHYSICAL',
    price: 18500, seller: 'amara-luxe-atelier',
    material: 'Heavyweight cotton oxford, mother-of-pearl buttons',
    dimensions: 'Regular fit; sizes S–XXL',
    colours: ['White', 'Pale Blue', 'Stone'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    features: [
      'Yarn-dyed oxford that reads crisp rather than shiny',
      'Single-needle stitching at 18 stitches per inch',
      'Split yoke holds shape across the shoulders',
      'Third button sits high enough for ties to knot cleanly',
    ],
    care: 'Machine wash warm; touch up with a hot iron while slightly damp.',
  },
  {
    name: 'Slim Chino Trousers', category: 'fashion', type: 'PHYSICAL',
    price: 19500, seller: 'amara-luxe-atelier',
    material: '2% stretch cotton twill',
    dimensions: 'Waists 30–40; inseam 30" hemmed',
    colours: ['Khaki', 'Navy', 'Olive', 'Charcoal'],
    sizes: ['30', '32', '34', '36', '38', '40'],
    features: [
      'A whisper of stretch for squatting, riding and long days',
      'Hidden coin pocket keeps cards flat',
      'Clean-finished waistband with curtain for tucked shirts',
      'Hemmed to a standard 30" inseam — cobbler-friendly',
    ],
  },
  {
    name: 'Suede Loafers', category: 'fashion', type: 'PHYSICAL',
    price: 34500, seller: 'amara-luxe-atelier',
    material: 'Suede upper, leather-lined, rubber-studded sole',
    dimensions: 'Sizes 39–46',
    colours: ['Tobacco', 'Navy', 'Stone Grey'],
    sizes: ['39', '40', '41', '42', '43', '44', '45', '46'],
    features: [
      'Blake-stitched construction flexes from the first wear',
      'Rubber studs grip polished floors and rain-slick paving',
      'Unlined heel counter prevents the blister phase',
      'Classic apron front that dresses up jeans',
    ],
    care: 'Brush suede with a crepe brush; protect with suede spray.',
  },
  {
    name: 'Woven Slingback Sandals', category: 'fashion', type: 'PHYSICAL',
    price: 18500, seller: 'amara-luxe-atelier',
    material: 'Vegetable-tanned straps, cushioned insole',
    dimensions: 'Sizes 36–43; 2 cm heel',
    colours: ['Nude Tan', 'Black', 'Off-White'],
    sizes: ['36', '37', '38', '39', '40', '41', '42', '43'],
    features: [
      'Woven straps stretch and mould to the foot within a week',
      'Elasticised slingback keeps them on without pinching',
      'Pigskin-lined insole absorbs the day',
      'Low block heel is steady on cobblestones and tiles',
    ],
  },
  {
    name: 'Layered Chain Jewelry Set', category: 'fashion', type: 'PHYSICAL',
    price: 12500, seller: 'amara-luxe-atelier',
    material: '18k gold-plated brass, lobster clasps',
    dimensions: 'Three chains 40/45/50 cm (necklace) + matching bracelet',
    colours: ['Gold-Tone', 'Silver-Tone'],
    features: [
      'Three necklaces engineered not to tangle into one knot',
      '2.5-micron plating over brass resists the tarnish of cheaper sets',
      'Lobster clasps sized for actual fingers',
      'Nickel-free and stamped 18k on each tag',
    ],
    includes: ['Gift box', 'Care card'],
  },
  {
    name: 'Raffia Fringe Tote', category: 'fashion', type: 'PHYSICAL',
    price: 19500, seller: 'amara-luxe-atelier',
    material: 'Hand-woven raffia with cotton lining',
    dimensions: '40 × 34 × 12 cm',
    colours: ['Natural', 'Black Raffia'],
    features: [
      'Genuine raffia weave with a fabric-lined body that protects contents',
      'Interior zip pocket among the straw texture',
      'Fringe trim cut by hand — a little shedding at first is normal',
      'Beach to market to brunch without apology',
    ],
  },
  {
    name: 'Quilted Crossbody Bag', category: 'fashion', type: 'PHYSICAL',
    price: 22500, seller: 'amara-luxe-atelier',
    material: 'Vegan nappa, brushed gold hardware',
    dimensions: '22 × 15 × 7 cm; strap drop 55–120 cm',
    colours: ['Black', 'Cream', 'Bordeaux'],
    features: [
      'Adjustable webbing strap converts from crossbody to shoulder',
      'Three card slots hidden behind the front panel',
      'Zip-top with a leather pull sized for fingers',
      'Base feet keep the nappa off café tables',
    ],
  },
  {
    name: 'Adire-Dyed Kimono Jacket', category: 'fashion', type: 'PHYSICAL',
    price: 26500, seller: 'amara-luxe-atelier',
    material: 'Indigo adire cotton, unlined',
    dimensions: 'Free size to UK 20; length 92 cm',
    colours: ['Indigo Tie-Dye', 'Indigo Stencil'],
    features: [
      'Each panel is tie-dyed by hand — no two kimonos match exactly',
      'Natural indigo will soften and fade characterfully',
      'Drop shoulders and open front layer over anything',
      'Side slits keep it breezy over trousers',
    ],
    care: 'Wash separately in cold water the first two times.',
  },
  {
    name: 'Men\'s Leather Driving Gloves', category: 'fashion', type: 'PHYSICAL',
    price: 14500, seller: 'amara-luxe-atelier',
    material: 'Deerskin, knuckle vents, snap wrist',
    dimensions: 'Sizes M–XXL',
    colours: ['Black', 'Brown'],
    sizes: ['M', 'L', 'XL', 'XXL'],
    features: [
      'Thin deerskin keeps steering feel without sacrificing grip',
      'Perforated knuckles vent heat in traffic',
      'Touchscreen-capable fingertips on index and thumb',
      'Snap closure at the wrist keeps them on when the window drops',
    ],
  },
  {
    name: 'Beaded Waist Chain', category: 'fashion', type: 'PHYSICAL',
    price: 6500, seller: 'amara-luxe-atelier',
    material: 'Glass and brass beads on coated wire',
    dimensions: 'Adjustable 80–105 cm',
    colours: ['Clear Crystal', 'Amber Mix', 'Onyx'],
    features: [
      'Strung on coated wire that will not snap mid-day',
      'Adjustable loop closure — no clasp fumbling',
      'Worn over or under clothing; beads stay put',
      'Ships in a small screw-top tube, not a tangle',
    ],
  },

  // ═══ ZURI HOME LIVING — interior, home & furniture ════════════════════
  {
    name: 'Ceramic Dinner Set (16-Piece)', category: 'interior-home', type: 'PHYSICAL',
    price: 68500, seller: 'zuri-home-living',
    material: 'Reactive-glaze stoneware',
    dimensions: 'Dinner plates 27 cm, side 20 cm, bowls 15 cm, mugs 350 ml',
    colours: ['Matte Sand', 'Slate Blue', 'Olive'],
    namedVariants: ['— 16-Piece (4 settings)', '— 32-Piece (8 settings) (₦128000)'],
    features: [
      'Reactive glaze pools differently on every piece — a matched family, not clones',
      'Chip-resistant rim tested for daily stacking',
      'Dishwasher, microwave and oven-safe to 220 °C',
      'Comfortably weighted rim rather than thin diner ware',
    ],
    includes: ['4 dinner plates', '4 side plates', '4 bowls', '4 mugs'],
  },
  {
    name: 'Seagrass Storage Baskets (Set of 3)', category: 'interior-home', type: 'PHYSICAL',
    price: 19500, seller: 'zuri-home-living',
    material: 'Hand-woven seagrass over wire frame',
    dimensions: 'S 28 × 20 cm, M 33 × 24 cm, L 38 × 28 cm',
    colours: ['Natural', 'Whitewash'],
    features: [
      'Wire frame lets these hold shape when filled with throws or toys',
      'Lined base keeps small items from slipping through the weave',
      'Handles stay cool near radiators and won\'t mark walls',
      'Nest inside each other when not in use',
    ],
  },
  {
    name: 'Arched Wall Mirror', category: 'interior-home', type: 'PHYSICAL',
    price: 42500, seller: 'zuri-home-living',
    material: 'Metal frame, 4 mm silvered glass',
    dimensions: '60 × 90 cm; hangs vertical or horizontal',
    colours: ['Antique Brass', 'Matte Black', 'Brushed Nickel'],
    features: [
      'True silvered glass — no funhouse warp at the edges',
      'Deep-set frame reads built-in rather than hung',
      'Two D-ring hangers pre-fitted; anchors included',
      'Backing board sealed against humid bathrooms',
    ],
    includes: ['Wall anchors and screws'],
  },
  {
    name: 'Ceramic Table Lamp with Linen Shade', category: 'interior-home', type: 'PHYSICAL',
    price: 36500, seller: 'zuri-home-living',
    material: 'Glazed ceramic base, linen drum shade',
    dimensions: 'Total height 52 cm; shade Ø 30 cm',
    colours: ['Off-White Base', 'Terracotta Base', 'Ink Blue Base'],
    features: [
      'Weighted base does not tip when adjusting the shade',
      'Inline dimmer dims to a genuine candle-glow low',
      'E27 socket takes standard bulbs (warm 2700 K recommended)',
      'Linen shade softly diffuses instead of glaring',
    ],
    includes: ['E27 bulb included'],
  },
  {
    name: 'Textured Throw Pillow Covers (Set of 2)', category: 'interior-home', type: 'PHYSICAL',
    price: 11500, seller: 'zuri-home-living',
    material: 'Cotton slub weave with hidden zip',
    dimensions: '45 × 45 cm (inserts sold separately)',
    colours: ['Oat', 'Terracotta', 'Sage', 'Charcoal'],
    features: [
      'Hidden YKK zips disappear when styled',
      'Generous covers fit plump 45 cm inserts without straining corners',
      'Colourfast dye — no crocking onto pale sofas',
      'Machine washable on gentle, air dry flat',
    ],
  },
  {
    name: 'Washable Area Rug', category: 'interior-home', type: 'PHYSICAL',
    price: 58500, seller: 'zuri-home-living',
    material: 'Low-pile polyester weave, cotton backing',
    dimensions: '160 × 230 cm (3 sizes)',
    colours: ['Ivory/Bone Pattern', 'Slate Geometric', 'Terracotta Border'],
    namedVariants: ['— 120 × 180 cm', '— 160 × 230 cm', '— 200 × 290 cm (₦98500)'],
    features: [
      'Machine-washable in two halves — the honest answer to real homes',
      'Low pile slides under doors and vacuums without tangling',
      'Anti-slip backing needs no separate underlay on tiles',
      'Pattern woven in, not printed — no fade lines at the traffic lanes',
    ],
  },
  {
    name: 'Blackout Curtains (Pair)', category: 'interior-home', type: 'PHYSICAL',
    price: 32500, seller: 'zuri-home-living',
    material: 'Triple-weave blackout fabric, eyelet finish',
    dimensions: 'Each panel 140 × 240 cm (3 lengths)',
    colours: ['Charcoal', 'Beige', 'Navy'],
    namedVariants: ['— 240 cm Drop', '— 270 cm Drop (₦36500)', '— 300 cm Drop (₦39500)'],
    features: [
      'Triple-weave blocks roughly 85–90% of light without a plastic face',
      'Eyelet finish slides on 28 mm rods smoothly',
      'Also buffers street noise and window heat',
      'Widths generously cut to gather properly, not stretched flat',
    ],
  },
  {
    name: 'Percale Bedding Set', category: 'interior-home', type: 'PHYSICAL',
    price: 44500, seller: 'zuri-home-living',
    material: '400-thread-count cotton percale',
    dimensions: 'Fits mattresses to 30 cm deep',
    colours: ['White', 'Sand', 'Sage Stripe'],
    namedVariants: ['— King', '— Queen (₦39500)', '— Single (₦27500)'],
    features: [
      'Crisp percale that sleeps cool in the humidity',
      'Deep-pocket fitted sheet with proper elastic all around',
      'OEKO-TEX certified dyes — no chemical smell on opening',
      'Two pillowcases included, envelope closure',
    ],
    includes: ['Fitted sheet', 'Flat sheet', '2 pillowcases'],
  },
  {
    name: 'Framed Abstract Print Set', category: 'interior-home', type: 'PHYSICAL',
    price: 28500, seller: 'zuri-home-living',
    material: 'Giclée print on 250 gsm matte paper, oak-look frame',
    dimensions: 'Each frame A2 (42 × 59.4 cm)',
    colours: ['Dunes Triptych', 'Coast Diptych', 'Botanical Pair'],
    features: [
      'Giclée pigment inks — no banding or orange shift over time',
      'Shatterproof acrylic glazing instead of glass',
      'Arrives strung and ready to hang',
      'Printed with a 2 cm white border for a gallery feel',
    ],
  },
  {
    name: 'Stoneware Vase Trio', category: 'interior-home', type: 'PHYSICAL',
    price: 18500, seller: 'zuri-home-living',
    material: 'Speckled stoneware, sealed interior',
    dimensions: 'H 24 / 18 / 13 cm',
    colours: ['Ivory Speckle', 'Charcoal Speckle'],
    features: [
      'Watertight interiors handle fresh stems without a liner',
      'Weighted bottoms suit tall branches',
      'Matte exterior with raw-foot base detail',
      'Group as a trio or scatter through shelves',
    ],
  },
  {
    name: 'Ladder Bookshelf', category: 'furniture', type: 'PHYSICAL',
    price: 78500, seller: 'zuri-home-living',
    material: 'Solid rubberwood and engineered panel',
    dimensions: 'H 180 cm; 5 shelves 60 cm wide; leans to wall',
    colours: ['Natural Oak Look', 'Walnut Look', 'Matte Black'],
    features: [
      'Leaning profile anchors against the wall — no floor fixing needed',
      'Anti-tip strap included for peace of mind',
      'Shelves hold 15 kg each — real books, not just decor',
      'Flat-packs into two boxes with cam-lock assembly under an hour',
    ],
    leadTime: 'Made to order — dispatches in 5–7 working days.',
  },
  {
    name: 'Coffee Table with Storage', category: 'furniture', type: 'PHYSICAL',
    price: 96500, seller: 'zuri-home-living',
    material: 'MDF body, oak-look veneer, metal legs',
    dimensions: '110 × 60 × 42 cm; two sliding doors',
    colours: ['Oak Look/Black Legs', 'Walnut Look/Brass Legs'],
    features: [
      'Sliding doors hide remotes, cables and the console clutter',
      'Push-open doors — no handles to catch hips',
      'Powder-coated steel legs with adjustable feet for uneven tiles',
      'Matte laminate wipes clean of coffee rings',
    ],
    leadTime: 'Made to order — dispatches in 5–7 working days.',
  },
  {
    name: 'Upholstered Dining Chair (Set of 2)', category: 'furniture', type: 'PHYSICAL',
    price: 88500, seller: 'zuri-home-living',
    material: 'Boucle upholstery, beech frame, webbed seat',
    dimensions: 'Seat H 46 cm; back H 88 cm',
    colours: ['Cream Boucle', 'Ash Grey Boucle'],
    namedVariants: ['— Set of 2', '— Set of 4 (₦165000)'],
    features: [
      'Webbed suspension under the foam — no hammock sag after a year',
      'Beech legs with felt pads for tile floors',
      'Boucle spot-cleans with a damp cloth',
      'Assembles in about ten minutes per chair',
    ],
    includes: ['Assembly tool', 'Felt pads'],
  },
  {
    name: 'Bedside Table with Drawer', category: 'furniture', type: 'PHYSICAL',
    price: 54500, seller: 'zuri-home-living',
    material: 'Engineered wood body, rattan-look drawer front',
    dimensions: '45 W × 40 D × 55 H cm',
    colours: ['Oak Look/Natural Cane', 'White/Rattan Front'],
    features: [
      'Soft-close drawer on metal runners — no midnight slam',
      'Open shelf keeps the current read at hand',
      'Cable notch at the back for lamp cords',
      'Anti-tip strap included',
    ],
    leadTime: 'Made to order — dispatches in 4–6 working days.',
  },
  {
    name: 'TV Stand Console', category: 'furniture', type: 'PHYSICAL',
    price: 118000, seller: 'zuri-home-living',
    material: 'Laminate body, powder-coated legs',
    dimensions: '160 W × 40 D × 45 H cm; suits up to 70" TVs',
    colours: ['Walnut Look', 'Oak Look'],
    features: [
      'Cable ports at the back keep the console clean behind the screen',
      'Two fluted sliding doors on quiet runners',
      'Adjustable interior shelf for consoles and decoders',
      'Supports 45 kg on the top panel',
    ],
    leadTime: 'Made to order — dispatches in 7–10 working days.',
  },
  {
    name: 'Wardrobe Organizer Set', category: 'interior-home', type: 'PHYSICAL',
    price: 13500, seller: 'zuri-home-living',
    material: 'Breathable non-woven fabric, steel frames',
    dimensions: '6 drawer boxes + 2 hanging shelves',
    colours: ['Grey', 'Beige'],
    features: [
      'Collapsible drawer boxes stack on wardrobe shelves without sagging',
      'Steel-framed hanging shelves hold folded knits',
      'Front labels window to see contents without unstacking',
      'Folds flat when moving house',
    ],
  },
  {
    name: 'Airtight Kitchen Canister Set', category: 'interior-home', type: 'PHYSICAL',
    price: 22500, seller: 'zuri-home-living',
    material: 'Powder-coated steel with bamboo lids and silicone seals',
    dimensions: '1.6 L, 1.2 L, 0.8 L',
    colours: ['Matte Black', 'Cream', 'Sage'],
    features: [
      'Silicone gaskets keep garri, flour and sugar genuinely airtight',
      'Window slot to see fill level without lifting the lid',
      'Bamboo lids double as serving trays',
      'Wide mouths fit a standard measuring scoop',
    ],
  },
  {
    name: 'Upholstered Bar Stool', category: 'furniture', type: 'PHYSICAL',
    price: 46500, seller: 'zuri-home-living',
    material: 'Faux-leather seat, steel frame, footrest',
    dimensions: 'Seat H 65 cm (counter); 75 cm (bar)',
    colours: ['Caramel', 'Black', 'Grey'],
    namedVariants: ['— Counter 65 cm', '— Bar 75 cm'],
    features: [
      '360° swivel with a controlled return, not a spin',
      'Gas-lift height adjustment in the counter variant',
      'Rubber-ringed base protects floors',
      'Welded footrest does not creak under weight',
    ],
  },
  {
    name: 'Tripod Floor Lamp', category: 'interior-home', type: 'PHYSICAL',
    price: 48500, seller: 'zuri-home-living',
    material: 'Solid rubberwood legs, linen shade',
    dimensions: 'H 150 cm; shade Ø 40 cm',
    colours: ['Natural Wood', 'Charcoal Wood'],
    features: [
      'Genuine tripod stance that stays planted on rugs',
      'Linen shade throws warm, even light for living rooms',
      'Foot-operated inline switch',
      'E27 socket, bulb included',
    ],
    includes: ['E27 warm bulb'],
  },
  {
    name: 'Silent Wall Clock', category: 'interior-home', type: 'PHYSICAL',
    price: 11500, seller: 'zuri-home-living',
    material: 'Bamboo rim, glass lens, sweep movement',
    dimensions: 'Ø 30 cm; runs on one AA cell',
    colours: ['Natural Bamboo', 'Black Rim'],
    features: [
      'Sweep second hand — genuinely silent for bedrooms',
      'Glass lens wipes clean; cheap acrylic alternatives scratch cloudy',
      'Accurate quartz movement that keeps time for years',
      'Single AA cell runs about a year',
    ],
  },
  {
    name: 'Under-Sink Organizer Rack', category: 'interior-home', type: 'PHYSICAL',
    price: 9500, seller: 'zuri-home-living',
    material: 'Coated steel mesh, adjustable shelves',
    dimensions: 'Expands 50–80 cm wide; 38 cm deep',
    colours: ['White'],
    features: [
      'Shelves adjust around the trap pipe instead of wasting that space',
      'Coated mesh wipes down and never rusts in damp cabinets',
      'Stackable two-tier design doubles vertical storage',
      'Assembly without tools in about five minutes',
    ],
  },
  {
    name: 'Woven Pendant Light Shade', category: 'interior-home', type: 'PHYSICAL',
    price: 16500, seller: 'zuri-home-living',
    material: 'Hand-woven raffia over steel frame',
    dimensions: 'Ø 40 cm; drop adjustable to 120 cm',
    colours: ['Natural', 'Charcoal Wash'],
    features: [
      'Ships flat-packed and pops into shape in a minute',
      'Standard E27 fitting reuses the existing bulb holder',
      'Cable adjustable for dining tables or corners',
      'Throws a warm dappled pattern when lit',
    ],
    includes: ['Cable and ceiling rose kit'],
  },

  // ═══ WELLSPRING WELLNESS CO. — health, wellness, beauty ═══════════════
  {
    name: 'Non-Slip Yoga Mat', category: 'health-wellness', type: 'PHYSICAL',
    price: 15500, seller: 'wellspring-wellness-co',
    material: 'TPE dual-layer, closed cell',
    dimensions: '183 × 61 cm × 6 mm',
    colours: ['Sage', 'Charcoal', 'Blush'],
    namedVariants: ['— 6 mm', '— 8 mm Extra Cushion (₦18500)'],
    features: [
      'Closed-cell surface will not absorb sweat or smell',
      'Laser-etched alignment lines for hand and foot placement',
      'Grip stays true when palms get damp',
      'Strap included — rolls tight and carries like a shoulder bag',
    ],
    includes: ['Carry strap'],
  },
  {
    name: 'Resistance Bands Set', category: 'health-wellness', type: 'PHYSICAL',
    price: 9500, seller: 'wellspring-wellness-co',
    material: 'Layered natural latex with fabric sleeves',
    dimensions: 'Five bands 10–50 lb equivalent; 150 cm long',
    colours: ['Multi (5 levels)'],
    namedVariants: ['— Loop Bands (5)', '— Tube Bands with Handles (₦12500)'],
    features: [
      'Five graded resistances from warm-up to heavy rows',
      'Fabric-sleeved tubes in the handle variant will not snap to skin',
      'Door anchor and ankle straps turn any room into a gym',
      'Ships with a printed exercise card, not just a QR code',
    ],
    includes: ['Door anchor', 'Ankle straps', 'Carry bag'],
  },
  {
    name: 'Neoprene Dumbbell Pair', category: 'health-wellness', type: 'PHYSICAL',
    price: 12500, seller: 'wellspring-wellness-co',
    material: 'Cast iron core, neoprene coating',
    dimensions: 'Hexagonal heads prevent roll',
    colours: ['Slate', 'Plum'],
    namedVariants: ['— 2 × 2 kg', '— 2 × 3 kg (₦15500)', '— 2 × 5 kg (₦21500)'],
    features: [
      'Neoprene coat protects floors and keeps grip when hands sweat',
      'Hex heads stay put for renegade rows and push-up handles',
      'Comfort-contoured handle suits small and large hands',
      'Sold as a matched pair in the same weight',
    ],
  },
  {
    name: 'Textured Foam Roller', category: 'health-wellness', type: 'PHYSICAL',
    price: 11500, seller: 'wellspring-wellness-co',
    material: 'EVA over rigid hollow core',
    dimensions: '33 × 14 cm; supports up to 120 kg',
    colours: ['Lavender', 'Slate'],
    features: [
      'Firm core with a moulded texture for deeper release than smooth foam',
      'Will not warp or lose shape after months of daily use',
      'Hollow core doubles as storage for the resistance band',
      'Standard size suits quads, IT bands and upper back work',
    ],
  },
  {
    name: 'Weighted Jump Rope', category: 'health-wellness', type: 'PHYSICAL',
    price: 7500, seller: 'wellspring-wellness-co',
    material: 'Ball-bearing handles, PVC-coated steel cable',
    dimensions: 'Adjustable to 300 cm',
    colours: ['Black/Red', 'Black/Sky'],
    features: [
      'Ball-bearing rotation keeps rhythm smooth at speed',
      'Cable cuts to length with the included cutters — no excess to trip on',
      'Weighted handles build forearm endurance',
      'Spare cable included in the box',
    ],
    includes: ['Spare cable', 'Cutting tool', 'Travel pouch'],
  },
  {
    name: 'Insulated Stainless Bottle', category: 'health-wellness', type: 'PHYSICAL',
    price: 13500, seller: 'wellspring-wellness-co',
    material: 'Double-wall 316 stainless, powder-coated shell',
    dimensions: '750 ml; 27 cm tall',
    colours: ['Sage', 'Sand', 'Matte Black', 'Blush'],
    namedVariants: ['— 750 ml', '— 1 L (₦16500)'],
    features: [
      'Keeps water genuinely cold for 24 hours and heat for 12',
      'Powder coat grips dry hands and hides knocks',
      'Leak-proof twist cap with a carry loop',
      'Fits standard car cup holders',
    ],
  },
  {
    name: 'Herbal Tea Sampler Tin', category: 'health-wellness', type: 'PHYSICAL',
    price: 8500, seller: 'wellspring-wellness-co',
    material: 'Loose-leaf blends in a lined steel tin',
    dimensions: 'Five 20 g tins in a gift carton',
    colours: ['Gift Carton'],
    namedVariants: ['— Five-Blend Sampler', '— Single Blend Refill (₦3500)'],
    features: [
      'Five caffeine-free blends: hibiscus ginger, lemongrass, moringa mint, rooibos, chamomile citrus',
      'Whole-leaf and flower cuts, not dust-grade fannings',
      'Airtight tins keep aromatics in for months',
      'Brewing notes on each lid lid — steep times that actually work',
    ],
  },
  {
    name: 'Percussion Massage Gun', category: 'health-wellness', type: 'PHYSICAL',
    price: 42500, seller: 'wellspring-wellness-co',
    material: 'Aluminium body, silicone-gripped handle',
    dimensions: '24 × 22 × 7 cm; 1 kg with case',
    colours: ['Graphite'],
    namedVariants: ['— Mini', '— Standard (this model)'],
    features: [
      'Five speeds from 1800 to 3200 percussions per minute',
      'Brushless motor runs under 45 dB — usable while the TV is on',
      'Six heads cover quads, shoulders, feet and knots',
      'Six-hour battery charges over USB-C',
    ],
    includes: ['Six heads', 'Hard carry case', 'USB-C charger'],
  },
  {
    name: 'Ultrasonic Aroma Diffuser', category: 'health-wellness', type: 'PHYSICAL',
    price: 16500, seller: 'wellspring-wellness-co',
    material: 'Ceramic-coated reservoir, PP body',
    dimensions: '300 ml tank; runs up to 10 hours',
    colours: ['Light Wood Look', 'Dark Wood Look'],
    namedVariants: ['— 300 ml', '— 500 ml (₦21500)'],
    features: [
      'Ultrasonic misting adds humidity along with scent — no heat',
      'Intermittent mode stretches a fill through the night',
      'Seven soft LED settings or fully off for sleep',
      'Auto shut-off when the tank runs dry',
    ],
    includes: ['Measuring cup'],
  },
  {
    name: 'Pilates Ring & Ball Kit', category: 'health-wellness', type: 'PHYSICAL',
    price: 12500, seller: 'wellspring-wellness-co',
    material: 'Fibreglass ring with foam grips, PVC mini ball',
    dimensions: 'Ring 38 cm; ball 25 cm',
    colours: ['Sage Kit', 'Blush Kit'],
    features: [
      'Ring gives light, controlled resistance for inner thighs and core',
      'Mini ball supports lower-back and deep-core work',
      'Foam pads on both grips stop pinching',
      'Includes a 20-exercise printed guide',
    ],
  },
  {
    name: 'Shea Body Butter', category: 'beauty-perfumes', type: 'PHYSICAL',
    price: 7500, seller: 'wellspring-wellness-co',
    material: 'Unrefined shea, cold-pressed coconut, vitamin E',
    dimensions: '250 g jar',
    colours: ['Unscented', 'Vanilla Bean', 'Lemongrass'],
    namedVariants: ['— 250 g', '— 500 g Twin Tub (₦13500)'],
    features: [
      'Whipped unrefined shea that melts on contact, not waxy',
      'No mineral oil, parabens or artificial dye',
      'Absorbs within minutes — no greasy film on clothes',
      'Made in small batches; best within 12 months',
    ],
  },
  {
    name: 'Roll-On Fragrance Oil', category: 'beauty-perfumes', type: 'PHYSICAL',
    price: 6500, seller: 'wellspring-wellness-co',
    material: 'Fractionated coconut base, fragrance blend',
    dimensions: '10 ml glass rollerball',
    colours: ['Oud & Amber', 'Jasmine & Sandalwood', 'Citrus Neroli', 'Vanilla Musk'],
    features: [
      'Alcohol-free oil wears closer to the skin and lasts all day',
      'Rollerball applies without spray bloom',
      'Pocket-sized steel cap survives handbags',
      'Layer two scents for a personal signature',
    ],
  },
  {
    name: 'Beard Conditioning Oil', category: 'beauty-perfumes', type: 'PHYSICAL',
    price: 5500, seller: 'wellspring-wellness-co',
    material: 'Jojoba, argan and castor oil blend',
    dimensions: '50 ml dropper bottle',
    colours: ['Cedar & Lime', 'Unscented'],
    features: [
      'Light oils soften without the heavy grease of petroleum bases',
      'Cedar & lime wears as a subtle scent through the day',
      'Dropper doses 3–5 drops properly — no glug',
      'Conditions skin underneath to fight flaking',
    ],
  },
  {
    name: 'Lip Balm Trio', category: 'beauty-perfumes', type: 'PHYSICAL',
    price: 4500, seller: 'wellspring-wellness-co',
    material: 'Shea, beeswax, vitamin E',
    dimensions: 'Three 4.5 g sticks',
    colours: ['Original', 'Cocoa', 'Peppermint'],
    features: [
      'Beeswax-locked moisture that survives harmattan air',
      'No tint, no flavour sweetness — just balm',
      'Twist mechanism that does not retract on application',
      'Trio covers bag, bedside and desk',
    ],
  },
  {
    name: 'Sugar Body Scrub', category: 'beauty-perfumes', type: 'PHYSICAL',
    price: 6500, seller: 'wellspring-wellness-co',
    material: 'Cane sugar, coconut oil, glycerin',
    dimensions: '300 g tub',
    colours: ['Coffee Coconut', 'Hibiscus Rose'],
    features: [
      'Fine-milled sugar polishes without microtears',
      'Oil-suspended formula rinses clean rather than slicking the shower floor',
      'Coffee variant smells like a café and feels like one too',
      'Stir before use — natural separation means no emulsifiers',
    ],
  },
  {
    name: 'Hair & Scalp Oil Blend', category: 'beauty-perfumes', type: 'PHYSICAL',
    price: 7000, seller: 'wellspring-wellness-co',
    material: 'Castor, coconut, rosemary and tea tree oils',
    dimensions: '100 ml applicator bottle',
    colours: ['Rosemary Blend', 'Tea Tree Blend'],
    features: [
      'Applicator nozzle parts braids and reaches the scalp directly',
      'Light enough to wash out on wash day without triple shampooing',
      'Rosemary and tea tree bring scent, not miracle claims',
      'Works as a pre-poo or a sealant on damp hair',
    ],
  },
  {
    name: 'Facial Steamer', category: 'beauty-perfumes', type: 'PHYSICAL',
    price: 19500, seller: 'wellspring-wellness-co',
    material: 'ABS body, stainless vaporizer plate',
    dimensions: 'Tank 180 ml; 10-minute sessions',
    colours: ['White', 'Mint'],
    features: [
      'Nano-scale mist feels warm and fine, not a kettle blast',
      'Auto shut-off when the tank empties',
      'Wide nozzle steams the whole face without leaning in',
      'Descale-safe plate wipes clean after each session',
    ],
  },
  {
    name: 'Vegan Makeup Brush Set', category: 'beauty-perfumes', type: 'PHYSICAL',
    price: 11500, seller: 'wellspring-wellness-co',
    material: 'Synthetic bristles, birch handles',
    dimensions: 'Ten brushes + zip case',
    colours: ['Rose Gold Ferrule', 'Black Ferrule'],
    features: [
      'Dense synthetic bristles pick up powder and cream without shedding',
      'Ten shapes cover base, powder, blush, contour, and four eye brushes',
      'Aluminium ferrules are double-crimped — heads do not wobble',
      'Zip case stands open on a dressing table',
    ],
    includes: ['Zip case', 'Brush cleaning cloth'],
  },
  {
    name: 'Eau de Parfum (50 ml)', category: 'beauty-perfumes', type: 'PHYSICAL',
    price: 24500, seller: 'wellspring-wellness-co',
    material: '15% parfum concentration in glass flacon',
    dimensions: '50 ml atomizer',
    colours: ['Nuit Blanche', 'Jardin Sauvage', 'Bois Doré'],
    namedVariants: ['— 50 ml', '— 30 ml Travel (₦16500)'],
    features: [
      '15% concentration reads as a true EDP, not a body mist',
      'Nuit Blanche opens bergamot into amber and cedar',
      'Atomizer produces a fine mist, not a squirt',
      'Weighted glass flacon with a magnetic cap',
    ],
  },
  {
    name: 'Manicure & Pedicure Kit', category: 'beauty-perfumes', type: 'PHYSICAL',
    price: 9500, seller: 'wellspring-wellness-co',
    material: 'Stainless tools in a leather-look case',
    dimensions: 'Twelve tools; case 16 × 10 cm',
    colours: ['Black Case', 'Tan Case'],
    features: [
      'Stainless clippers and nippers hold an edge and sharpen well',
      'Glass nail file files smoothly and outlasts emery boards',
      'Case elastic keeps every tool visible and in place',
      'Tools stay put in luggage',
    ],
    includes: ['12 tools', 'Zip case'],
  },
  {
    name: 'Cork Massage Ball Pair', category: 'health-wellness', type: 'PHYSICAL',
    price: 5500, seller: 'wellspring-wellness-co',
    material: 'Natural cork, two densities',
    dimensions: '8 cm firm + 6 cm medium',
    colours: ['Natural Cork'],
    features: [
      'Cork grips skin and fascia rather than sliding like rubber',
      'Two sizes target feet, shoulders and glutes differently',
      'Firmness tuned for release, not bruising',
      'Zero plastic — compostable at end of life',
    ],
  },
  {
    name: 'Collapsible Foam Roller (Travel)', category: 'health-wellness', type: 'PHYSICAL',
    price: 9500, seller: 'wellspring-wellness-co',
    material: 'Segmented EVA over plastic core',
    dimensions: 'Collapses to 22 cm; extends to 33 cm',
    colours: ['Slate', 'Sage'],
    features: [
      'Telescopes to full roller length then pockets into luggage',
      'Firmness close to a solid roller despite the hinge',
      'Doubles as a lumbar support on long flights',
      'Carry bag included',
    ],
  },

  // ═══ BRIGHTPATH DIGITAL ACADEMY — courses, ebooks, templates ══════════
  {
    name: 'Excel From Zero to Dashboards', category: 'digital-education', type: 'DIGITAL',
    price: 12500, seller: 'brightpath-digital-academy',
    format: '42 video lessons (MP4, 6.5 h) + 14 exercise workbooks (XLSX) + cheat sheets (PDF)',
    contents: [
      'Formulas and lookups built on realistic sales and payroll data',
      'Pivot tables, slicers and Power Query cleanups',
      'Building an interactive dashboard from raw CSV export',
      'Chart design: what to use and what to avoid',
    ],
    audience: 'Office professionals, analysts and small-business owners who live in spreadsheets',
    requirements: ['Excel 2016 or newer (or Excel for Microsoft 365)', 'A computer — the course is not phone-friendly'],
    outcome: 'Build and automate a working dashboard from messy data by the final module',
    namedVariants: ['— Standard', '— Standard + Live Q&A Recording (₦16500)'],
  },
  {
    name: 'Data Analysis with Python Bootcamp', category: 'digital-education', type: 'DIGITAL',
    price: 24900, seller: 'brightpath-digital-academy',
    format: '68 lessons (MP4, 11 h) + annotated Jupyter notebooks + 3 graded projects',
    contents: [
      'Python fundamentals taught through data cleaning, not toy puzzles',
      'pandas and matplotlib on real Nigerian retail and transport datasets',
      'SQL for analysts: joins, windows and query tuning',
      'Capstone: an end-to-end analysis presented as a written report',
    ],
    audience: 'Career switchers and Excel users moving into data roles',
    requirements: ['A laptop with 8 GB RAM', 'No prior programming experience needed'],
    outcome: 'Deliver a portfolio-grade analysis project with reproducible notebooks',
    namedVariants: ['— Self-Paced', '— Self-Paced + Project Reviews (₦34900)'],
  },
  {
    name: 'UI/UX Design Fundamentals', category: 'digital-education', type: 'DIGITAL',
    price: 19900, seller: 'brightpath-digital-academy',
    format: '54 lessons (MP4, 9 h) + Figma exercise files + critique templates',
    contents: [
      'Figma from first click: frames, components, auto-layout',
      'Type, spacing and colour systems that survive real content',
      'Wireframe → prototype → usability test on your own design',
      'Building a three-project portfolio case study',
    ],
    audience: 'Aspiring product designers and developers who want design literacy',
    requirements: ['A free Figma account', 'Chrome or Edge browser'],
    outcome: 'Ship a tested prototype and a written case study for your portfolio',
    namedVariants: ['— Self-Paced', '— With Portfolio Review (₦27900)'],
  },
  {
    name: 'Canva for Small Business', category: 'digital-education', type: 'DIGITAL',
    price: 8500, seller: 'brightpath-digital-academy',
    format: '24 lessons (MP4, 3.5 h) + 30 editable Canva templates',
    contents: [
      'Brand kit setup: fonts, colours and logo locks',
      'Instagram, flyer and WhatsApp-status designs that look intentional',
      'The duplication workflow that keeps a feed consistent',
      'Print basics: bleed, CMYK and working with a printer',
    ],
    audience: 'Bakery owners, boutique sellers and anyone marketing without a designer',
    requirements: ['A free Canva account'],
    outcome: 'A month of branded content designed and scheduled by yourself',
  },
  {
    name: 'Digital Marketing Foundations', category: 'digital-education', type: 'DIGITAL',
    price: 14900, seller: 'brightpath-digital-academy',
    format: '36 lessons (MP4, 5 h) + campaign planning workbook (PDF) + KPI tracker (XLSX)',
    contents: [
      'Choosing channels by budget: organic social, paid, email, SEO basics',
      'Writing ad copy against a single clear promise',
      'Meta and Google campaign structure without wasted spend',
      'Reading analytics to decide the next budget move',
    ],
    audience: 'Founders and marketing assistants running their first campaigns',
    requirements: ['A business or project to market — apply each module live'],
    outcome: 'A written, measurable campaign plan ready to launch',
  },
  {
    name: 'Freelancing 101: Land Your First Client', category: 'digital-education', type: 'DIGITAL',
    price: 11500, seller: 'brightpath-digital-academy',
    format: '28 lessons (MP4, 4 h) + proposal and contract templates (DOCX)',
    contents: [
      'Positioning: what to sell when you can do five things',
      'Pricing hourly vs value-based with real market examples',
      'Cold outreach and portfolio-free pitching',
      'Contracts, deposits and scope creep defence',
    ],
    audience: 'New freelancers in writing, design, dev and admin support',
    requirements: ['None — templates provided'],
    outcome: 'A priced offer, a proposal template and a 30-day outreach plan',
  },
  {
    name: 'Video Editing with CapCut & Premiere', category: 'digital-education', type: 'DIGITAL',
    price: 16900, seller: 'brightpath-digital-academy',
    format: '40 lessons (MP4, 6 h) + practice footage pack (8 GB download)',
    contents: [
      'Cutting, pacing and sound levels — the trio that fixes most videos',
      'Captions, hooks and platform-specific exports',
      'Colour correction fundamentals on any screen',
      'Delivering client work: formats, revisions and handoff',
    ],
    audience: 'Content creators and VAs adding editing as a service',
    requirements: ['CapCut (free) or Premiere Pro 2022+', '16 GB RAM recommended for Premiere'],
    outcome: 'Edit a 60-second promo and a 10-minute talking-head from raw footage',
  },
  {
    name: 'Full-Stack Web Development Track', category: 'digital-education', type: 'DIGITAL',
    price: 44900, seller: 'brightpath-digital-academy',
    format: '120+ lessons (MP4, 26 h) + 200-page handbook (PDF) + 5 projects with code reviews',
    contents: [
      'HTML/CSS/JS foundations through responsive layouts',
      'React components, state and data fetching',
      'Node/Express APIs with authentication and file uploads',
      'PostgreSQL data modelling and deployment walkthroughs',
    ],
    audience: 'Self-taught developers targeting junior full-stack roles',
    requirements: ['Comfortable using a computer', 'Commitment of 10+ hours weekly'],
    outcome: 'Five deployed projects and a GitHub profile that recruiters can read',
    namedVariants: ['— Self-Paced', '— With Mentorship (₦74900)'],
  },
  {
    name: 'Copywriting that Converts', category: 'digital-education', type: 'DIGITAL',
    price: 10500, seller: 'brightpath-digital-academy',
    format: '26 lessons (MP4, 3.8 h) + swipe file (PDF) + copy teardown sheets',
    contents: [
      'Voice-of-customer research: mining reviews and DMs for language',
      'Landing pages structured around one decision',
      'Email sequences for launch, nurture and winback',
      'Editing pass method: cutting 30% without losing meaning',
    ],
    audience: 'Marketers, founders and freelancers who write their own copy',
    requirements: ['None'],
    outcome: 'A rewritten landing page with before/after rationale',
  },
  {
    name: 'Personal Finance for Nigerians', category: 'digital-education', type: 'DIGITAL',
    price: 9500, seller: 'brightpath-digital-academy',
    format: '22 lessons (MP4, 3 h) + budgeting spreadsheet (XLSX/Sheets)',
    contents: [
      'Budgeting on irregular income without pretending it is monthly',
      'Nigerian savings instruments compared: MMF, treasury bills, fixed deposits',
      'Dollar diversification options and their actual costs',
      'Insurance basics: what matters and what is upsell',
    ],
    audience: 'Salaried professionals and freelancers organizing money for goals',
    requirements: ['None — spreadsheet works in Excel or Google Sheets'],
    outcome: 'A working budget and a written savings plan matched to real timelines',
  },
  {
    name: 'Product Management Foundations', category: 'digital-education', type: 'DIGITAL',
    price: 18900, seller: 'brightpath-digital-academy',
    format: '32 lessons (MP4, 5.5 h) + PRD and roadmap templates + interview prep pack',
    contents: [
      'Discovery interviews that avoid leading questions',
      'Writing PRDs engineers actually read',
      'Prioritization frameworks applied to one real backlog',
      'Working with design and engineering without becoming a ticket clerk',
    ],
    audience: 'Aspiring PMs and founders managing their first product team',
    requirements: ['A product idea or live product to practice on'],
    outcome: 'A researched PRD and a prioritized quarterly roadmap',
  },
  {
    name: 'Cybersecurity Essentials for Teams', category: 'digital-education', type: 'DIGITAL',
    price: 13900, seller: 'brightpath-digital-academy',
    format: '24 lessons (MP4, 4 h) + policy templates (DOCX) + incident checklist',
    contents: [
      'Password managers, MFA and access hygiene that sticks',
      'Phishing simulation planning without breeding paranoia',
      'Device policies for remote teams',
      'What to do in the first hour of an incident',
    ],
    audience: 'Office managers and team leads responsible for tooling',
    requirements: ['None'],
    outcome: 'A written security baseline and rollout plan for your team',
  },
  {
    name: 'CV & Interview Toolkit', category: 'digital-education', type: 'DIGITAL',
    price: 6500, seller: 'brightpath-digital-academy',
    format: '3 CV templates (DOCX + Google Docs) + 40-page interview guide (PDF) + tracker (XLSX)',
    contents: [
      'CV structures parsed correctly by ATS software',
      'Bullet rewriting: achievements over duties with worked examples',
      'STAR interview answers drilled against Nigerian employer examples',
      'Salary negotiation scripts and a red-flag checklist',
    ],
    audience: 'Job seekers across experience levels',
    requirements: ['Word or Google Docs'],
    outcome: 'A rewritten CV and rehearsed answers to the ten common questions',
    namedVariants: ['— Standard', '— Standard + Mock Interview Recording Review (₦10500)'],
  },
  {
    name: 'Business Plan & Pitch Deck Templates', category: 'digital-products', type: 'DIGITAL',
    price: 8500, seller: 'brightpath-digital-academy',
    format: 'Pitch deck (PPTX/Slides, 14 slides) + business plan (DOCX) + financial model (XLSX)',
    contents: [
      'Narrative-first deck structure investors expect',
      'Pre-filled financial model with Nigerian cost assumptions',
      'Editable charts wired to the model',
      'Written prompts guiding each section, not blank boxes',
    ],
    audience: 'Founders raising grants, loans or first-cheque investment',
    requirements: ['PowerPoint or Google Slides', 'Excel or Google Sheets'],
    outcome: 'An investor-ready deck and model within a working week',
  },
  {
    name: 'Social Media Content Calendar System', category: 'digital-products', type: 'DIGITAL',
    price: 5500, seller: 'brightpath-digital-academy',
    format: 'Notion + Sheets calendars + 90 hook prompts (PDF)',
    contents: [
      'Planning pipeline: idea bank → monthly themes → weekly posts',
      'Repurposing map turning one post into five',
      'Metrics tab that reviews what worked in ten minutes weekly',
      'Hook prompt bank with fill-in-the-blank starters',
    ],
    audience: 'Solo creators and small brands managing their own channels',
    requirements: ['Free Notion account or Google Sheets'],
    outcome: 'Three months of planned content in one afternoon of setup',
  },
  {
    name: 'Professional CV Template Pack', category: 'digital-products', type: 'DIGITAL',
    price: 3500, seller: 'brightpath-digital-academy',
    format: '6 templates (DOCX + Google Docs) + icon pack + writing guide (PDF)',
    contents: [
      'Six layouts from conservative to modern, all ATS-tested',
      'One-click recolouring to match your industry',
      'Line-by-line writing guide with weak/strong bullet examples',
      'Matching cover letter template in the same type system',
    ],
    audience: 'Professionals refreshing an application in one evening',
    requirements: ['Word 2013+ or Google Docs'],
    outcome: 'A finished CV with consistent typography and spacing',
    namedVariants: ['— Standard Pack (6)', '— Extended Pack (12) (₦5500)'],
  },
  {
    name: 'Lightroom Preset Collection', category: 'digital-products', type: 'DIGITAL',
    price: 6500, seller: 'brightpath-digital-academy',
    format: '30 presets (XMP + DNG) + installation video + skin-tone guide',
    contents: [
      '30 presets tuned for Nigerian skin tones and harsh daylight',
      'Versions for mobile (free Lightroom) and desktop',
      'Skin-tone protection so portraits never go orange or grey',
      'Before/after gallery for every preset',
    ],
    audience: 'Photographers and creators editing on phone or desktop',
    requirements: ['Lightroom Mobile (free) or Lightroom Classic'],
    outcome: 'Consistent, natural edits in two clicks per photo',
    namedVariants: ['— Portrait 30', '— Wedding & Events 45 (₦9500)'],
  },
  {
    name: 'Invoice & Receipt Template Pack', category: 'digital-products', type: 'DIGITAL',
    price: 3000, seller: 'brightpath-digital-academy',
    format: '8 templates (Word/Sheets/PDF) + auto-calculating invoice (Sheets)',
    contents: [
      'Auto-calculating invoice with VAT toggle and naira formatting',
      'Receipt, quotation and proforma variants',
      'Bank details block formatted for Nigerian transfers',
      'Numbering convention guide to keep records tidy',
    ],
    audience: 'Freelancers and small businesses invoicing properly',
    requirements: ['Word/Excel or Google Workspace'],
    outcome: 'Branded invoices issued in under two minutes each',
  },
  {
    name: 'Startup Pitch Deck Bundle', category: 'digital-products', type: 'DIGITAL',
    price: 12500, seller: 'brightpath-digital-academy',
    format: '4 full decks (PPTX/Slides) + 20 single-slide layouts + icon library',
    contents: [
      'Four narrative arcs: traction-led, vision-led, problem-led, demo-led',
      '20 polished single slides to cannibalize into your own deck',
      'Charts styled to stay legible when projected',
      'Written teardowns of why each example deck works',
    ],
    audience: 'Founders iterating on investor decks',
    requirements: ['PowerPoint or Google Slides'],
    outcome: 'A distinctive deck assembled from proven slide patterns',
  },
  {
    name: 'Ebook: Start Selling Online in 30 Days', category: 'digital-products', type: 'DIGITAL',
    price: 4500, seller: 'brightpath-digital-academy',
    format: 'Ebook (PDF + EPUB, 140 pages) + 30-day workbook (PDF)',
    contents: [
      'Choosing what to sell against honest market checks',
      'Product photography with a phone: the 6-setup cheat sheet',
      'Pricing pages and delivery options that close orders',
      'Customer service scripts for the usual objections',
    ],
    audience: 'First-time sellers starting with what they already have',
    requirements: ['Any PDF/EPUB reader'],
    outcome: 'A live listing and a 30-day launch checklist in motion',
  },
  {
    name: 'Digital Study Planner (Undated)', category: 'digital-products', type: 'DIGITAL',
    price: 2500, seller: 'brightpath-digital-academy',
    format: 'GoodNotes + Notability planner (280 pages) + printable A5 PDF',
    contents: [
      'Undated daily, weekly and semester views — start any time',
      'Linked tabs for courses, assignments and revision tracking',
      'Exam countdown dashboard with a spaced-repetition log',
      'Hyperlinked from the index to every section',
    ],
    audience: 'University students and self-study candidates',
    requirements: ['Tablet with GoodNotes/Notability, or a printer for the A5 PDF'],
    outcome: 'One planner holding every course deadline and revision loop',
    namedVariants: ['— Dark Theme', '— Light Theme', '— Duo (both themes) (₦4000)'],
  },
  {
    name: 'Monthly Budget Spreadsheet', category: 'digital-products', type: 'DIGITAL',
    price: 3000, seller: 'brightpath-digital-academy',
    format: 'Excel + Google Sheets versions + setup video (15 min)',
    contents: [
      'Weekly bucket budgeting rather than 30 identical rows',
      'Auto-rolling dashboard of spend vs plan by category',
      'Sinking funds tab for rent, school fees and lumpy bills',
      'Naira-formatted inputs with kobo-safe rounding',
    ],
    audience: 'Anyone who has abandoned an overcomplicated budget app',
    requirements: ['Excel 2016+ or free Google Sheets'],
    outcome: 'A budget you will still be using next quarter',
  },
  {
    name: 'Brand Guidelines Template', category: 'digital-products', type: 'DIGITAL',
    price: 7500, seller: 'brightpath-digital-academy',
    format: '24-page InDesign + Canva + PDF template pack',
    contents: [
      'Logo usage rules with clear-space and misuse examples',
      'Colour, type and imagery systems with real sample pages',
      'Voice and tone section with do/don\'t copy pairs',
      'Export-ready for sending to printers and partners',
    ],
    audience: 'Designers delivering brand systems and founders documenting one',
    requirements: ['InDesign (optional) or free Canva account'],
    outcome: 'A complete brand book a supplier can work from without you on the call',
  },
  {
    name: 'Notion Second Brain OS', category: 'digital-products', type: 'DIGITAL',
    price: 6500, seller: 'brightpath-digital-academy',
    format: 'Notion template (14 linked databases) + video walkthrough (35 min)',
    contents: [
      'Inbox → projects → areas pipeline adapted for real workloads',
      'Linked task and note databases that never duplicate entries',
      'Weekly review dashboard with a ten-minute checklist',
      'Mobile capture flow that survives being busy',
    ],
    audience: 'Knowledge workers juggling projects, side hustles and study',
    requirements: ['Free Notion account'],
    outcome: 'A single trusted system after one setup evening',
  },
];
