// ============================================================
// KOVA — Wave-4 catalog families (DEMO DATA ONLY)
// Closes the remaining per-seller gap to the 200-product floor
// with variant-rich, genuinely distinct product families.
// Digital families use edition/licence variants (how digital
// sellers really segment); physical use real material/size/
// capacity variants.
// ============================================================

import type { SeedItem } from './seed-data';

export const WAVE4_ITEMS: SeedItem[] = [
  // ═══ BRIGHTPATH DIGITAL ACADEMY (+81 needed) ═══════════
  { name: 'Virtual Assistant Career Course', category: 'digital-education', type: 'DIGITAL', price: 11900, seller: 'brightpath-digital-academy',
    format: '26 lessons (MP4, 4 h) + tools mastery checklists + client onboarding templates',
    contents: ['Core VA services and pricing them for the Nigerian market', 'Calendar, email and travel management workflows', 'Tool fluency: Notion, Trello, Calendly, Canva', 'Finding and keeping retainer clients'],
    audience: 'Admin professionals and students starting a VA business',
    requirements: ['A laptop and reliable internet'],
    outcome: 'A service menu, rates and a client-ready workflow',
    namedVariants: ['— Self-Paced', '— With Niche Positioning Workshop (₦15900)', '— Team Training 3 Seats (₦29900)', '— With Client Finder Playbook (₦18900)', '— Cohort Edition with Live Clinics (₦24900)'] },
  { name: 'Graphic Design with Photoshop Essentials', category: 'digital-education', type: 'DIGITAL', price: 16900, seller: 'brightpath-digital-academy',
    format: '34 lessons (MP4, 5 h) + 25 exercise files + asset pack (PSD)',
    contents: ['Layers, masks and selections — the trinity done properly', 'Retouching portraits without plastic skin', 'Print vs screen: resolution, colour and bleed basics', 'Speed workflow: actions and templates for client work'],
    audience: 'Beginners targeting freelance design or in-house roles',
    requirements: ['Photoshop CC 2020+ (trial works)'],
    outcome: 'A five-piece portfolio of real-world design exercises',
    namedVariants: ['— Self-Paced', '— With Illustrator Module (₦22900)', '— With Portfolio Review (₦24900)', '— Classroom Licence 10 Seats (₦89900)'] },
  { name: 'Bookkeeping with QuickBooks', category: 'digital-education', type: 'DIGITAL', price: 15900, seller: 'brightpath-digital-academy',
    format: '30 lessons (MP4, 4.2 h) + chart of accounts template + practice company file',
    contents: ['Setting up a Nigerian small-business file properly', 'Invoices, bills and bank feeds without duplication', 'Payroll basics and statutory remittance tracking', 'Month-end close checklist and reports that matter'],
    audience: 'Bookkeepers, accountants and SME finance staff',
    requirements: ['QuickBooks Online (trial works)'],
    outcome: 'A maintained practice file and a clean monthly close routine',
    namedVariants: ['— Self-Paced', '— With Sage Module (₦21900)', '— With Exam Prep for Certification (₦24900)'] },
  { name: 'Content Writing Mastery', category: 'digital-education', type: 'DIGITAL', price: 10900, seller: 'brightpath-digital-academy',
    format: '24 lessons (MP4, 3.5 h) + 40 writing prompts + editing checklists',
    contents: ['Research systems for writing about anything credibly', 'Blog, web and social formats with distinct structures', 'SEO writing that reads like a human wrote it', 'Building a client-ready writing portfolio'],
    audience: 'Writers turning English skills into income',
    requirements: ['None'],
    outcome: 'Ten published pieces and a pitching system',
    namedVariants: ['— Self-Paced', '— With SEO Writing Module (₦14900)', '— With Client Acquisition System (₦17900)', '— Team Licence 5 Seats (₦44900)'] },
  { name: 'Microsoft Office Complete Suite Training', category: 'digital-education', type: 'DIGITAL', price: 13900, seller: 'brightpath-digital-academy',
    format: '72 lessons (MP4, 9 h across Word, Excel, PowerPoint, Outlook) + exercise files',
    contents: ['Word: styles, templates and long-document control', 'Excel: formulas, tables and charts for the office', 'PowerPoint: decks that inform instead of sedate', 'Outlook: inbox systems and calendar discipline'],
    audience: 'Administrative staff, students and job seekers',
    requirements: ['Office 2016+ or Microsoft 365'],
    outcome: 'Workplace-level fluency across the four core apps',
    namedVariants: ['— Full Suite', '— Excel Only Deep Dive (₦8500)', '— Word + PowerPoint (₦8900)', '— With MOS Exam Practice (₦19900)'] },
  { name: 'Amazon KDP Self-Publishing Course', category: 'digital-education', type: 'DIGITAL', price: 13500, seller: 'brightpath-digital-academy',
    format: '22 lessons (MP4, 3.2 h) + cover templates + keyword research sheet',
    contents: ['Choosing profitable non-fiction niches honestly', 'Formatting interiors for paperback and Kindle', 'Covers that convert at thumbnail size', 'Launch pricing and the first ten reviews'],
    audience: 'Writers and educators publishing their first book',
    requirements: ['A manuscript idea (guide helps you shape it)'],
    outcome: 'A published paperback and ebook listing on Amazon',
    namedVariants: ['— Self-Paced', '— With Niche Research Session (₦19900)', '— With Low-Content Book Pack (₦16900)'] },
  { name: '3D Modeling with Blender Basics', category: 'digital-education', type: 'DIGITAL', price: 17900, seller: 'brightpath-digital-academy',
    format: '30 lessons (MP4, 5.5 h) + project files + render settings pack',
    contents: ['Navigation, modelling and modifiers for real objects', 'Materials and lighting that flatter product renders', 'Rendering stills and turntables for e-commerce', 'Exporting usable assets for clients'],
    audience: 'Designers and product sellers adding 3D visuals',
    requirements: ['Blender (free) and 8 GB RAM'],
    outcome: 'Three rendered product scenes for a portfolio',
    namedVariants: ['— Self-Paced', '— With Product Visualization Focus (₦22900)', '— With Animation Module (₦25900)'] },
  { name: 'Instagram Growth for Brands', category: 'digital-education', type: 'DIGITAL', price: 8900, seller: 'brightpath-digital-academy',
    format: '20 lessons (MP4, 2.6 h) + 90 content prompts + audit worksheet',
    contents: ['Positioning a business page people remember', 'Reels, carousels and stories — what each is for', 'Hashtag and caption systems that compound', 'Turning followers into WhatsApp and DM buyers'],
    audience: 'Boutique owners, food brands and service providers',
    requirements: ['An Instagram business account'],
    outcome: 'A 30-day content plan and a profile that sells',
    namedVariants: ['— Self-Paced', '— With Content Shoot Guide (₦12900)', '— With Reels Editing Module (₦14900)'] },
  { name: 'Customer Service Excellence Training', category: 'digital-education', type: 'DIGITAL', price: 9900, seller: 'brightpath-digital-academy',
    format: '18 lessons (MP4, 2.4 h) + 30 response scripts + escalation flowchart',
    contents: ['Tone that de-escalates angry customers in writing', 'Response templates for orders, refunds and delays', 'Live chat and phone manner fundamentals', 'Turning complaints into retained customers'],
    audience: 'Support teams and business owners handling customers directly',
    requirements: ['None'],
    outcome: 'A scripted, consistent customer experience across channels',
    namedVariants: ['— Individual', '— Team Pack 5 Seats (₦39900)', '— Team Pack 10 Seats (₦69900)'] },
  { name: 'Project Management with Trello & Asana', category: 'digital-education', type: 'DIGITAL', price: 9500, seller: 'brightpath-digital-academy',
    format: '20 lessons (MP4, 2.8 h) + board templates + SOP pack',
    contents: ['Boards built around outcomes, not noise', 'Automation rules that remove busywork', 'Client-facing vs internal boards', 'Sprint-style weekly reviews that keep projects moving'],
    audience: 'Team leads, VAs and founders coordinating work',
    requirements: ['Free Trello and Asana accounts'],
    outcome: 'A working project system your team actually updates',
    namedVariants: ['— Self-Paced', '— With Agency Ops Templates (₦14900)'] },

  // Brightpath — template/product wave (digital-products)
  { name: 'Webinar Slide & Registration Kit', category: 'digital-products', type: 'DIGITAL', price: 6500, seller: 'brightpath-digital-academy',
    format: 'Slide deck template (PPTX/Slides) + registration page copy + reminder email sequence',
    contents: ['Teaching-first slide structure that holds attention', 'Registration page copy skeleton that converts', 'Four-email reminder sequence pre-written', 'Post-webinar follow-up offer email'],
    audience: 'Experts hosting their first paid webinar',
    requirements: ['PowerPoint or Google Slides'],
    outcome: 'A complete webinar kit from promotion to follow-up',
    namedVariants: ['— Standard Kit', '— With Replay Funnel Emails (₦9500)', '— Corporate Training Edition (₦14500)'] },
  { name: 'Course Workbook & Worksheet Templates', category: 'digital-products', type: 'DIGITAL', price: 4500, seller: 'brightpath-digital-academy',
    format: '15 worksheet layouts (DOCX/PDF/Canva) + workbook cover set',
    contents: ['Fill-in worksheets matched to lesson outcomes', 'Canva-editable versions for branding', 'Printable PDF and screen-fillable formats', 'Workbook cover and interior page designs'],
    audience: 'Course creators adding workbooks to their programmes',
    requirements: ['Word or free Canva account'],
    outcome: 'A branded student workbook in one afternoon',
    namedVariants: ['— Core 15', '— Extended 30 (₦7500)', '— With Editable Canva Mastery Guide (₦9500)'] },
  { name: 'Church & Ministry Media Pack', category: 'digital-products', type: 'DIGITAL', price: 5500, seller: 'brightpath-digital-academy',
    format: 'Flyer, sermon slide and social templates (Canva/PPTX) + announcement scripts',
    contents: ['Sunday flyer and programme templates', 'Sermon slide master with scripture typography', 'Instagram and WhatsApp announcement designs', 'Event promotion timeline script'],
    audience: 'Church media teams and ministry communicators',
    requirements: ['Free Canva account'],
    outcome: 'A consistent media presence for services and events',
    namedVariants: ['— Standard Pack', '— With Youth Event Pack (₦8500)', '— Choir & Concert Edition (₦8500)'] },
  { name: 'School Administrator Toolkit', category: 'digital-products', type: 'DIGITAL', price: 8500, seller: 'brightpath-digital-academy',
    format: 'Fee tracker + attendance register + result sheet + PTA minutes templates (XLSX/DOCX)',
    contents: ['Fee payment ledger with defaulter flags', 'Attendance register across terms and arms', 'Result computation sheet with positions', 'PTA meeting minutes and circular templates'],
    audience: 'Private school administrators and proprietors',
    requirements: ['Excel or Google Sheets'],
    outcome: 'Paperwork under control from enrollment to results day',
    namedVariants: ['— Single School', '— Multi-Campus Edition (₦14500)'] },
  { name: 'Real Estate Flyer & Listing Templates', category: 'digital-products', type: 'DIGITAL', price: 5500, seller: 'brightpath-digital-academy',
    format: '12 Canva flyer templates + signage sizes + WhatsApp broadcast designs',
    contents: ['Flyer layouts for land and house listings', 'Print signage with correct bleed sizes', 'WhatsApp and Instagram story sizes', 'Agent contact and QR code placement guide'],
    audience: 'Property marketers and agencies',
    requirements: ['Free Canva account'],
    outcome: 'Listing collateral that looks agency-grade',
    namedVariants: ['— Standard 12', '— Luxury Segment Pack (₦8500)'] },
  { name: 'Fashion Boutique Branding Kit', category: 'digital-products', type: 'DIGITAL', price: 7500, seller: 'brightpath-digital-academy',
    format: 'Logo templates (Canva) + price tag designs + packaging inserts + brand board',
    contents: ['Logo system editable in Canva — no designer needed', 'Price tag and care card print designs', 'Thank-you insert that drives repeat orders', 'Brand board to keep visuals consistent'],
    audience: 'Boutique owners building a recognisable brand',
    requirements: ['Free Canva account'],
    outcome: 'Cohesive branding from tag to Instagram grid',
    namedVariants: ['— Standard Kit', '— With Packaging Sticker Set (₦10500)'] },
  { name: 'Food Vendor Recipe Costing Cards', category: 'digital-products', type: 'DIGITAL', price: 4500, seller: 'brightpath-digital-academy',
    format: 'Costing cards (XLSX/PDF) + portion guide + margin calculator',
    contents: ['Per-plate costing down to the seasoning cube', 'Portion control guide against shrinkage', 'Margin calculator with market price swings', 'Menu pricing tiers (dine-in vs delivery)'],
    audience: 'Caterers and food vendors protecting profit',
    requirements: ['Excel or Google Sheets'],
    outcome: 'Priced menu with known margins per plate',
    namedVariants: ['— Core Cards', '— With Weekly Market Price Tracker (₦7500)'] },
  { name: 'Fitness Coach Client Program Templates', category: 'digital-products', type: 'DIGITAL', price: 6500, seller: 'brightpath-digital-academy',
    format: 'Program templates (PDF/DOCX) + intake form + progress tracker + nutrition guide skeleton',
    contents: ['Beginner, intermediate and home-program templates', 'Client intake with PAR-Q style screening', 'Progress photos and measurement tracker', 'Editable nutrition guidance framework'],
    audience: 'Personal trainers professionalising client delivery',
    requirements: ['Word/Excel or PDF editor'],
    outcome: 'A polished client experience from intake to results',
    namedVariants: ['— Standard Pack', '— With Group Program Templates (₦9500)'] },
  { name: 'DJ & Event Promo Pack', category: 'digital-products', type: 'DIGITAL', price: 5500, seller: 'brightpath-digital-academy',
    format: 'Flyer and ticket designs (Canva/PPTX) + countdown story templates + rate card template',
    contents: ['Event flyer layouts in three styles', 'Ticket and table-booking designs', 'Instagram countdown story set', 'Rate card to send enquiries without haggling'],
    audience: 'DJs, MCs and event promoters',
    requirements: ['Free Canva account'],
    outcome: 'Promo materials ready for the next show',
    namedVariants: ['— Standard Pack', '— Detty December Edition (₦8500)'] },
  { name: 'Barbing Salon Price List & Booking Templates', category: 'digital-products', type: 'DIGITAL', price: 3500, seller: 'brightpath-digital-academy',
    format: 'Price list designs (Canva) + appointment card + loyalty card templates',
    contents: ['Price list layouts for print and WhatsApp', 'Appointment reminder card designs', 'Loyalty punch card to fill by the tenth cut', 'Service menu wording that upsells cleanly'],
    audience: 'Salon and barbing studio owners',
    requirements: ['Free Canva account'],
    outcome: 'Professional front-of-house materials in one evening',
    namedVariants: ['— Standard', '— With Staff Commission Tracker (₦6500)'] },
  { name: 'Airbnb Host Welcome Book Templates', category: 'digital-products', type: 'DIGITAL', price: 5500, seller: 'brightpath-digital-academy',
    format: 'Welcome book (Canva/PDF) + house rules card + review request message pack',
    contents: ['Welcome book covering check-in, amenities and area guide', 'House rules one-pager guests actually read', 'Checkout instructions card', 'Five-star review request message timing guide'],
    audience: 'Short-let hosts standardising guest experience',
    requirements: ['Free Canva account'],
    outcome: 'Fewer guest questions and better reviews from the next booking',
    namedVariants: ['— Standard Book', '— With Self Check-in Signage Set (₦8500)'] },
  { name: 'Tutorial Centre Enrollment Kit', category: 'digital-products', type: 'DIGITAL', price: 4500, seller: 'brightpath-digital-academy',
    format: 'Flyer templates + enrollment form + fee structure sheet + parent letter',
    contents: ['Session flyers for WAEC, JAMB and lesson classes', 'Enrollment form capturing what matters', 'Fee structure sheet with sibling discounts', 'Parent communication letter templates'],
    audience: 'Lesson teachers and tutorial centres',
    requirements: ['Word/Excel or Canva'],
    outcome: 'Enrollment collateral ready before the session starts',
    namedVariants: ['— Standard Kit', '— With Online Class Setup Guide (₦7500)'] },

  // ═══ ALABI TECHHUB (+32 needed) ════════════════════════
  { name: 'Graphics Tablet (Drawing Pad)', category: 'electronics', type: 'PHYSICAL', price: 36500, seller: 'alabi-techhub',
    material: 'Textured surface, battery-free pen', dimensions: 'Active area 6 × 4 in (also 8 × 5)',
    colours: ['Black'],
    namedVariants: ['— 6×4", 8192 levels', '— 8×5" Pro (₦48500)', '— With Stand and Glove (₦54500)'],
    features: ['Battery-free pen charges nothing and never dies mid-stroke', '8192 pressure levels for natural line weight', 'Works with Windows, macOS and Android phones', 'Express keys programmable per app'],
    includes: ['Pen nibs ×10', 'Two-finger glove', 'Quick guide'] },
  { name: 'Conference Speakerphone', category: 'electronics', type: 'PHYSICAL', price: 42900, seller: 'alabi-techhub',
    material: 'Fabric-wrapped 360° mic array', dimensions: 'Ø 12 cm; picks voices to 5 m',
    colours: ['Black'],
    namedVariants: ['— Standard', '— Daisy-Chain Pair for Boardrooms (₦78900)'],
    features: ['Six microphones beamform to the active speaker', 'Full-duplex audio — no cutting each other off', 'USB and Bluetooth to any meeting laptop', '18-hour call battery on one charge'],
    includes: ['USB-C cable', 'Travel case'] },
  { name: 'Laptop Docking Station (Dual HDMI)', category: 'electronics', type: 'PHYSICAL', price: 58500, seller: 'alabi-techhub',
    material: 'Aluminium chassis', dimensions: 'Dual 4K HDMI, 100 W PD, Gigabit, 3× USB',
    colours: ['Space Grey'],
    namedVariants: ['— Dual HDMI', '— Triple Display HDMI+DP (₦68500)'],
    features: ['Turns one USB-C into a full desk: two 4K screens, network, peripherals', '100 W pass-through charges the laptop while docked', 'Gigabit Ethernet for stable hybrid meetings', 'SD/microSD readers for camera offloads'],
    includes: ['Power adapter', 'USB-C host cable'] },
  { name: 'Smart Door Lock', category: 'electronics', type: 'PHYSICAL', price: 78500, seller: 'alabi-techhub',
    material: 'Zinc alloy body, IP65 weather seal', dimensions: 'Fits standard 38–55 mm doors',
    colours: ['Black', 'Silver'],
    features: ['Fingerprint, PIN, app and mechanical key — four ways in', 'Guest codes expire on schedule for short-let hosts', 'Auto-locks behind you after a set delay', 'Low-battery warnings weeks ahead, USB-C emergency port'],
    includes: ['Lock cylinder set', 'Drilling template', 'Mechanical keys ×2'] },
  { name: 'Digital Photo Frame (Cloud)', category: 'electronics', type: 'PHYSICAL', price: 32500, seller: 'alabi-techhub',
    material: 'IPS panel, wood-look frame', dimensions: '10.1" touch screen',
    colours: ['Walnut Look', 'Black'],
    namedVariants: ['— 10.1"', '— 13.3" Wall Mount (₦48500)'],
    features: ['Family sends photos from anywhere through the app', 'IPS panel reads well from any angle in the lounge', 'Motion sensor sleeps when the room is empty', 'Plays short video clips too'],
    includes: ['Stand', 'Wall mount kit'] },
  { name: 'Robot Vacuum Cleaner', category: 'electronics', type: 'PHYSICAL', price: 96500, seller: 'alabi-techhub',
    material: 'Impact bumper, cliff sensors', dimensions: 'Ø 32 cm; auto-dock recharge',
    colours: ['Black'],
    namedVariants: ['— Standard Suction', '— With Mop Module (₦118000)'],
    features: ['Gyro mapping cleans in rows instead of drunk spirals', 'Auto-docks and resumes after charging', 'App schedules around NEPA and prayer times', 'Cliff sensors refuse stairs and balcony edges'],
    includes: ['Side brushes ×2', 'HEPA filter ×2', 'Cleaning tool'] },
  { name: 'Portable Monitor 15.6" USB-C', category: 'electronics', type: 'PHYSICAL', price: 68500, seller: 'alabi-techhub',
    material: 'IPS panel, magnetic smart cover', dimensions: '15.6" FHD; 700 g; single USB-C',
    colours: ['Space Grey'],
    namedVariants: ['— FHD 60 Hz', '— 2K 120 Hz (₦96500)'],
    features: ['Second screen from a laptop or phone over one USB-C cable', 'Cover folds into a stand with three angles', 'Works with consoles and mini PCs too', 'Speakers and headphone jack built in'],
    includes: ['USB-C cables ×2', 'Smart cover'] },
  { name: 'Smart Body Composition Scale', category: 'electronics', type: 'PHYSICAL', price: 16500, seller: 'alabi-techhub',
    material: 'Tempered glass, BIA sensors', dimensions: '13 metrics; 180 kg max; app sync',
    colours: ['Black', 'White'],
    features: ['Thirteen metrics beyond weight: fat, muscle, water, bone', 'Unlimited profiles on the family app', 'Bluetooth sync charts trends honestly over months', 'Large tempered-glass platform'],
  },
  { name: 'Wireless Doorbell Camera', category: 'electronics', type: 'PHYSICAL', price: 44500, seller: 'alabi-techhub',
    material: 'IP65 housing, rechargeable pack', dimensions: '2K HDR camera; chime included',
    colours: ['Black'],
    features: ['See and speak to the gate before opening it', '2K HDR reads faces against Nigerian afternoon glare', 'Rechargeable pack lasts months per charge', 'Motion zones ignore the street, watch the door'],
    includes: ['Indoor chime', 'Mounting kit', 'USB charger'] },
  { name: 'CCTV Security Camera System (4-Channel)', category: 'electronics', type: 'PHYSICAL', price: 128000, seller: 'alabi-techhub',
    material: 'Metal IP67 cameras, 1 TB NVR', dimensions: '4 × 2K cameras + NVR kit',
    colours: ['White'],
    namedVariants: ['— 4-Channel 1 TB', '— 8-Channel 2 TB (₦188000)'],
    features: ['Night vision that actually shows a face, not a shadow', 'Motion alerts to the phone with clip playback', '1 TB storage loops about four weeks of footage', 'Wired reliability where Wi-Fi cameras drop'],
    includes: ['NVR', '4 cameras', '60 m cabling', 'Power supplies', 'Mouse'] },
  { name: 'Fast Charge Power Strip Tower', category: 'electronics', type: 'PHYSICAL', price: 18900, seller: 'alabi-techhub',
    material: 'Flame-retardant tower, 1.8 m cord', dimensions: '8 sockets + 4 USB; 2-layer',
    colours: ['White', 'Black'],
    features: ['Vertical tower feeds the whole desk or TV unit from one socket', 'Surge protection for the expensive things plugged in', 'Two-layer control switches sections independently', 'Cable handles on top keep cords organised'] },

  // ═══ ZURI HOME LIVING (+34 needed) ═════════════════════
  { name: 'Recliner Armchair', category: 'furniture', type: 'PHYSICAL', price: 118000, seller: 'zuri-home-living',
    material: 'Microfiber upholstery, steel recline frame', dimensions: 'W 84 cm; reclines to 160°',
    colours: ['Chocolate', 'Grey', 'Black'],
    namedVariants: ['— Manual Recline', '— Power Recline with USB (₦148000)'],
    features: ['Smooth manual recline with a leg-rest that locks where you leave it', 'Padded lumbar and headrest for long matches', 'Stain-resistant microfiber wipes clean', 'Side pocket for remotes and the current novel'],
    leadTime: 'Made to order — dispatches in 7–10 working days.' },
  { name: 'Dining Table Set (6-Seater)', category: 'furniture', type: 'PHYSICAL', price: 245000, seller: 'zuri-home-living',
    material: 'Tempered glass top, powder-coated frame', dimensions: 'Table 160 × 90 cm; 6 chairs',
    colours: ['Black Frame/Clear', 'Walnut/Bronze'],
    namedVariants: ['— 6-Seater', '— 4-Seater Compact (₦185000)', '— 8-Seater Extendable (₦298000)'],
    features: ['Tempered glass seats a family without visual bulk', 'Chairs stack for quick sweeping under the table', 'Adjustable feet tame compound floors', 'Glass cleans of jollof fingerprints in one wipe'],
    leadTime: 'Made to order — dispatches in 10–14 working days.' },
  { name: 'Wardrobe with Mirror (3-Door)', category: 'furniture', type: 'PHYSICAL', price: 165000, seller: 'zuri-home-living',
    material: 'Engineered wood, hanging rail + shelves', dimensions: 'H 200 × W 135 cm; full-length mirror',
    colours: ['Walnut Look', 'White', 'Grey'],
    namedVariants: ['— 3-Door with Mirror', '— 2-Door Compact (₦128000)', '— Sliding Door 4-Drawer (₦198000)'],
    features: ['Hanging rail plus six shelves plus a drawer — real capacity', 'Full-length mirror on the door saves wall space', 'Soft-close hinges on the mirrored door', 'Anti-tip wall strap included'],
    leadTime: 'Made to order — dispatches in 7–10 working days.' },
  { name: 'Kitchen Island Trolley', category: 'furniture', type: 'PHYSICAL', price: 68500, seller: 'zuri-home-living',
    material: 'Rubberwood top, steel frame', dimensions: '85 × 50 × 90 cm; lockable casters',
    colours: ['Natural/Black', 'White/Wood'],
    features: ['Rolls prep space to wherever the cooking happens', 'Two drawers plus a two-tier rack for pots', 'Lockable casters stop mid-chop drift', 'Towel rail and knife block slots included'] },
  { name: 'Shoe Cabinet (5-Tier)', category: 'furniture', type: 'PHYSICAL', price: 48500, seller: 'zuri-home-living',
    material: 'Engineered wood, adjustable shelves', dimensions: 'Holds ~20 pairs; H 110 × W 60 cm',
    colours: ['White', 'Oak Look', 'Grey'],
    namedVariants: ['— 5-Tier', '— 7-Tier Tall (₦58500)', '— 3-Tier Entry (₦34500)'],
    features: ['Adjustable tiers swallow heels, trainers and children\'s sizes', 'Back panel vent slots keep smells honest', 'Top surface catches keys on the way in', 'Anti-tip strap included for family hallways'] },
  { name: 'Ceramic Dinner Plates (Set of 6)', category: 'interior-home', type: 'PHYSICAL', price: 19500, seller: 'zuri-home-living',
    material: 'Reactive-glaze stoneware', dimensions: 'Ø 27 cm; stack-safe rim',
    colours: ['Matte Sand', 'Slate Blue', 'Olive'],
    namedVariants: ['— Set of 6', '— Set of 12 (₦36500)', '— With Side Plates Bundle (₦29500)'],
    features: ['Matching family to the Ceramic Dinner Set for top-ups', 'Chip-resistant rim survives daily stacking', 'Dishwasher and microwave safe', 'Reactive glaze means each plate pools slightly differently'] },
  { name: 'Glass Storage Jars with Bamboo Lids (Set of 4)', category: 'interior-home', type: 'PHYSICAL', price: 12500, seller: 'zuri-home-living',
    material: 'Borosilicate glass, bamboo lid with gasket', dimensions: '1 L each (mixed set available)',
    colours: ['Clear/Bamboo'],
    namedVariants: ['— 4 × 1 L', '— Mixed Set 4 sizes (₦14500)', '— 6-Piece Pantry Set (₦18500)'],
    features: ['Borosilicate handles hot decantsing without cracking', 'Silicone-gasketed bamboo lids keep contents crisp', 'Square bases pack pantry shelves tightly', 'Wide mouths fit measuring cups directly'] },
  { name: 'Faux Fur Throw Blanket', category: 'interior-home', type: 'PHYSICAL', price: 15500, seller: 'zuri-home-living',
    material: 'Faux fur front, sherpa reverse', dimensions: '130 × 170 cm',
    colours: ['Cream', 'Charcoal', 'Blush'],
    namedVariants: ['— Standard', '— Oversized 180×200 (₦22500)'],
    features: ['Double-sided warmth: fur face, sherpa reverse', 'Sheds minimally after the first shake-out', 'Machine washable on gentle — survives real homes', 'Weighted drape stays on sleeping viewers'] },
  { name: 'LED Vanity Strip Mirror Lights', category: 'interior-home', type: 'PHYSICAL', price: 8500, seller: 'zuri-home-living',
    material: 'Flexible LED strip, touch dimmer', dimensions: '3 m cuttable strip; USB powered',
    colours: ['White Strip'],
    features: ['Hollywood-style lighting around any existing mirror', 'Touch dimmer from make-up bright to evening warm', 'Adhesive backing mounts without drilling', 'USB powered from the nearest adapter'] },
  { name: 'Bathroom Storage Ladder Shelf', category: 'interior-home', type: 'PHYSICAL', price: 28500, seller: 'zuri-home-living',
    material: 'Bamboo, moisture-sealed finish', dimensions: 'H 145 cm; 4 tiers; leans to wall',
    colours: ['Natural Bamboo'],
    features: ['Four tiers of towels and toiletries in slim bathrooms', 'Moisture-sealed bamboo tolerates steamy rooms', 'Anti-slip feet grip wet tiles', 'Assembles in fifteen minutes'] },
  { name: 'Decorative Wall Clock (Silent Sweep)', category: 'interior-home', type: 'PHYSICAL', price: 9500, seller: 'zuri-home-living',
    material: 'Metal frame, glass lens', dimensions: 'Ø 35 cm; AA powered',
    colours: ['Gold Frame/White', 'Black Frame/Charcoal', 'Rose Gold/Blush'],
    features: ['Silent sweep movement for bedrooms and studies', 'Metal frame reads more expensive than it costs', 'Glass lens wipes clean of kitchen film', 'Wide hanger mounts on a single nail'] },
  { name: 'Tabletop Water Dispenser', category: 'interior-home', type: 'PHYSICAL', price: 22500, seller: 'zuri-home-living',
    material: 'Food-grade PP body', dimensions: 'Fits 19 L bottles; hot and cold taps',
    colours: ['White', 'Black'],
    namedVariants: ['— Hot & Cold', '— Ambient Only (₦16500)'],
    features: ['Sits on the counter and feeds the whole floor from one bottle', 'Child-safety latch on the hot tap', 'Cold tank chills without compressor noise', 'Drip tray lifts out for washing'] },

  // ═══ WELLSPRING (+46 needed) ═══════════════════════════
  { name: 'Complete Home Gym Kit', category: 'health-wellness', type: 'PHYSICAL', price: 68500, seller: 'wellspring-wellness-co',
    material: 'Mixed: bands, dumbbells, mat, roller, rope', dimensions: 'Everything fits the included storage bag',
    colours: ['Sage Kit', 'Charcoal Kit'],
    namedVariants: ['— Starter Kit (9 pieces)', '— Advanced Kit with 2×5 kg + Bench Bands (₦98500)'],
    features: ['A full-body gym that lives under the bed', 'Bands, dumbbells, mat, roller and rope in one buy', 'Printed four-week starter programme included', 'Saves the annual gym registration you never use'],
    includes: ['Storage bag', 'Programme booklet'] },
  { name: 'Foldable Treadmill (Walking Pad)', category: 'health-wellness', type: 'PHYSICAL', price: 148000, seller: 'wellspring-wellness-co',
    material: 'Aluminium deck, shock-absorbing belt', dimensions: 'Folds to 15 cm; 1–8 km/h; 100 kg max',
    colours: ['Grey'],
    namedVariants: ['— Walking Pad', '— With Incline + Handle Rails (₦198000)'],
    features: ['Slides under the bed — cardio without the gym queue', 'Remote control speed from 1 to 8 km/h', 'Shock-absorbing belt kind to downstairs neighbours', 'LED display tracks steps, distance and calories'] },
  { name: 'Adjustable Dumbbell (Single)', category: 'health-wellness', type: 'PHYSICAL', price: 48500, seller: 'wellspring-wellness-co',
    material: 'Iron plates, anti-slip grip', dimensions: '2.5–24 kg dial adjustment',
    colours: ['Black/Yellow'],
    namedVariants: ['— Single 24 kg', '— Pair (₦92500)', '— Single 41 kg Pro (₦78500)'],
    features: ['Fifteen dumbbells in one dial — the honest space saver', 'Dial locks plates with a click you can hear', 'Anti-slip handle survives sweaty sets', 'Storage tray included'] },
  { name: 'Exercise Bike (Magnetic)', category: 'health-wellness', type: 'PHYSICAL', price: 128000, seller: 'wellspring-wellness-co',
    material: 'Steel frame, magnetic resistance', dimensions: '8 resistance levels; 120 kg max; LCD monitor',
    colours: ['Black/Red', 'Black/Silver'],
    namedVariants: ['— Upright', '— Foldable X-Bike (₦98500)', '— Spin Style with Tablet Holder (₦158000)'],
    features: ['Magnetic resistance is silent — ride during calls and films', 'Eight levels from rehab-spin to hill-climb', 'LCD tracks time, speed, distance and pulse', 'Moves on transport wheels to hide between rides'] },
  { name: 'Acupressure Ring & Finger Massager', category: 'health-wellness', type: 'PHYSICAL', price: 3500, seller: 'wellspring-wellness-co',
    material: 'Stainless steel sprung rings', dimensions: 'Set of 3 sizes',
    colours: ['Steel'],
    features: ['Rolls desk-day stiffness out of fingers in a minute', 'Three ring sizes fit every finger', 'Pocket tin lives next to the keyboard', 'No batteries, no noise, no excuses'] },
  { name: 'Neck & Shoulder Heating Pad', category: 'health-wellness', type: 'PHYSICAL', price: 8500, seller: 'wellspring-wellness-co',
    material: 'Microplush, fast-heat carbon fibre', dimensions: 'Neck wrap design; 3 heat levels; auto-off',
    colours: ['Grey'],
    features: ['Drapes the neck and trapezius hands-free', 'Heats in thirty seconds with three honest levels', 'Two-hour auto-off for dozing-off safety', 'Machine washable cover'] },
  { name: 'Menstrual Heat Belt (Cordless)', category: 'health-wellness', type: 'PHYSICAL', price: 11500, seller: 'wellspring-wellness-co',
    material: 'Soft wrap, graphite heating layer', dimensions: 'Adjustable 80–130 cm; 4 heat levels',
    colours: ['Blush', 'Grey'],
    features: ['Wears under clothes through a working day', 'Cordless battery runs a full cycle-day per charge', 'Four levels including gentle-warm for sensitive days', 'Machine washable wrap'] },
  { name: ' Portable Blender (Rechargeable)', category: 'health-wellness', type: 'PHYSICAL', price: 12500, seller: 'wellspring-wellness-co',
    material: 'Tritan jar, stainless blades', dimensions: '500 ml; 12-blade; USB-C',
    colours: ['Mint', 'Blush', 'White'],
    namedVariants: ['— 500 ml Standard', '— 350 ml Mini (₦9500)', '— With Ice-Crush Motor (₦15500)'],
    features: ['Smoothie at the desk, gym bag or hotel room', 'Twelve-blade stainless head crushes frozen fruit', 'USB-C rechargeable — about 15 blends per charge', 'Self-clean mode with a drop of soap and water'] },
  { name: 'Food Scale (Digital)', category: 'health-wellness', type: 'PHYSICAL', price: 5500, seller: 'wellspring-wellness-co',
    material: 'Tempered glass, alloy sensors', dimensions: '1 g–10 kg; units g/oz/ml',
    colours: ['Black Glass', 'White Glass'],
    features: ['Gram-exact portions turn meal plans into results', 'Tare button ignores the bowl honestly', 'Reads ml for liquids on the same platform', 'Slim glass wipes clean after every use'] },
  { name: 'Meal Prep Container Set (Glass)', category: 'health-wellness', type: 'PHYSICAL', price: 16500, seller: 'wellspring-wellness-co',
    material: 'Borosilicate glass, snap-lock lids', dimensions: '5 × 820 ml; oven-safe to 400 °C',
    colours: ['Clear/Green Lids'],
    namedVariants: ['— 5-Piece Set', '— 3-Piece Starter (₦10500)', '— 10-Piece Family (₦29500)'],
    features: ['Glass never stains with stew the way plastic does', 'Oven, microwave and freezer safe — one container cooks and stores', 'Snap-lock lids with silicone gaskets survive the bag', 'Portion-etched sides keep serving sizes honest'] },
  { name: 'Hand Therapy Putty Set', category: 'health-wellness', type: 'PHYSICAL', price: 4500, seller: 'wellspring-wellness-co',
    material: 'Silicone putty, four resistances', dimensions: '4 × 85 g tubs',
    colours: ['Progressive Colours'],
    features: ['Four resistances rebuild grip after injury or typing years', 'Colour-coded tubs track progress honestly', 'Squeezes quietly through meetings', 'Non-greasy formula never dries out'] },
  { name: 'Balance Board (Wobble)', category: 'health-wellness', type: 'PHYSICAL', price: 9500, seller: 'wellspring-wellness-co',
    material: 'Plywood deck, non-slip surface', dimensions: 'Ø 40 cm; 15° tilt; 150 kg max',
    colours: ['Natural Wood'],
    features: ['Ten minutes of balancing recruits muscles squats never find', 'Non-slip deck grips socks and soles alike', 'Under-desk use for standing-desk days', 'Holds 150 kg without cracking'] },
  { name: 'African Black Soap (Family Pack)', category: 'beauty-perfumes', type: 'PHYSICAL', price: 3500, seller: 'wellspring-wellness-co',
    material: 'Traditional black soap, shea, palm ash', dimensions: '6 × 150 g bars',
    colours: ['Raw', 'With Honey'],
    namedVariants: ['— 6-Bar Family Pack', '— Single Bar (₦800)', '— Liquid Body Wash 500 ml (₦5500)'],
    features: ['Traditional recipe lathers deep without stripping', 'Shea content keeps it kind through harmattan', 'Cuts through sunscreen and city grime', 'Family pack covers the bathroom for weeks'] },
  { name: 'Rosewater Facial Toner', category: 'beauty-perfumes', type: 'PHYSICAL', price: 4500, seller: 'wellspring-wellness-co',
    material: 'Steam-distilled rosewater, glycerin', dimensions: '200 ml spray bottle',
    colours: ['Classic Rose', 'Rose + Niacinamide'],
    features: ['Two-ingredient toner: rosewater and glycerin, honestly', 'Spray format refreshes over make-up midday', 'Niacinamide variant supports even tone', 'No alcohol sting on freshly washed skin'] },
  { name: 'Argan Hair Serum', category: 'beauty-perfumes', type: 'PHYSICAL', price: 6500, seller: 'wellspring-wellness-co',
    material: 'Argan oil blend, vitamin E', dimensions: '60 ml pump bottle',
    colours: ['Original', 'With Castor'],
    features: ['Three pumps seal split ends before styling heat', 'Pump doses without oiling the whole bottle', 'Light enough for relaxed and natural hair alike', 'Vitamin E supports scalp between wash days'] },
  { name: 'Body Shimmer Oil', category: 'beauty-perfumes', type: 'PHYSICAL', price: 7500, seller: 'wellspring-wellness-co',
    material: 'Fractionated coconut, mica shimmer', dimensions: '100 ml spray',
    colours: ['Gold Shimmer', 'Bronze Shimmer'],
    features: ['Event-night shimmer that photographs like a filter', 'Coconut base moisturises while it glows', 'Spray reaches your own shoulders evenly', 'Washes off with soap, no glitter landfill'] },
  { name: 'Scented Body Mist Set (3×)', category: 'beauty-perfumes', type: 'PHYSICAL', price: 6500, seller: 'wellspring-wellness-co',
    material: 'Alcohol-light mist, glycerin', dimensions: '3 × 150 ml',
    colours: ['Vanilla Cloud', 'Pink Pepper & Peony', 'Ocean Air'],
    features: ['Three moods for bag, bathroom and bedside', 'Alcohol-light formula doesn\'t dry skin out', 'Layerable with the matching roll-on oils', 'Glycerin keeps the mist feeling soft'] },
  { name: 'Men\'s Skincare Starter Set', category: 'beauty-perfumes', type: 'PHYSICAL', price: 9500, seller: 'wellspring-wellness-co',
    material: 'Cleanser, moisturiser, beard oil trio', dimensions: '3 × 100 ml',
    colours: ['Fragrance-Free', 'Cedar Scented'],
    namedVariants: ['— Trio Set', '— With Face Scrub (₦12500)'],
    features: ['Three steps, ninety seconds, honest skin', 'Cleanser cuts through sunscreen without tightness', 'Moisturiser disappears under beards', 'Cedar-scented option avoids the floral aisle'] },
  { name: 'Gift & Self-Care Hamper', category: 'beauty-perfumes', type: 'PHYSICAL', price: 18500, seller: 'wellspring-wellness-co',
    material: 'Curated set in a keepsake basket', dimensions: '6 items + card',
    colours: ['Spa Day Theme', 'New Mum Theme', 'Get Well Theme'],
    namedVariants: ['— Spa Day Hamper', '— New Mum Hamper', '— Birthday Luxe (₦24500)'],
    features: ['Six curated items themed for the recipient', 'Keepsake basket doubles as storage', 'Handwritten card included at checkout notes', 'Gift-ready wrapping — no extra shopping needed'] },
  { name: 'Silicone Wedding-Proof Cooking Mitts', category: 'health-wellness', type: 'PHYSICAL', price: 4500, seller: 'wellspring-wellness-co',
    material: 'Food-grade silicone, cotton lining', dimensions: 'Heat-safe to 230 °C; pair',
    colours: ['Sage', 'Charcoal', 'Blush'],
    features: ['Grips hot pots without the steam-burn through fabric', 'Waterproof — no wet-cloth shock when lifting lids', 'Textured surface holds slippery serving dishes', 'Dishwasher safe, hanging loop included'] },

  // ═══ Top-up alabi/zuri edge families ═══════════════════
  { name: 'Kids Learning Tablet', category: 'electronics', type: 'PHYSICAL', price: 28500, seller: 'alabi-techhub',
    material: 'Shockproof silicone bumper case', dimensions: '7" screen; parental controls',
    colours: ['Blue', 'Pink', 'Green'],
    namedVariants: ['— 32 GB', '— 64 GB with Headphones (₦34500)'],
    features: ['Curated learning apps behind a parental gate', 'Shockproof bumper survives real siblings', 'Eye-protection mode softens evening screens', 'Offline mode keeps school apps usable without data'],
    includes: ['Stylus', 'Screen protector', 'Charger'] },
  { name: 'Fast Wireless Car Charger Mount', category: 'electronics', type: 'PHYSICAL', price: 15500, seller: 'alabi-techhub',
    material: 'Alloy arm, silicone grip', dimensions: 'CD-slot and vent mounts included',
    colours: ['Black'],
    features: ['Clamps and charges in one motion at 15 W', 'Vent and CD-slot mounts for any dashboard', 'Foreign-object detection stops charging on coins', 'One-hand release lever works while parked'] },
  { name: 'Bed Frame with Under-Storage (Queen)', category: 'furniture', type: 'PHYSICAL', price: 185000, seller: 'zuri-home-living',
    material: 'Engineered wood, upholstered headboard', dimensions: 'Queen 150 × 200 cm; four drawers',
    colours: ['Grey Fabric', 'Beige Fabric'],
    namedVariants: ['— Queen with 4 Drawers', '— King with 6 Drawers (₦225000)', '— Ottoman Gas-Lift Base (₦245000)'],
    features: ['Four real drawers swallow bedding and suitcases', 'Upholstered headboard reads hotel-grade', 'Solid slat base supports any mattress without a board', 'Gas-lift variant lifts the whole base for full access'],
    leadTime: 'Made to order — dispatches in 10–14 working days.' },
  { name: 'Dresser with 6 Drawers', category: 'furniture', type: 'PHYSICAL', price: 128000, seller: 'zuri-home-living',
    material: 'Engineered wood, metal runners', dimensions: 'W 120 × H 80 cm',
    colours: ['Walnut Look', 'White', 'Black'],
    namedVariants: ['— 6 Drawers', '— 3 Drawers Compact (₦88500)', '— With Mirror Bundle (₦158000)'],
    features: ['Six full-extension drawers sort a whole wardrobe\'s flat-lays', 'Rounded corners for family hallways', 'Anti-tip strap included', 'Matching mirror available as a bundle'],
    leadTime: 'Made to order — dispatches in 7–10 working days.' },
  { name: 'Study Table & Chair Set for Kids', category: 'furniture', type: 'PHYSICAL', price: 58500, seller: 'zuri-home-living',
    material: 'Solid pine, rounded edges', dimensions: 'Desk 80 × 50 cm; adjustable height chair',
    colours: ['Natural', 'White', 'Blue'],
    features: ['Grows with the child through adjustable chair height', 'Rounded pine edges survive enthusiasm', 'Side hooks for school bags keep floors clear', 'Cable slot for the learning tablet'],
    leadTime: 'Made to order — dispatches in 5–7 working days.' },

  // ── Final top-up batch (closes per-seller deficits) ───
  { name: 'Magnetic Charging Cable Trio (6-Pack)', category: 'electronics', type: 'PHYSICAL', price: 8900, seller: 'alabi-techhub',
    material: 'Nylon braid, magnetic tips', dimensions: 'Three 1 m cables, six tips (C/L/micro)',
    colours: ['Black', 'Silver'],
    namedVariants: ['— 6-Pack Mixed Tips', '— 3-Pack USB-C Only (₦5500)', '— 100 W PD Version (₦12500)'],
    features: ['One-handed snap charging in the dark', 'Magnetic tips stay in devices, sealing ports against fluff', 'Nylon braid survives the desk drawer', 'LED ring finds the cable before you do'],
  },
  { name: 'Bluetooth FM Transmitter with QC3.0', category: 'electronics', type: 'PHYSICAL', price: 11900, seller: 'alabi-techhub',
    material: 'ABS body, matte display', dimensions: 'Dual QC3.0 ports; 12 V powered',
    colours: ['Black'],
    namedVariants: ['— Dual QC3.0', '— With USB-C PD (₦13500)', '— With Voltmeter Display (₦12900)'],
    features: ['QC3.0 ports charge phones at full speed in traffic', 'Five EQ presets tune FM audio beyond the usual flat', 'Hands-free calls through the built-in mic', 'Voltmeter variant watches battery health on long trips'],
  },

  // ═══ WELLSPRING top-up ══════════════════════════════
  { name: 'Posture & Core Trainer Seat Cushion', category: 'health-wellness', type: 'PHYSICAL', price: 11500, seller: 'wellspring-wellness-co',
    material: 'High-density foam, breathable mesh cover', dimensions: '45 × 40 × 10 cm; U-shaped coccyx cut',
    colours: ['Grey', 'Black', 'Sage'],
    namedVariants: ['— Seat Cushion', '— Lumbar Support Pair (₦18500)'],
    features: ['Coccyx cut-out removes tailbone pressure on long desk days', 'Dense foam keeps its height through eight hours of sitting', 'Breathable mesh survives Nigerian afternoons', 'Non-slip base grips wooden and tiled chairs'],
  },

  // ═══ BRIGHTPATH top-up ══════════════════════════════
  { name: 'Grant & NGO Proposal Writing Course', category: 'digital-education', type: 'DIGITAL', price: 13900, seller: 'brightpath-digital-academy',
    format: '24 lessons (MP4, 3.5 h) + proposal templates (DOCX) + funder research sheet',
    contents: ['Reading a funder brief the way reviewers do', 'Problem statements backed by real data sources', 'Budgets that survive due diligence', 'The follow-up and reporting that wins the next grant'],
    audience: 'NGO staff, founders and consultants pursuing funding',
    requirements: ['Word or Google Docs'],
    outcome: 'A submitted proposal and a reusable template library',
    namedVariants: ['— Self-Paced', '— With Proposal Review (₦21900)', '— Team Licence 3 Seats (₦29900)', '— With Donor Database Guide (₦17900)', '— Cohort with Live Clinic (₦25900)'] },
  { name: 'Social Media Manager Bootcamp', category: 'digital-education', type: 'DIGITAL', price: 18900, seller: 'brightpath-digital-academy',
    format: '38 lessons (MP4, 5.5 h) + client proposal template + content calendar system + portfolio guide',
    contents: ['Managing five client accounts without drowning', 'Content systems, batch creation and approval flows', 'Basic ads and boosted-post decisions per platform', 'Reporting templates clients actually read'],
    audience: 'Freelancers starting social media management as a service',
    requirements: ['A free Canva account and one practice brand'],
    outcome: 'A priced service, a portfolio and a delivery system',
    namedVariants: ['— Self-Paced', '— With Client Acquisition Scripts (₦24900)', '— With Personal Brand Module (₦22900)', '— Team Licence 5 Seats (₦59900)', '— With Portfolio Review Clinic (₦28900)', '— Agency Systems Edition (₦32900)'] },
];

export function applyWave4(items: SeedItem[]): SeedItem[] {
    return [...items, ...WAVE4_ITEMS];
  }
