// ============================================================
// KOVA — Wave-3 catalog families (DEMO DATA ONLY)
// Final expansion wave so every seller clears the 200-product
// floor. Distinct real product families — not duplicates —
// each with real attributes, variants and composed descriptions.
// ============================================================

import type { SeedItem } from './seed-data';

export const WAVE3_ITEMS: SeedItem[] = [
  // ═══ ALABI TECHHUB (needs +60) ═════════════════════════
  { name: 'Ergonomic Vertical Mouse', category: 'electronics', type: 'PHYSICAL', price: 14500, seller: 'alabi-techhub',
    material: 'Textured ABS, rubber thumb rest', dimensions: 'Fits M/L hands; 2.4 GHz + Bluetooth',
    colours: ['Black', 'White'],
    namedVariants: ['— Rechargeable', '— With USB-C Dock (₦18500)'],
    features: ['57° vertical grip relieves wrist pronation pain', 'Silent switches rated 5M clicks', 'Switches between three devices with one button', '800/1200/1600 DPI cycle for precision and speed'],
    includes: ['USB-C cable'] },
  { name: 'Laptop Backpack with USB Port', category: 'electronics', type: 'PHYSICAL', price: 19900, seller: 'alabi-techhub',
    material: 'Water-repellent 900D Oxford, YKK zips', dimensions: 'Fits up to 15.6"; 28 L',
    colours: ['Charcoal', 'Navy', 'Black'],
    features: ['Padded suspended laptop sleeve survives dropped bags', 'Luggage pass-through slides over trolley handles', 'External USB port pairs with your own power bank inside', 'Anti-theft back pocket for passport and wallet'] },
  { name: 'Wireless Carplay Adapter', category: 'electronics', type: 'PHYSICAL', price: 38500, seller: 'alabi-techhub',
    material: 'Matte puck, USB-A/C cables included', dimensions: '8 × 5 × 1.5 cm',
    colours: ['Black'],
    features: ['Converts wired CarPlay to wireless on factory head units', 'Connects in ~10 seconds after first pairing', 'Pass-through USB keeps the phone charging', 'Firmware updatable over the companion app'] },
  { name: 'Smart LED Strip Lights (5 m)', category: 'electronics', type: 'PHYSICAL', price: 11500, seller: 'alabi-techhub',
    material: 'Adhesive-backed RGBIC strip', dimensions: '5 m (also 10 m); app + remote',
    colours: ['RGB Multicolor'],
    namedVariants: ['— 5 m', '— 10 m (₦19500)', '— With Music Sync Box (₦16500)'],
    features: ['RGBIC segments show multiple colours at once', 'Music mode reacts to game and movie audio', 'App schedules wake-up and wind-down scenes', 'Cuttable to length at marked points'] },
  { name: 'Solar Power Bank 26800mAh', category: 'electronics', type: 'PHYSICAL', price: 29500, seller: 'alabi-techhub',
    material: 'Rubberised shell, solar panel face', dimensions: '16 × 8 × 2 cm; IPX4',
    colours: ['Black/Orange', 'Camo'],
    namedVariants: ['— 26800 mAh', '— 36800 mAh (₦38500)'],
    features: ['Solar trickle charging keeps it alive off-grid (primary charging is USB-C 18 W)', 'Four outputs charge phone, earbuds and torch together', 'Built-in flashlight with SOS mode', 'IPX4 splash resistance for outdoor use'] },
  { name: 'Digital Tyre Inflator', category: 'electronics', type: 'PHYSICAL', price: 22500, seller: 'alabi-techhub',
    material: 'Metal cylinder, ABS housing', dimensions: 'Preset pressure auto-shutoff; 12 V + battery',
    colours: ['Black/Yellow'],
    features: ['Set target PSI and walk away — auto-shutoff prevents blowouts', 'Inflates a tyre in under three minutes from flat-ish', 'LED work light and powerbank output for emergencies', 'Stores in the boot with the cable tidy bag'],
    includes: ['Valve adapters', 'Storage bag'] },
  { name: 'Wireless Charging Car Mount', category: 'electronics', type: 'PHYSICAL', price: 13500, seller: 'alabi-techhub',
    material: 'Alloy arm, silicone cradle', dimensions: 'Air-vent clamp; 15 W Qi coil',
    colours: ['Black'],
    features: ['Clamps the phone automatically when docked', '15 W Qi charging with foreign-object detection', 'One-hand mount and release while parked', 'Ball joint angles the screen toward the driver'] },
  { name: 'Bluetooth Tracker Tags (4-Pack)', category: 'electronics', type: 'PHYSICAL', price: 11900, seller: 'alabi-techhub',
    material: 'IP67 shell, CR2032 powered', dimensions: 'Coin-sized; 80 dB alarm',
    colours: ['Black', 'White'],
    features: ['Rings loudly when keys vanish into sofa depths', 'Crowd-find network shows last seen location', 'IP67 survives rain and washing machine accidents', 'Replaceable coin cells last about a year'] },
  { name: 'Noise-Isolating Wired Earbuds', category: 'electronics', type: 'PHYSICAL', price: 6500, seller: 'alabi-techhub',
    material: 'Aluminium housings, braided cable', dimensions: '3.5 mm plug; mic remote',
    colours: ['Black', 'Silver', 'Blue'],
    features: ['Passive isolation beats cheap ANC on a bus', 'Braided cable refuses to tangle in pockets', 'Three-button remote handles calls and volume', 'Spare ear-tip sizes included'] },
  { name: 'Mesh Wi-Fi 6 System (2-Pack)', category: 'electronics', type: 'PHYSICAL', price: 68500, seller: 'alabi-techhub',
    material: 'White shell, wall-plug or desk', dimensions: 'Covers ~250 m² combined',
    colours: ['White'],
    namedVariants: ['— 2-Pack', '— 3-Pack (₦96500)'],
    features: ['One network name across the whole house — no more range drama', 'Wi-Fi 6 handles 40+ smart devices without choking', 'Wired backhaul option for maximum speed', 'App shows every connected device and pauses the kids\' Wi-Fi'] },
  { name: 'USB-A to USB-C Adapter Set', category: 'electronics', type: 'PHYSICAL', price: 3500, seller: 'alabi-techhub',
    material: 'Aluminium housings', dimensions: '6 adapters: 3×A→C, 3×C→A',
    colours: ['Silver'],
    features: ['Bridges the old and new port worlds on every cable', 'Solid aluminium housings survive keyring duty', 'Supports charging and data at USB 2.0 speeds minimum', 'Six pack covers bag, desk, car and lounge'] },
  { name: 'Streaming Microphone Arm Stand', category: 'electronics', type: 'PHYSICAL', price: 16900, seller: 'alabi-techhub',
    material: 'Heavy steel with spring suspension', dimensions: 'Reach 95 cm; desk clamp to 5.5 cm',
    colours: ['Black'],
    features: ['Suspension arm swings the mic into position and stays', 'Hidden cable channels keep the desk clean', 'Clamp pads protect desk surfaces', 'Standard threads fit most broadcast mics'] },
  { name: 'Portable Bluetooth Turntable', category: 'electronics', type: 'PHYSICAL', price: 54900, seller: 'alabi-techhub',
    material: 'Wood-effect plinth, dust cover', dimensions: '33/45 RPM; built-in speakers',
    colours: ['Walnut Look', 'Black'],
    features: ['Plays 33 and 45 RPM records with the included 45 adapter', 'Bluetooth streams vinyl to bigger speakers', 'Built-in speakers for instant playback', 'Belt-drive motor keeps wow and flutter honest'],
    includes: ['45 RPM adapter', 'Replacement stylus'] },
  { name: 'Anti-Theft Sling Bag', category: 'electronics', type: 'PHYSICAL', price: 14900, seller: 'alabi-techhub',
    material: 'Cut-resistant fabric, hidden zips', dimensions: 'Fits tablet + essentials; 6 L',
    colours: ['Black', 'Grey', 'Olive'],
    features: ['Hidden back-panel zips face the body in crowds', 'Cut-resistant strap and fabric layers', 'USB port pairs with an internal power bank', 'RFID-blocking pocket shields contactless cards'] },
  { name: 'Universal Remote Control', category: 'electronics', type: 'PHYSICAL', price: 8500, seller: 'alabi-techhub',
    material: 'Rubberised shell', dimensions: 'Controls 8 devices; backlit keys',
    colours: ['Black'],
    features: ['Replaces the decoder, TV and soundbar remotes with one', 'Backlit keys findable in load-shedding darkness', 'Learning mode copies stubborn original remotes', 'Macro buttons switch the whole lounge in one press'] },

  // ═══ ZURI HOME LIVING (needs +63) ══════════════════════
  { name: 'Nonstick Frying Pan Trio', category: 'interior-home', type: 'PHYSICAL', price: 27500, seller: 'zuri-home-living',
    material: 'Forged aluminium, granite-look coating', dimensions: '20 / 24 / 28 cm; induction ready',
    colours: ['Granite Grey', 'Cream'],
    features: ['Three sizes cover eggs, fish and family jollof', 'Granite-look coating releases without metal-scratching', 'Stay-cool bakelite handles', 'Works on gas, electric and induction hobs'] },
  { name: 'Electric Kettle 1.8L', category: 'interior-home', type: 'PHYSICAL', price: 15500, seller: 'zuri-home-living',
    material: 'Stainless interior, cool-touch shell', dimensions: '1.8 L; 2200 W rapid boil',
    colours: ['Brushed Steel', 'White'],
    namedVariants: ['— Standard', '— Glass Body with Blue LED (₦18500)'],
    features: ['Boils in under four minutes for tea and garri emergencies', 'Strix auto-shutoff and boil-dry protection', 'Wide lid opens fully for descaling', 'Cordless 360° base lifts from any angle'] },
  { name: 'Spice Jar Carousel (12-Jar)', category: 'interior-home', type: 'PHYSICAL', price: 13500, seller: 'zuri-home-living',
    material: 'Glass jars, bamboo turntable', dimensions: 'Ø 26 cm turntable; 120 ml jars',
    colours: ['Bamboo/Clear'],
    features: ['Spins every jar to the front — no more digging', 'Airtight bamboo lids with silicone gaskets', 'Chalk labels included, rewriting is encouraged', 'Jars refill from any spice bulk bag'] },
  { name: 'Stackable Fridge Organizer Bins', category: 'interior-home', type: 'PHYSICAL', price: 9500, seller: 'zuri-home-living',
    material: 'BPA-free PET, grip handles', dimensions: 'Set of 4: two large, two small',
    colours: ['Clear'],
    features: ['Clear walls make leftovers findable before they become science', 'Stackable with grip handles for one-hand pulls', 'Fridge, freezer and pantry safe', 'Rounded corners wipe clean in seconds'] },
  { name: 'Magnetic Spice Rack Strip', category: 'interior-home', type: 'PHYSICAL', price: 7500, seller: 'zuri-home-living',
    material: 'Alloy magnetic bar + 6 tins', dimensions: '40 cm bar; wall-mounted',
    colours: ['Brushed Steel'],
    features: ['Mounts on the wall or fridge side — zero counter space', 'Six magnetic tins with clear window lids', 'Peel-and-stick or screw mounting both included', 'Tins hold roughly 100 ml of everyday spices'] },
  { name: 'Slow Cooker 3.5L', category: 'interior-home', type: 'PHYSICAL', price: 32500, seller: 'zuri-home-living',
    material: 'Stoneware pot, brushed housing', dimensions: '3.5 L; three heat settings',
    colours: ['Black', 'Cream'],
    namedVariants: ['— 3.5 L', '— 5.5 L Family (₦42500)'],
    features: ['Dinner starts at 7am and finishes itself', 'Low/High/Warm settings for beans, soups and stews', 'Removable stoneware pot serves at the table', 'Glass lid with a steam vent'] },
  { name: 'Velvet Accent Chair', category: 'furniture', type: 'PHYSICAL', price: 74500, seller: 'zuri-home-living',
    material: 'Velvet upholstery, birch legs', dimensions: 'Seat H 47 cm; W 68 cm',
    colours: ['Emerald', 'Blush', 'Mustard'],
    features: ['Deep seat with a supportive lumbar curve', 'Birch legs finished with floor-safe pads', 'Velvet spot-cleans with a damp cloth', 'Assembles in ten minutes, tools included'],
    leadTime: 'Made to order — dispatches in 5–7 working days.' },
  { name: 'Writing Desk with Drawers', category: 'furniture', type: 'PHYSICAL', price: 88500, seller: 'zuri-home-living',
    material: 'Engineered wood, metal runners', dimensions: '120 × 55 × 76 cm; two drawers',
    colours: ['Walnut Look', 'White', 'Black'],
    namedVariants: ['— Two Drawers', '— Three Drawers with File Rail (₦98500)'],
    features: ['Cable grommet keeps laptop wiring tidy', 'Drawers on smooth full-extension runners', 'Water-resistant top wipes clean of ink and coffee', 'Anti-tip kit included for family homes'],
    leadTime: 'Made to order — dispatches in 4–6 working days.' },
  { name: 'Wardrobe Hanging Rail Organizer', category: 'interior-home', type: 'PHYSICAL', price: 8500, seller: 'zuri-home-living',
    material: 'Powder-coated steel', dimensions: 'Fits rails 25–35 mm; 5 tiers',
    colours: ['White', 'Black'],
    features: ['Five hanging tiers triple a single rail\'s capacity', 'Hangs from the existing wardrobe rail in seconds', 'S-hooks included for scarves and belts', 'Folds flat when the season changes'] },
  { name: 'Memory Foam Pillow (Pair)', category: 'interior-home', type: 'PHYSICAL', price: 24500, seller: 'zuri-home-living',
    material: 'Ventilated memory foam, bamboo-blend cover', dimensions: 'Standard 50 × 75 cm',
    colours: ['White'],
    namedVariants: ['— Standard Pair', '— Contour Pair (₦28500)'],
    features: ['Ventilated foam sleeps cooler than solid slabs', 'Bamboo-blend covers unzip for washing', 'Medium loft suits back and side sleepers', 'Compressed-packed; full loft within 48 hours'] },
  { name: 'Scented Candle Trio', category: 'interior-home', type: 'PHYSICAL', price: 9500, seller: 'zuri-home-living',
    material: 'Soy wax blend, cotton wicks', dimensions: '3 × 180 g tins; 25 h burn each',
    colours: ['Vanilla & Oak', 'Lemongrass & Ginger', 'Rose & Oud'],
    features: ['Soy blend burns clean without paraffin soot', 'Cotton wicks trimmed ready to light', 'Tins reusable for spices and pins', 'Three scent moods: warm, fresh and floral'] },
  { name: 'Jute Runner Rug', category: 'interior-home', type: 'PHYSICAL', price: 18500, seller: 'zuri-home-living',
    material: 'Hand-braided jute', dimensions: '70 × 240 cm runner',
    colours: ['Natural', 'Natural with Grey Border'],
    features: ['Hand-braided texture that hides real-life crumbs', 'Natural jute is tough in hallways', 'Reversible for double the life', 'Sheds a little at first — normal for jute'] },
  { name: 'Ceramic Planter with Drainage (Set of 3)', category: 'interior-home', type: 'PHYSICAL', price: 15500, seller: 'zuri-home-living',
    material: 'Glazed ceramic with saucers', dimensions: 'Ø 12 / 15 / 18 cm',
    colours: ['Matte White', 'Terracotta', 'Speckled Sage'],
    features: ['Drainage holes with matching saucers — plants live longer', 'Weighted bases suit top-heavy monstera babies', 'Glazed interiors protect shelves from water', 'Nesting sizes group or scatter nicely'] },
  { name: 'LED Under-Cabinet Light Bars', category: 'interior-home', type: 'PHYSICAL', price: 11500, seller: 'zuri-home-living',
    material: 'Aluminium bars, magnetic mounts', dimensions: '3 bars; USB-C rechargeable',
    colours: ['Silver'],
    features: ['Lights the chopping board, not the back of your hand', 'Magnetic mounts pop off for charging', 'Tap or motion-activated modes', 'No wiring — installs in five minutes'] },
  { name: 'Over-Door Hook Rack', category: 'interior-home', type: 'PHYSICAL', price: 6500, seller: 'zuri-home-living',
    material: 'Alloy rail, 6 hooks', dimensions: 'Fits doors to 4.5 cm thick',
    colours: ['Black', 'Nickel'],
    features: ['Six hooks for coats, bags and towels without drilling', 'Padded backs spare the door paint', 'Rubber-tipped hooks grip slippery straps', 'Installs in ten seconds, moves whenever'] },

  // ═══ WELLSPRING (needs +90) ════════════════════════════
  { name: 'Foam Yoga Blocks (Pair)', category: 'health-wellness', type: 'PHYSICAL', price: 7500, seller: 'wellspring-wellness-co',
    material: 'High-density EVA foam', dimensions: '23 × 15 × 10 cm each',
    colours: ['Sage', 'Charcoal', 'Blush'],
    features: ['High-density foam supports full weight without squashing', 'Bevelled edges grip sweaty palms', 'Brings the floor closer in poses and stretches', 'Wipes clean after hot sessions'] },
  { name: 'Yoga Wheel', category: 'health-wellness', type: 'PHYSICAL', price: 11500, seller: 'wellspring-wellness-co',
    material: 'ABS core, TPE padding', dimensions: 'Ø 33 cm × 13 cm wide',
    colours: ['Sage', 'Rose'],
    features: ['Opens chest and shoulders safely in backbends', 'Padded ring cushions the spine', 'Supports up to 150 kg without flex', 'Rolls out forearm and quad tension too'] },
  { name: 'Ab Roller Wheel with Knee Mat', category: 'health-wellness', type: 'PHYSICAL', price: 8500, seller: 'wellspring-wellness-co',
    material: 'Dual ABS wheels, foam grips', dimensions: 'Wheel Ø 18 cm; knee mat included',
    colours: ['Black/Red', 'Black/Blue'],
    features: ['Dual wheels track straight — no wobble mid-rep', 'Wide tyre rolls on tiles and rugs alike', 'Knee mat included, no folded-towel improvisation', 'Strips to a compact travel size'] },
  { name: 'Exercise Hula Hoop (Weighted)', category: 'health-wellness', type: 'PHYSICAL', price: 9500, seller: 'wellspring-wellness-co',
    material: 'Foam-padded detachable segments', dimensions: '8 segments; Ø 96 cm assembled',
    colours: ['Purple', 'Rose', 'Slate'],
    features: ['Detaches into eight pieces for storage and travel', 'Foam padding is kind to hips while learning', 'Adjustable diameter by removing segments', 'Ten minutes of hooping sneaks real cardio into TV time'] },
  { name: 'Ankle & Wrist Weights (Pair)', category: 'health-wellness', type: 'PHYSICAL', price: 8500, seller: 'wellspring-wellness-co',
    material: 'Soft fabric pockets, iron sand fill', dimensions: '1 kg each; adjustable strap',
    colours: ['Sage', 'Charcoal'],
    namedVariants: ['— 1 kg Pair', '— 2 kg Pair (₦11500)'],
    features: ['Weights sit snug without chafing on walks and Pilates', 'Straps adjust over ankles and wrists alike', 'Evenly distributed fill — no lump sliding', 'Machine-washable shell'] },
  { name: 'Hydration Tracking Bottle 2L', category: 'health-wellness', type: 'PHYSICAL', price: 6500, seller: 'wellspring-wellness-co',
    material: 'Tritan plastic, time-marked sleeve', dimensions: '2 L with hourly markings',
    colours: ['Clear/Sage', 'Clear/Blush'],
    features: ['Hourly marks turn a vague intention into a schedule', 'Wide mouth takes ice and fruit infusions', 'Leak-proof flip lid locks for bag transport', 'BPA-free Tritan survives drops'] },
  { name: 'Green Tea & Moringa Blend', category: 'health-wellness', type: 'PHYSICAL', price: 5500, seller: 'wellspring-wellness-co',
    material: 'Loose-leaf green tea, moringa, lemongrass', dimensions: '100 g resealable pouch',
    colours: ['Classic Blend', 'Mint Blend'],
    features: ['Whole-leaf green tea, not dust bags', 'Moringa adds body without bitterness', 'Resealable pouch keeps leaves fresh', 'Makes roughly 50 cups'] },
  { name: 'Immunity Booster Vitamin Gummies', category: 'health-wellness', type: 'PHYSICAL', price: 8500, seller: 'wellspring-wellness-co',
    material: 'Vitamin C, zinc, elderberry pectin gummies', dimensions: '60 gummies; 30-day supply',
    colours: ['Mixed Berry'],
    features: ['Pectin-based, no gelatin', 'Elderberry and zinc round out the vitamin C', 'Naturally flavoured — no medicine aftertaste', 'One-a-day dosing in a resealable tub'] },
  { name: 'Reusable Glass Water Bottles (2-Pack)', category: 'health-wellness', type: 'PHYSICAL', price: 7500, seller: 'wellspring-wellness-co',
    material: 'Borosilicate glass, silicone sleeves', dimensions: '550 ml each',
    colours: ['Amber', 'Clear/Grey'],
    features: ['Glass leaves no plastic taste in hot weather', 'Silicone sleeves grip and protect from knocks', 'Wide mouths fit ice cubes and brush cleaning', 'Two bottles rotate through the dishwasher'] },
  { name: 'Compression Foot Massager Roller', category: 'health-wellness', type: 'PHYSICAL', price: 5500, seller: 'wellspring-wellness-co',
    material: 'EVA nubs on PP core', dimensions: 'Ø 7 cm × 18 cm',
    colours: ['Slate', 'Sage'],
    features: ['Rolls out plantar fascia after long teaching or market days', 'Nub pattern mimics a therapist\'s thumb strip', 'Light enough to use from a desk chair', 'Wipes clean and stores under the sofa'] },
  { name: 'Posture Corrector Brace', category: 'health-wellness', type: 'PHYSICAL', price: 7500, seller: 'wellspring-wellness-co',
    material: 'Breathable neoprene blend', dimensions: 'Unisex S–XL; figure-8 design',
    colours: ['Black', 'Beige'],
    namedVariants: ['— Standard', '— With Lumbar Support Panel (₦9500)'],
    features: ['Gentle pull reminds shoulders back without forcing', 'Figure-8 straps adjust from both sides', 'Breathable mesh survives Nigerian heat under a shirt', 'Wear 20 minutes at a time while building the habit'] },
  { name: 'Wireless TENS Unit', category: 'health-wellness', type: 'PHYSICAL', price: 19500, seller: 'wellspring-wellness-co',
    material: 'Rechargeable pods, gel pads', dimensions: 'Pods 5 × 3 cm; app-controlled',
    colours: ['White'],
    features: ['Wireless pods free you from cable tangles during sessions', 'Six modes and 20 intensity levels via phone app', 'Rechargeable — no repeat battery purchases', 'Gel pads replaceable and widely available'] },
  { name: 'Acupressure Mat & Pillow Set', category: 'health-wellness', type: 'PHYSICAL', price: 13500, seller: 'wellspring-wellness-co',
    material: 'Cotton-linen cover, ABS lotus points', dimensions: 'Mat 65 × 42 cm; pillow included',
    colours: ['Sage', 'Navy', 'Plum'],
    features: ['8,800 lotus points ease back tension after desk days', 'Removable cover washes after sweaty use', 'Pillow targets neck and scalp', 'Starts with 5-minute sessions over a shirt'] },
  { name: 'Natural Deodorant Stick', category: 'beauty-perfumes', type: 'PHYSICAL', price: 4500, seller: 'wellspring-wellness-co',
    material: 'Shea, bicarbonate, arrowroot', dimensions: '75 g twist tube',
    colours: ['Unscented', 'Lemongrass', 'Cocoa'],
    features: ['Aluminium-free formula that still survives Lagos afternoons', 'Shea-based glide, no sticky residue', 'Twist tube dispenses without mess', 'Skin- adjusts within a week of switching'] },
  { name: 'Bath Loofah Set (3-Pack)', category: 'beauty-perfumes', type: 'PHYSICAL', price: 3500, seller: 'wellspring-wellness-co',
    material: 'Natural loofah with cotton cords', dimensions: 'Ø 12 cm each',
    colours: ['Natural'],
    features: ['Three-pack rotates monthly for hygiene', 'Natural loofah exfoliates without microplastics', 'Cord loop hangs to dry between uses', 'Softens in water, compostable at end of life'] },
  { name: 'Charcoal Teeth Whitening Powder', category: 'beauty-perfumes', type: 'PHYSICAL', price: 4000, seller: 'wellspring-wellness-co',
    material: 'Activated coconut charcoal, bentonite', dimensions: '50 g jar',
    colours: ['Natural'],
    features: ['Activated charcoal polishes surface stains from tea and coffee', 'Bentonite adds mineral polish without enamel harshness', 'Mint finish leaves breath fresh', 'A jar lasts about two months of evening use'] },
  { name: 'Silk Pillowcase (Standard)', category: 'beauty-perfumes', type: 'PHYSICAL', price: 11500, seller: 'wellspring-wellness-co',
    material: '22-momme mulberry silk', dimensions: 'Standard 50 × 75 cm; hidden zip',
    colours: ['Ivory', 'Charcoal', 'Blush'],
    features: ['22-momme silk reduces hair friction and bed-crease lines', 'Hidden zip keeps the pillow seated', 'Cool to the touch in hot nights', 'Hand wash or silk cycle, air dry'] },
  { name: 'Nail Care Kit with Dryer', category: 'beauty-perfumes', type: 'PHYSICAL', price: 9500, seller: 'wellspring-wellness-co',
    material: 'Stainless tools, 3 W UV lamp', dimensions: 'Case 18 × 12 cm',
    colours: ['Pink Case', 'Black Case'],
    features: ['UV mini-dryer sets polish between coats', 'Clippers, files, cuticle pusher and nippers included', 'Case elastics keep tools sorted', 'Fits a handbag for touch-up trips'] },
  { name: 'Heatless Curling Rod Kit', category: 'beauty-perfumes', type: 'PHYSICAL', price: 5500, seller: 'wellspring-wellness-co',
    material: 'Satin-covered foam rod, scrunchies', dimensions: 'Rod 55 cm; 2 scrunchies + clip',
    colours: ['Blush', 'Charcoal', 'Ivory'],
    features: ['Overnight curls without heat damage', 'Satin cover slides out without snagging', 'Works on relaxed and natural hair alike', 'Wake up, unwrap, fluff — done'] },
  { name: 'Body Shaper Seamless Shorts', category: 'beauty-perfumes', type: 'PHYSICAL', price: 8500, seller: 'wellspring-wellness-co',
    material: 'Nylon-spandex seamless knit', dimensions: 'S–XXL; mid-thigh',
    colours: ['Black', 'Nude', 'Chocolate'],
    namedVariants: ['— Mid-Thigh', '— High-Waist Long (₦9500)'],
    features: ['Seamless knit disappears under clothing', 'Breathable weave for long events', 'Four-way stretch that stays put without rolling', 'Hand wash to keep the elasticity honest'] },
  { name: 'Travel Steamer for Clothes', category: 'beauty-perfumes', type: 'PHYSICAL', price: 13500, seller: 'wellspring-wellness-co',
    material: 'Aluminium plate, 200 ml tank', dimensions: 'Folds to 22 cm; dual voltage',
    colours: ['White', 'Mint'],
    features: ['Kills event-morning wrinkles without an ironing board', '200 ml tank steams six shirts per fill', 'Dual voltage handles foreign trips', 'Folds flat into cabin luggage'] },

  // ═══ BRIGHTPATH (needs +98) ════════════════════════════
  { name: 'Facebook & Instagram Ads Masterclass', category: 'digital-education', type: 'DIGITAL', price: 19900, seller: 'brightpath-digital-academy',
    format: '30 lessons (MP4, 4.5 h) + campaign templates + audience research sheet',
    contents: ['Account structure that survives audits', 'Creative testing matrix on a ₦50k weekly budget', 'Pixel events and custom conversions done properly', 'Reading the numbers that decide scale or stop'],
    audience: 'Business owners and marketers running their first paid social',
    requirements: ['A Meta Business account and a small test budget'],
    outcome: 'A tested, measured campaign framework with written benchmarks',
    namedVariants: ['— Self-Paced', '— With Ad Account Audit (₦32900)'] },
  { name: 'SEO for Local Nigerian Businesses', category: 'digital-education', type: 'DIGITAL', price: 12900, seller: 'brightpath-digital-academy',
    format: '24 lessons (MP4, 3.6 h) + keyword research workbook + GBP optimisation checklist',
    contents: ['Google Business Profile setup that ranks in map results', 'Keyword research for what Nigerians actually type', 'On-page basics on WordPress, Wix or Shopify', 'Reviews and citations that build trust signals'],
    audience: 'Local shops, restaurants and service businesses',
    requirements: ['A live business location or service area'],
    outcome: 'A ranking profile and a 90-day content plan',
    namedVariants: ['— Self-Paced', '— With Site Audit (₦22900)'] },
  { name: 'Google Sheets Automation Course', category: 'digital-education', type: 'DIGITAL', price: 10900, seller: 'brightpath-digital-academy',
    format: '26 lessons (MP4, 3.8 h) + automation recipe library (20 scripts)',
    contents: ['Formulas that replace manual copy-paste workflows', 'Apps Script fundamentals for real automations', 'Connecting Forms, Sheets and Gmail', 'Dashboards that update themselves'],
    audience: 'Ops staff, VAs and small teams drowning in spreadsheets',
    requirements: ['A free Google account'],
    outcome: 'Three working automations running in your own workspace' },
  { name: 'WordPress Website in a Weekend', category: 'digital-education', type: 'DIGITAL', price: 14900, seller: 'brightpath-digital-academy',
    format: '28 lessons (MP4, 4 h) + theme + plugin checklist + maintenance calendar',
    contents: ['Hosting and domain choices without overspending', 'Building pages with a page builder, properly', 'Security, backups and updates on a schedule', 'Speed basics that keep Nigerian networks happy'],
    audience: 'Small businesses and freelancers needing a credible site fast',
    requirements: ['Hosting + domain (walkthrough included)'],
    outcome: 'A live, backed-up, maintainable business website' },
  { name: 'WhatsApp Business Selling System', category: 'digital-education', type: 'DIGITAL', price: 8900, seller: 'brightpath-digital-academy',
    format: '20 lessons (MP4, 2.8 h) + catalogue setup guide + 15 message templates',
    contents: ['Catalogue and business profile that converts visitors', 'Broadcast lists and labels for real CRM on WhatsApp', 'Payment flow options for Nigerian buyers', 'Message templates for enquiries, follow-ups and delivery'],
    audience: 'Instagram and WhatsApp sellers formalising operations',
    requirements: ['WhatsApp Business app (free)'],
    outcome: 'An organised sales pipeline inside the app buyers already use' },
  { name: 'CV Writing Service Templates (Recruiter Edition)', category: 'digital-products', type: 'DIGITAL', price: 11500, seller: 'brightpath-digital-academy',
    format: 'Recruiter-grade templates (DOCX/Slides) + screening rubric + outreach scripts',
    contents: ['The 6-second scan layout recruiters actually use', 'Achievement bullets with metrics placeholders that force honesty', 'Outreach scripts for referrals and cold applications', 'Tracking sheet for applications and follow-ups'],
    audience: 'HR staff and job seekers targeting competitive roles',
    requirements: ['Word or Google Docs'],
    outcome: 'Applications that survive the first human scan' },
  { name: 'Course Creator Launch Bundle', category: 'digital-products', type: 'DIGITAL', price: 15500, seller: 'brightpath-digital-academy',
    format: 'Curriculum planner + slide deck templates + sales page copy + launch calendar',
    contents: ['Curriculum planner mapping outcomes to lessons', 'Slide templates designed for teaching, not decorating', 'Sales page copy skeleton with fill-in prompts', 'Four-week launch calendar with daily actions'],
    audience: 'Experts packaging their knowledge into a first course',
    requirements: ['Word/PowerPoint or Google equivalents'],
    outcome: 'A course outline, deck and launch plan ready to build' },
  { name: 'Invoice & Bookkeeping Starter for SMEs', category: 'digital-products', type: 'DIGITAL', price: 7500, seller: 'brightpath-digital-academy',
    format: 'Invoice templates + income/expense ledger (Sheets/XLSX) + receivables tracker',
    contents: ['Invoice templates with VAT and discount logic', 'Cashbook ledger with automatic monthly summaries', 'Receivables tracker with ageing buckets', 'Simple chart of accounts for small businesses'],
    audience: 'SME owners doing their own books without an accountant yet',
    requirements: ['Excel or Google Sheets'],
    outcome: 'Books a future accountant will thank you for' },
  { name: 'Restaurant Operations Toolkit', category: 'digital-products', type: 'DIGITAL', price: 12500, seller: 'brightpath-digital-academy',
    format: 'Menu costing sheet + staff rota + inventory log + vendor tracker (XLSX)',
    contents: ['Plate costing that protects margin per menu item', 'Rota template with shift-cost visibility', 'Stock counts that catch shrinkage early', 'Vendor price tracker across market swings'],
    audience: 'Restaurant and cloud-kitchen owners formalising operations',
    requirements: ['Excel or Google Sheets'],
    outcome: 'Costed menu and controlled stock within one setup week' },
  { name: 'Real Estate Agent Digital Kit', category: 'digital-products', type: 'DIGITAL', price: 9500, seller: 'brightpath-digital-academy',
    format: 'Listing presentation template + inspection checklist + client tracker + social templates',
    contents: ['Listing presentation deck that wins mandates', 'Inspection checklist covering the questions buyers ask', 'Client pipeline tracker from lead to closing', 'Instagram story templates for new listings'],
    audience: 'Independent agents professionalising their process',
    requirements: ['PowerPoint/Sheets or Google equivalents'],
    outcome: 'A mandate-ready presentation and organised pipeline' },
  { name: 'Photography Editing Workflow Course', category: 'digital-education', type: 'DIGITAL', price: 15900, seller: 'brightpath-digital-academy',
    format: '28 lessons (MP4, 4 h) + workflow presets + client gallery guide',
    contents: ['Culling 2,000 photos down to 60 without regret', 'A repeatable edit order: crop, light, colour, skin', 'Client galleries that look professional and deliver fast', 'Backup routine that survives card failures'],
    audience: 'Event photographers drowning in unedited galleries',
    requirements: ['Lightroom Classic (free trial works)'],
    outcome: 'A gallery delivered in one focused evening, every time' },
  { name: 'Notion Real Estate CRM', category: 'digital-products', type: 'DIGITAL', price: 5500, seller: 'brightpath-digital-academy',
    format: 'Notion template (listings, clients, viewings, follow-ups) + walkthrough video',
    contents: ['Listings database with status pipeline', 'Client matching against live inventory', 'Viewing scheduler with reminder views', 'Follow-up sequences that never forget a lead'],
    audience: 'Agents and small agencies tracking deals in Notion',
    requirements: ['Free Notion account'],
    outcome: 'Every lead and listing in one system by tomorrow' },
  { name: 'Kids Coding with Scratch (Parent Guide)', category: 'digital-education', type: 'DIGITAL', price: 8500, seller: 'brightpath-digital-academy',
    format: '16 guided projects (PDF) + parent teaching notes + progress stickers',
    contents: ['Sixteen projects from animated cards to simple games', 'Teaching notes for parents who have never coded', 'Screen-time-friendly session plans of 30 minutes', 'Certificate template for finishing the set'],
    audience: 'Parents and guardians of ages 7–12',
    requirements: ['A laptop and the free Scratch website'],
    outcome: 'A child who can build and share their first game' },
  { name: 'Data Entry Efficiency Course', category: 'digital-education', type: 'DIGITAL', price: 6900, seller: 'brightpath-digital-academy',
    format: '18 lessons (MP4, 2.5 h) + typing drills + accuracy checklist',
    contents: ['Touch-typing plan from 20 to 50+ words per minute', 'Shortcuts that halve spreadsheet data entry', 'Validation and dropdowns that prevent errors at source', 'Speed without accuracy is worthless — drills balance both'],
    audience: 'VAs, data clerks and admin staff levelling up',
    requirements: ['A keyboard and patience'],
    outcome: 'Measurably faster, cleaner data entry with proof' },
  { name: 'Mini Importation Guide 2026', category: 'digital-education', type: 'DIGITAL', price: 11900, seller: 'brightpath-digital-academy',
    format: 'Guide (PDF, 90 pages) + supplier vetting checklist + landed-cost calculator',
    contents: ['Sourcing platforms and vetting suppliers without being burned', 'Landed cost math: freight, duties and realistic margins', 'Clearing agents and the paperwork that matters', 'First-order sizing: testing demand before bulk'],
    audience: 'First-time importers starting small',
    requirements: ['Starting budget from ₦150k recommended'],
    outcome: 'A vetted supplier shortlist and honest unit economics' },
];

export function applyWave3(items: SeedItem[]): SeedItem[] {
  return [...items, ...WAVE3_ITEMS];
}
