// ============================================================
// KOVA — Variant extensions (DEMO DATA ONLY)
// Real-world stores sell colourways, capacities, pack sizes and
// editions of the same product family. These tables add genuine
// variant SKUs to families from catalog-large.ts — every label
// is a real attribute of that product, priced sensibly.
// Merged into the items BEFORE expansion so seeds and the image
// generator stay in sync.
// ============================================================

import type { SeedItem } from './seed-data';

type FamilyKey = string; // `${seller}::${name}` — matches LARGE_ITEMS/ITEMS

/** Extra real-world variants appended to each family's own variants. */
const EXTRA_VARIANTS: Record<FamilyKey, string[]> = {
  // ── Alabi TechHub (needs +119) ──────────────────────────
  'alabi-techhub::Bluetooth Party Speaker': ['— Desert Sand Limited', '— Forest Green'],
  'alabi-techhub::USB-C 7-in-1 Hub': ['— 8-in-1 with Ethernet (₦19500)', '— 11-in-1 Pro Dock (₦28900)'],
  'alabi-techhub::1080p Streaming Webcam': ['— 2K Variant (₦31500)', '— Ring Light Bundle (₦27500)'],
  'alabi-techhub::Aluminium Laptop Stand': ['— With Phone Cradle (₦16900)', '— Standing Desk Riser (₦54900)'],
  'alabi-techhub::15W Wireless Charging Pad': ['— 3-in-1 Dock (₦22900)', '— MagSafe Grip Stand (₦16900)'],
  'alabi-techhub::Smart Wi-Fi Plug': ['— With Energy Monitoring (₦9500)', '— Outdoor IP44 (₦11500)'],
  'alabi-techhub::Fitness Activity Band': ['— Slim Edition', '— Kids Edition (₦12900)'],
  'alabi-techhub::Bluetooth FM Transmitter': ['— With QC3.0 Ports (₦11500)', '— Solar Window Model (₦13500)'],
  'alabi-techhub::Phone Gimbal Stabilizer': ['— Pocket Sized (₦32900)', '— Pro Payload 300g (₦61900)'],
  'alabi-techhub::USB Condenser Microphone': ['— With Boom Arm Studio Kit (₦42900)', '— Mini Desktop Version (₦18900)'],
  'alabi-techhub::Laptop Cooling Pad': ['— Slim Aluminium (₦15900)', '— With Phone Stand Cutout (₦13900)'],
  'alabi-techhub::Wireless Lavalier Microphone Set': ['— Camera Kit with Cold Shoe', '— Desktop Two-Person Pod (₦44900)'],
  'alabi-techhub::Smart Watch with Calling': ['— Rugged Outdoor Edition (₦44900)', '— Slim Fashion Edition (₦34900)'],
  'alabi-techhub::Magnetic Power Bank': ['— With Kickstand (₦26900)', '— 15000 mAh (₦42900)'],
  'alabi-techhub::HDMI 2.0 Cable': ['— 10 m Active (₦13500)', '— 8K 48Gbps 2 m (₦15500)'],
  'alabi-techhub::USB Card Reader': ['— USB-C Dual (₦6500)', '— Multi-Card Studio Reader (₦12900)'],
  'alabi-techhub::Office Headset with Boom Mic': ['— Wireless DECT (₦42900)', '— Binaural Double-Ear (₦24500)'],
  'alabi-techhub::Wi-Fi Range Extender': ['— Mesh Node Pair (₦27900)', '— AX1800 Wi-Fi 6 (₦26900)'],
  'alabi-techhub::Precision Stylus for Tablets': ['— Felt Nib Artist Tip', '— Case Bundle (₦19900)'],
  'alabi-techhub::Car Dash Camera': ['— 4K Front (₦48900)', '— 3-Channel Taxi Kit (₦58900)'],
  'alabi-techhub::Tablet Keyboard Folio Case': ['— With Trackpad (₦32900)', '— 11-inch Pro Fit'],
  'alabi-techhub::4G LTE Mobile Router': ['— With External Antenna Ports', '— Cat12 Dual SIM (₦84900)'],
  'alabi-techhub::Under-Desk Cable Management Tray': ['— Set of 2 (₦15900)', '— With Cable Sleeves (₦10500)'],
  'alabi-techhub::Travel Power Strip with USB': ['— With USB-C PD 30W (₦14900)', '— Surge 2000J Version (₦13500)'],
  'alabi-techhub::Bluetooth Audio Receiver for Home Stereos': ['— With Optical Out (₦16500)', '— Hi-Fi DAC Version (₦22900)'],
  'alabi-techhub::Mechanical Numpad Macro Pad': ['— Six-Key with 2 Knobs (₦22500)', '— Gateron Pre-Built'],
  'alabi-techhub::Wireless Noise-Cancelling Headphones': ['— Studio Reference Edition (₦78000)', '— Lite ANC (₦54000)'],
  // wave-3/4 family extras (variant extensions run last in the chain)
  'alabi-techhub::Robot Vacuum Cleaner': ['— With Self-Empty Station (₦138000)'],

  // ── Amara Luxe Atelier (surplus — keep small) ───────────
  'amara-luxe-atelier::Silk-Touch Headwrap Collection': ['— Maxwell Mesh'],

  // ── Zuri Home Living (needs +94) ────────────────────────
  'zuri-home-living::Ceramic Dinner Set (16-Piece)': ['— Dinner + Serving Platter (₦78500)', '— Breakfast Set 8pc (₦38500)'],
  'zuri-home-living::Seagrass Storage Baskets (Set of 3)': ['— With Lids (₦24500)', '— Single XXL (₦12500)'],
  'zuri-home-living::Arched Wall Mirror': ['— Full Length 70×170 (₦88500)', '— Entryway 50×120 (₦58500)'],
  'zuri-home-living::Ceramic Table Lamp with Linen Shade': ['— Pair (2 lamps) (₦68500)', '— Petite Bedside (₦28500)'],
  'zuri-home-living::Textured Throw Pillow Covers (Set of 2)': ['— Set of 4 (₦21500)', '— Lumbar 30×50 Pair (₦9500)'],
  'zuri-home-living::Washable Area Rug': ['— Runner 80×300 (₦42500)', '— Round Ø160 (₦49500)'],
  'zuri-home-living::Blackout Curtains (Pair)': ['— Lined Thermal Pair (₦38500)', '— Sheer Pairing Add-On (₦14500)'],
  'zuri-home-living::Percale Bedding Set': ['— Duvet Cover Only (₦24500)', '— Full Set + Duvet (₦59500)'],
  'zuri-home-living::Framed Abstract Print Set': ['— Triptych XL A1 (₦44500)', '— Single Statement A2 (₦16500)'],
  'zuri-home-living::Stoneware Vase Trio': ['— Statement Floor Vase (₦28500)', '— Bud Vase Quintet (₦22500)'],
  'zuri-home-living::Ladder Bookshelf': ['— Narrow Hallway (₦58500)', '— Wide 5-Tier Plus (₦98500)'],
  'zuri-home-living::Coffee Table with Storage': ['— Round Ø90 (₦88500)', '— Nesting Pair (₦118000)'],
  'zuri-home-living::Upholstered Dining Chair (Set of 2)': ['— Velvet Edition (₦98500/4)', '— Cane Back Set of 2 (₦94500)'],
  'zuri-home-living::Bedside Table with Drawer': ['— Two-Drawer (₦68500)', '— Floating Wall (₦48500)'],
  'zuri-home-living::TV Stand Console': ['— 180 cm Wide (₦138000)', '— Corner Unit (₦98500)'],
  'zuri-home-living::Wardrobe Organizer Set': ['— Full Wardrobe Bundle (₦24500)', '— Shoe Boxes 6pk (₦9500)'],
  'zuri-home-living::Airtight Kitchen Canister Set': ['— 5-Piece Pantry Tower (₦32500)', '— Single XL Flour (₦9500)'],
  'zuri-home-living::Upholstered Bar Stool': ['— Set of 2 (₦88500)', '— Oak Leg Edition (₦52500)'],
  'zuri-home-living::Tripod Floor Lamp': ['— With Shelf (₦58500)', '— Arc Overhead (₦88500)'],
  'zuri-home-living::Silent Wall Clock': ['— Ø 40 cm Oversize (₦16500)', '— Double-Sided Station Clock (₦24500)'],
  'zuri-home-living::Under-Sink Organizer Rack': ['— Two-Tier Stack (₦14500)', '— Pull-Out Basket (₦12500)'],
  'zuri-home-living::Woven Pendant Light Shade': ['— Double Bulb Wide (₦24500)', '— Cluster of 3 (₦42500)'],
  'zuri-home-living::Upholstered Accent Armchair': ['— With Ottoman (₦168000)', '— Petite Nursery (₦74500)'],
  'zuri-home-living::Storage Ottoman Bench': ['— With Tray Top (₦59500)', '— Twin Entry Pair (₦68500)'],

  // ── Wellspring Wellness Co. (needs +131) ────────────────
  'wellspring-wellness-co::Non-Slip Yoga Mat': ['— Pro 8mm with Alignment (₦19500)', '— Travel Foldable (₦11500)'],
  'wellspring-wellness-co::Resistance Bands Set': ['— Fabric Booty Bands 3pk (₦8500)', '— Heavy Pull-Up Assist (₦14500)'],
  'wellspring-wellness-co::Neoprene Dumbbell Pair': ['— 2 × 8 kg (₦28500)', '— Ajustable Pair 2-20kg (₦68500)'],
  'wellspring-wellness-co::Textured Foam Roller': ['— Travel Hollow 45cm (₦13500)', '— Vibrating Recovery (₦48500)'],
  'wellspring-wellness-co::Weighted Jump Rope': ['— Speed Rope 1.5mm (₦8500)', '— Beaded Rhythm Rope (₦6500)'],
  'wellspring-wellness-co::Insulated Stainless Bottle': ['— Flask with Straw Lid (₦15500)', '— Sports Squeeze 650ml (₦9500)'],
  'wellspring-wellness-co::Herbal Tea Sampler Tin': ['— Immunity Five (₦9500)', '— Sleep & Calm Duo (₦6500)'],
  'wellspring-wellness-co::Percussion Massage Gun': ['— Deep Tissue 12mm (₦52900)', '— Warm-Head Attachment Kit (₦8500)'],
  'wellspring-wellness-co::Ultrasonic Aroma Diffuser': ['— With Oils Trio (₦23500)', '— Car USB Diffuser (₦6500)'],
  'wellspring-wellness-co::Pilates Ring & Ball Kit': ['— With Booty Band (₦14500)', '— Ring Only (₦9500)'],
  'wellspring-wellness-co::Shea Body Butter': ['— Gift Trio Jar Set (₦18500)', '— Travel 100g (₦3500)'],
  'wellspring-wellness-co::Roll-On Fragrance Oil': ['— Perfumer Trio Discovery (₦15500)', '— 25 ml Statement (₦12500)'],
  'wellspring-wellness-co::Beard Conditioning Oil': ['— Full Beard Kit with Comb (₦11500)', '— Beard Balm Tin (₦6500)'],
  'wellspring-wellness-co::Lip Balm Trio': ['— Holiday Gift Box (₦6500)', '— Single Stick (₦1800)'],
  'wellspring-wellness-co::Sugar Body Scrub': ['— Coffee Coconut 500g (₦9500)', '— Foot Scrub Peppermint (₦5500)'],
  'wellspring-wellness-co::Hair & Scalp Oil Blend': ['— Growth Kit with Cap (₦12500)', '— Braid Spray 250ml (₦5500)'],
  'wellspring-wellness-co::Facial Steamer': ['— With Towel Warmer (₦24500)', '— Nano Mister Handheld (₦9500)'],
  'wellspring-wellness-co::Vegan Makeup Brush Set': ['— 5-Piece Starter (₦7500)', '— 15-Piece Pro + Stand (₦19500)'],
  'wellspring-wellness-co::Eau de Parfum (50 ml)': ['— Discovery Set 3×2ml (₦6500)', '— Layering Duo 2×30ml (₦38500)'],
  'wellspring-wellness-co::Manicure & Pedicure Kit': ['— Pro File + Buffing Add-On (₦12500)', '— Travel Mini 6pc (₦5500)'],
  'wellspring-wellness-co::Cork Massage Ball Pair': ['— Single Firm 10cm (₦3500)', '— Triple Therapy Set (₦9500)'],
  'wellspring-wellness-co::Collapsible Foam Roller (Travel)': ['— With Massage Grid (₦11500)', '— Doorway Stretch Strap (₦7500)'],
  'wellspring-wellness-co::Cleansing Balm': ['— Fragrance Free', '— Mini Travel 30ml (₦3500)'],
  'wellspring-wellness-co::Bamboo Charcoal Soap (Set of 3)': ['— Single Bar', '— Family Dozen (₦12500)'],
  'wellspring-wellness-co::Sleep Mask & Earplug Kit': ['— Silk Mask Only (₦5500)', '— Blackout Bundle (₦8500)'],

  // ── Brightpath Digital Academy (needs +141) ─────────────
  'brightpath-digital-academy::Excel From Zero to Dashboards': ['— Excel + Power BI Combo (₦24900)', '— Team Licence 5 Seats (₦52500)'],
  'brightpath-digital-academy::Data Analysis with Python Bootcamp': ['— Data Track Full (₦44900)', '— Weekend Intensive Cohort (₦39900)'],
  'brightpath-digital-academy::UI/UX Design Fundamentals': ['— Advanced Patterns Course (₦24900)', '— Design + Portfolio Bundle (₦39900)'],
  'brightpath-digital-academy::Canva for Small Business': ['— With Brand Kit Service (₦18500)', '— Social Content Pack (₦12500)'],
  'brightpath-digital-academy::Digital Marketing Foundations': ['— With Paid Ads Lab (₦24900)', '— Team Training 5 Seats (₦59900)'],
  'brightpath-digital-academy::Freelancing 101: Land Your First Client': ['— With Client Pipeline CRM (₦16500)', '— Pricing Masterclass (₦9500)'],
  'brightpath-digital-academy::Video Editing with CapCut & Premiere': ['— Colour Grading Module (₦12500)', '— Creator Bundle with LUTs (₦22900)'],
  'brightpath-digital-academy::Full-Stack Web Development Track': ['— Frontend Specialization (₦29900)', '— Career Track + Mentorship (₦98900)'],
  'brightpath-digital-academy::Copywriting that Converts': ['— Email Funnels Module (₦9500)', '— Landing Page Teardown Library (₦7500)'],
  'brightpath-digital-academy::Personal Finance for Nigerians': ['— With Investing Basics (₦14500)', '— Couples Finance Edition (₦12500)'],
  'brightpath-digital-academy::Product Management Foundations': ['— With Agile Delivery Module (₦24900)', '— Interview Drill Cohort (₦19900)'],
  'brightpath-digital-academy::Cybersecurity Essentials for Teams': ['— With Phishing Sim Kit (₦19900)', '— Individual Edition (₦8500)'],
  'brightpath-digital-academy::CV & Interview Toolkit': ['— LinkedIn Optimisation Add-On (₦8500)', '— Graduate Starter (₦4500)'],
  'brightpath-digital-academy::Business Plan & Pitch Deck Templates': ['— Grant Application Pack (₦12500)', '— Financial Model Pro (₦14500)'],
  'brightpath-digital-academy::Social Media Content Calendar System': ['— With 360 Hook Bank (₦8500)', '— Agency Multi-Brand (₦14500)'],
  'brightpath-digital-academy::Professional CV Template Pack': ['— Creative Fields Pack (₦5500)', '— Executive Suite (₦7500)'],
  'brightpath-digital-academy::Lightroom Preset Collection': ['— Portrait Skin Pro (₦9500)', '— Creator Complete Library (₦16500)'],
  'brightpath-digital-academy::Invoice & Receipt Template Pack': ['— With VAT Ledger Sheet (₦5500)', '— Business Starter Docs (₦7500)'],
  'brightpath-digital-academy::Startup Pitch Deck Bundle': ['— Fintech Examples (₦15500)', '— Demo Day Polish Service (₦34900)'],
  'brightpath-digital-academy::Ebook: Start Selling Online in 30 Days': ['— With Launch Checklist Kit (₦7500)', '— Audiobook Edition (₦6500)'],
  'brightpath-digital-academy::Digital Study Planner (Undated)': ['— JAMB/WAEC Special (₦3000)', '— Postgraduate Research (₦3500)'],
  'brightpath-digital-academy::Monthly Budget Spreadsheet': ['— Household Edition (₦4000)', '— Freelancer Tax Prep (₦5500)'],
  'brightpath-digital-academy::Brand Guidelines Template': ['— With Canva Workshop (₦11500)', '— Startup Lite (₦5500)'],
  'brightpath-digital-academy::Notion Second Brain OS': ['— Student Edition (₦4500)', '— With GTD Course (₦12500)'],
  // wave-3/4 family extras (variant extensions run last in the chain)
  'brightpath-digital-academy::Kids Coding with Scratch (Parent Guide)': ['— Classroom 10 Licence (₦49900)', '— With Tutor Support (₦12500)'],
  'brightpath-digital-academy::Mini Importation Guide 2026': ['— With Supplier List Access (₦16900)', '— Group Buying Cohort (₦19900)'],
  'brightpath-digital-academy::Data Entry Efficiency Course': ['— With Typing Certificate (₦9500)'],
  'brightpath-digital-academy::Email Marketing Playbook': ['— With ESP Setup Service (₦14900)'],
  'brightpath-digital-academy::Presentation Design Masterclass': ['— With Slide Audit (₦16900)'],
  'brightpath-digital-academy::Photography Editing Workflow Course': ['— With Culling Workshop (₦19900)'],
  'brightpath-digital-academy::Freelance Web Developer Starter Kit': ['— With Website Review (₦12500)'],
  'brightpath-digital-academy::Study Skills & Exam Technique Course': ['— With Weekly Check-in Cohort (₦12500)'],
  'brightpath-digital-academy::WhatsApp Business Selling System': ['— With Catalogue Setup Service (₦12900)'],
  // target low-variant families (expansion caps at 8 per family)
  'brightpath-digital-academy::Interview Preparation Cohort (Live)': ['— Tech Roles Focus (₦32900)', '— Graduate Edition (₦24900)', '— With CV Rewrite Session (₦35900)'],
  'brightpath-digital-academy::Shopify & WooCommerce Launch Course': ['— With Theme Setup Service (₦22900)', '— Multi-Currency Edition (₦19900)', '— With Product Photography Lab (₦18900)'],
  'brightpath-digital-academy::Notion Client Portal Template': ['— With Onboarding Video Series (₦9500)', '— Agency Multi-Client (₦12500)', '— With Invoice Automation (₦11500)'],
  'alabi-techhub::Graphics Tablet (Drawing Pad)': ['— Left-Handed Express Keys'],
};

/**
 * Second-wave families for sellers still below the 200-product floor
 * after EXTRA_VARIANTS are applied. Distinct real products — not
 * duplicates of existing rows.
 */
export const WAVE2_ITEMS: SeedItem[] = [
  // ── Alabi TechHub — printers, projectors, monitors, accessories ──────
  { name: 'Portable Inkless Thermal Printer', category: 'electronics', type: 'PHYSICAL', price: 34500, seller: 'alabi-techhub',
    material: 'ABS shell, direct thermal mechanism', dimensions: '24 × 8 × 5 cm; A4 via roll feed',
    colours: ['White', 'Mint'],
    features: ['Prints receipts, labels and documents without ink refills', 'Bluetooth and USB-C for phones and laptops', '1000 mAh battery prints ~150 pages per charge', 'Uses affordable 210 mm thermal rolls'],
    includes: ['Thermal roll', 'USB-C cable', 'Pouch'] },
  { name: 'Mini LED Projector', category: 'electronics', type: 'PHYSICAL', price: 48500, seller: 'alabi-techhub',
    material: 'Matte shell, glass lens', dimensions: '17 × 13 × 8 cm; 100 ANSI lumens',
    colours: ['White', 'Black'],
    namedVariants: ['— 1080p Native (₦78500)', '— With Tripod (₦54500)'],
    features: ['Projects a 40–120 inch picture for movie nights and huddles', 'HDMI and USB inputs handle decoders, sticks and drives', 'Built-in speaker with a 3.5 mm out for bigger sound', 'Keystone correction squares the image from an angle'],
    includes: ['Remote', 'HDMI cable', 'Power adapter'] },
  { name: '24-Inch IPS Monitor 75Hz', category: 'electronics', type: 'PHYSICAL', price: 89500, seller: 'alabi-techhub',
    material: 'IPS panel, slim bezel, VESA 100 back', dimensions: '24" FHD 1920×1080, 75 Hz, 5 ms',
    colours: ['Black'],
    namedVariants: ['— 27" QHD 100Hz (₦158000)', '— 24" 100Hz Frameless (₦98500)'],
    features: ['IPS colour holds up from side angles for shared desks', '75 Hz over HDMI makes scrolling visibly smoother', 'Flicker-free and low-blue-light modes for long days', 'VESA mount ready for arms and walls'],
    includes: ['HDMI cable', 'Power brick'] },
  { name: 'Monitor Light Bar', category: 'electronics', type: 'PHYSICAL', price: 18900, seller: 'alabi-techhub',
    material: 'Aluminium bar, asymmetric optic', dimensions: '45 cm bar; fits screens 1–6 cm thick',
    colours: ['Space Grey', 'White'],
    features: ['Lights the desk, not the screen — no glare or reflections', 'Stepless warmth from cool work light to warm evening', 'USB powered from the monitor or laptop', 'Saves the desk space a lamp arm takes'],
    includes: ['USB-A cable', 'Counterweight clip'] },
  { name: 'Laptop Sleeve with Accessory Pocket', category: 'electronics', type: 'PHYSICAL', price: 8500, seller: 'alabi-techhub',
    material: 'Water-repellent polyester, plush lining', dimensions: 'Fits 13–14" (also 15.6")',
    colours: ['Charcoal', 'Navy', 'Burgundy'],
    namedVariants: ['— 13/14"', '— 15.6" (₦9500)'],
    features: ['Corner-protected plush interior absorbs commuter knocks', 'Front pocket swallows charger, mouse and cables', 'Water-repellent shell shrugs off harmattan drizzle', 'Slim enough to slide into a backpack or tote'],
  },
  { name: 'Ethernet Cable Cat 6', category: 'electronics', type: 'PHYSICAL', price: 4500, seller: 'alabi-techhub',
    material: 'Pure copper core, snagless boots', dimensions: 'Three lengths; 1 Gbps rated',
    colours: ['Grey', 'Blue'],
    namedVariants: ['— 1 m', '— 3 m (₦6500)', '— 10 m (₦11500)'],
    features: ['Gigabit speeds for consoles, routers and smart TVs', 'Snagless boots survive repeated plugging', 'Pure copper conductors, not CCA imitations', 'Flexible jacket routes cleanly along skirting'],
  },
  { name: 'USB Desk Fan (Quiet)', category: 'electronics', type: 'PHYSICAL', price: 9500, seller: 'alabi-techhub',
    material: 'ABS blades, metal neck', dimensions: 'Ø 15 cm head; 1.5 m USB cable',
    colours: ['White', 'Black', 'Sage'],
    namedVariants: ['— Rechargeable (₦12500)', '— Clip-On Version (₦10500)'],
    features: ['Three speeds with a genuinely quiet low setting', 'Adjustable metal neck aims the breeze', 'USB powered from any adapter or power bank', 'Removable front grill for cleaning'],
  },
  { name: ' Bluetooth 5.3 Audio Transmitter', category: 'electronics', type: 'PHYSICAL', price: 12500, seller: 'alabi-techhub',
    material: 'Matte shell, aptX support', dimensions: '5 × 3 × 1 cm; USB-C or 3.5 mm',
    colours: ['Black'],
    features: ['Adds Bluetooth to gym equipment, planes and old consoles', 'aptX Low Latency keeps video lipsynced', 'Pairs with two headphones for shared listening', 'Runs 12 hours per charge'],
  },
  { name: 'Wireless Presentation Clicker', category: 'electronics', type: 'PHYSICAL', price: 8500, seller: 'alabi-techhub',
    material: 'Rubberised body, red laser', dimensions: 'Pen format; 2.4 GHz plug',
    colours: ['Black', 'Red'],
    features: ['Advances slides from across the hall at 2.4 GHz', 'Red laser for pointing at exactly the wrong number', 'Stores the receiver inside the barrel', 'Plug-and-play — no software on the presentation laptop'],
    includes: ['AAA battery'] },
  { name: 'Magnetic Cable Clips (6-Pack)', category: 'electronics', type: 'PHYSICAL', price: 3500, seller: 'alabi-techhub',
    material: 'ABS clip, foam adhesive pads', dimensions: 'Slots for cables up to 7 mm',
    colours: ['Black', 'White'],
    features: ['Keeps charge cables exactly where your hand expects them', 'Foam pads hold on painted desks and nightstands', 'Six clips cover bed, desk, car and lounge', 'Weighted magnetic bases reposition without residue'],
  },
  { name: 'Phone Stand with Charging Port Cutout', category: 'electronics', type: 'PHYSICAL', price: 5500, seller: 'alabi-techhub',
    material: 'Aluminium with silicone pads', dimensions: 'Folds flat to 1 cm; fits phones and mini tablets',
    colours: ['Space Grey', 'Silver', 'Blush'],
    features: ['Adjustable viewing angles from 30° to 120°', 'Charging cable routes through the base while docked', 'Silicone pads stop slips and scratches', 'Solid alloy does not wobble when tapping the screen'],
  },
  { name: 'AA/AAA Battery Charger + 8 Batteries', category: 'electronics', type: 'PHYSICAL', price: 12900, seller: 'alabi-techhub',
    material: 'Fire-retardant housing, NiMH cells included', dimensions: 'Charges 8 cells; USB-C input',
    colours: ['Black'],
    features: ['Refills remotes, mice and keyboards instead of binning cells', 'Overcharge protection with per-slot status LEDs', 'NiMH batteries arrive ready and keep 80% charge for a year', 'Charges mixed AA and AAA slots at once'],
    includes: ['4 × AA + 4 × AAA NiMH', 'USB-C cable'] },
  { name: 'Desktop CNC-Cut Cable Organizer', category: 'electronics', type: 'PHYSICAL', price: 7500, seller: 'alabi-techhub',
    material: 'Bamboo board with silicone channels', dimensions: '20 × 8 × 2 cm; six channels',
    colours: ['Bamboo'],
    features: ['Weights the cable spaghetti flat along the desk edge', 'Silicone channels grip without marking jacketing', 'Bamboo matches wooden desk setups', 'Anti-slip base stays put while unplugging one cable'],
  },
  { name: 'Echo-Reducing Desk Microphone Arm', category: 'electronics', type: 'PHYSICAL', price: 15500, seller: 'alabi-techhub',
    material: 'Steel springs, alloy clamp', dimensions: 'Reach 80 cm; fits 5/8" and 3/8" threads',
    colours: ['Black'],
    features: ['Suspends the mic off the desk to cut keyboard thumps', 'Hidden spring channels and cable routing clips', 'Desk clamp protects surfaces with a cork pad', 'Holds broadcast mics up to 1.2 kg'],
  },
  { name: 'LED Ring Light with Stand', category: 'electronics', type: 'PHYSICAL', price: 22500, seller: 'alabi-techhub',
    material: 'Aluminium ring, tripod stand', dimensions: 'Ø 26 cm; stand 50–160 cm',
    colours: ['White'],
    namedVariants: ['— 26 cm Bi-Color', '— 33 cm Pro with Remote (₦29500)'],
    features: ['Three warmth settings × ten brightness steps for clean video light', 'Phone holder sits inside the ring for even face lighting', 'Tripod extends to standing-eye height', 'Bluetooth shutter button fires the camera remotely'],
    includes: ['Phone holder', 'Bluetooth remote', 'Carry bag'] },

  // ── Zuri Home Living — kitchen, bedding, storage, decor ──────────────
  { name: 'Cast Iron Skillet', category: 'interior-home', type: 'PHYSICAL', price: 18500, seller: 'zuri-home-living',
    material: 'Pre-seasoned cast iron', dimensions: 'Ø 26 cm (also 20 cm); 2.1 kg',
    colours: ['Matte Black'],
    namedVariants: ['— Ø 20 cm (₦13500)', '— Ø 30 cm with Lid (₦29500)'],
    features: ['Pre-seasoned surface starts naturally non-stick and improves with use', 'Oven, grill and campfire safe — one pan for every heat source', 'Pour spouts on both sides for draining fat', 'Will outlive every non-stick pan in the kitchen'],
    care: 'Hand wash, dry immediately, wipe with a little oil.' },
  { name: 'Bamboo Chopping Board Set', category: 'interior-home', type: 'PHYSICAL', price: 12500, seller: 'zuri-home-living',
    material: 'End-grain bamboo, juice groove', dimensions: 'L 38 cm, M 30 cm, S 23 cm',
    colours: ['Natural Bamboo'],
    features: ['Three boards separate raw meat, veg and bread honestly', 'Juice grooves catch runoff before it reaches the counter', 'Gentle on knife edges compared to glass or stone', 'Integrated handles hang for drying'],
    care: 'Hand wash; oil monthly with food-grade mineral oil.' },
  { name: 'Stainless Steel Mixing Bowl Set', category: 'interior-home', type: 'PHYSICAL', price: 15500, seller: 'zuri-home-living',
    material: '18/8 stainless, non-slip silicone bases', dimensions: '1.5 / 3 / 5 L nesting trio',
    colours: ['Steel'],
    features: ['Nesting trio covers whisking, tossing and dough without a cupboard of singles', 'Silicone bases grip marble and granite counters', 'Tight-fitting lids included for marinating and storage', 'Dishwasher safe and unbreakable in real kitchens'],
    includes: ['3 lids'] },
  { name: 'Ceramic Utensil Holder', category: 'interior-home', type: 'PHYSICAL', price: 8500, seller: 'zuri-home-living',
    material: 'Glazed stoneware, weighted base', dimensions: 'H 18 cm; Ø 14 cm',
    colours: ['Matte White', 'Speckled Grey', 'Terracotta'],
    features: ['Weighted base does not tip when loaded with heavy tools', 'Glazed interior rinses clean of drips', 'Wide mouth fits whisks, spatulas and tongs together', 'Doubles as a wine cooler on the counter'],
  },
  { name: 'Pull-Out Pantry Baskets (2-Pack)', category: 'interior-home', type: 'PHYSICAL', price: 11500, seller: 'zuri-home-living',
    material: 'Coated steel mesh with handles', dimensions: '42 × 30 × 18 cm each',
    colours: ['White', 'Bronze'],
    features: ['Slide-out baskets make deep shelves reachable', 'Handles pull even when fully loaded with tins', 'Mesh shows contents at a glance', 'Stacks two-high for vertical shelves'],
  },
  { name: 'Quilted Bedspread Set', category: 'interior-home', type: 'PHYSICAL', price: 39500, seller: 'zuri-home-living',
    material: 'Microfiber quilt with cotton fill', dimensions: 'King 240 × 260 cm (also Queen)',
    colours: ['Ivory', 'Sage', 'Graphite'],
    namedVariants: ['— King', '— Queen (₦34500)'],
    features: ['Lightweight warmth for AC bedrooms without duvet bulk', 'Quilting holds fill evenly through washes', 'Two shams included, same dye lot', 'Pre-washed soft, not stiff out of the bag'],
    includes: ['Bedspread', '2 shams'] },
  { name: 'Floating Wall Shelves (Set of 3)', category: 'furniture', type: 'PHYSICAL', price: 19500, seller: 'zuri-home-living',
    material: 'Engineered wood with hidden brackets', dimensions: '60 cm, 45 cm, 30 cm lengths; 20 cm deep',
    colours: ['Walnut Look', 'White', 'Oak Look'],
    features: ['Hidden brackets give the floating look without sagging', 'Holds 8 kg per shelf when anchored properly', 'Three lengths compose a staggered gallery wall', 'Anchors and screws included and pre-sorted'],
    includes: ['Wall anchors', 'Screw kit'] },
  { name: 'Accent Console Table', category: 'furniture', type: 'PHYSICAL', price: 68500, seller: 'zuri-home-living',
    material: 'Solid wood top, powder-coated frame', dimensions: '100 × 35 × 80 cm',
    colours: ['Walnut/Black', 'Natural/Brass'],
    features: ['Slim 35 cm depth fits hallways behind a sofa', 'Open lower shelf for baskets or books', 'Levelling feet tame uneven floors', 'Assembles with six bolts and the included key'],
    leadTime: 'Made to order — dispatches in 5–7 working days.' },
  { name: 'Ottoman Storage Pouf', category: 'furniture', type: 'PHYSICAL', price: 42500, seller: 'zuri-home-living',
    material: 'Linen-look upholstery, storage core', dimensions: 'Ø 45 × H 45 cm; holds ~60 L',
    colours: ['Oat', 'Charcoal', 'Mustard'],
    features: ['Stows blankets, toys or the cable graveyard out of sight', 'Firm lid seats one adult comfortably', 'Stitched piping holds shape after a year of use', 'Doubles as a footrest or extra seat when guests land'],
  },
  { name: 'Vanity Mirror with LED', category: 'interior-home', type: 'PHYSICAL', price: 29500, seller: 'zuri-home-living',
    material: 'Glass, alloy frame, LED halo', dimensions: 'Ø 40 cm; touch dimmer',
    colours: ['White', 'Black'],
    features: ['Three light temperatures reproduce daylight, office and evening', 'Touch dimmer remembers the last setting', '10× magnifying spot mirror swivels from the side', 'Tilts on a weighted stand or wall-mounts'],
  },
  { name: 'Linen Curtain Panels (Pair)', category: 'interior-home', type: 'PHYSICAL', price: 28500, seller: 'zuri-home-living',
    material: 'Washed linen-blend, rod-pocket top', dimensions: 'Each 130 × 240 cm',
    colours: ['Natural Flax', 'Dusty Rose', 'Slate'],
    features: ['Washed linen drapes with an easy, lived-in fold', 'Filters light softly while keeping daytime privacy', 'Rod-pocket or back-tab hanging for either rod style', 'Hems are stitched, not glued'],
  },
  { name: 'Entryway Coat Rack', category: 'furniture', type: 'PHYSICAL', price: 32500, seller: 'zuri-home-living',
    material: 'Solid rubberwood pole, alloy hooks', dimensions: 'H 175 cm; 8 hooks; weighted base',
    colours: ['Natural', 'Espresso'],
    features: ['Weighted base stays upright loaded with bags and coats', 'Eight hooks at two heights for adults and children', 'Base doubles as a shoe rest while lacing up', 'Assembles in five minutes with two bolts'],
  },

  // ── Wellspring — recovery, nutrition, personal care ─────────────────
  { name: 'Foam Massage Ball (Spiky)', category: 'health-wellness', type: 'PHYSICAL', price: 4500, seller: 'wellspring-wellness-co',
    material: 'PVC spiky shell, hollow core', dimensions: 'Ø 10 cm',
    colours: ['Lime', 'Rose', 'Slate'],
    features: ['Spikes wake up flat feet before long standing days', 'Targets plantar fascia and forearm knots precisely', 'Inflates with the included needle pump for firmness control', 'Pocket sized for desk drawers and gym bags'],
  },
  { name: 'Hip Resistance Circle (Fabric)', category: 'health-wellness', type: 'PHYSICAL', price: 6500, seller: 'wellspring-wellness-co',
    material: 'Non-slip fabric weave', dimensions: 'Ø 33 cm; three resistances',
    colours: ['Sage Set', 'Blush Set'],
    namedVariants: ['— 3-Band Set', '— Single Heavy'],
    features: ['Fabric weave grips leggings instead of rolling into a band', 'Three resistances progress glute and hip work', 'Stitched seams survive thousands of stretches', 'Comes with a printed five-move starter circuit'],
  },
  { name: 'Hand Grip Strengthener (Adjustable)', category: 'health-wellness', type: 'PHYSICAL', price: 5500, seller: 'wellspring-wellness-co',
    material: 'Alloy spring, ribbed handles', dimensions: '10–60 kg adjustable',
    colours: ['Black', 'Red'],
    features: ['Dial resistance from rehab-light to grip-sport heavy', 'Counts repetitions on the built-in tally window', 'Ribbed handles stay put when palms sweat', 'Fits both large and small hands comfortably'],
  },
  { name: 'Protein Shaker Bottle (Insulated)', category: 'health-wellness', type: 'PHYSICAL', price: 7500, seller: 'wellspring-wellness-co',
    material: 'Double-wall stainless, leak lid', dimensions: '700 ml; fits cup holders',
    colours: ['Matte Black', 'Steel', 'Sage'],
    features: ['Stainless walls hold cold through a two-hour gym session', 'Mixing grid blends powder without clumps', 'Twist lid seals in gym bags — tested upside down', 'Wide mouth takes a full scoop without funnels'],
  },
  { name: 'Digital Body Weight Scale', category: 'health-wellness', type: 'PHYSICAL', price: 9500, seller: 'wellspring-wellness-co',
    material: 'Tempered glass over alloy sensors', dimensions: '30 × 30 cm; 180 kg max; 50 g steps',
    colours: ['Clear Glass', 'Black Glass'],
    features: ['Reads in 50 g steps — useful for real progress tracking', 'Auto-calibrates to zero each time it wakes', 'Large backlit digits readable without spectacles', 'Units switch between kg, lb and st for the family'],
  },
  { name: 'Bath Salts Recovery Blend', category: 'beauty-perfumes', type: 'PHYSICAL', price: 6500, seller: 'wellspring-wellness-co',
    material: 'Epsom salt, dried hibiscus, eucalyptus oil', dimensions: '500 g resealable pouch',
    colours: ['Eucalyptus Recovery', 'Hibiscus Relax'],
    features: ['Two scoops turn a bath into an after-training soak', 'Resealable pouch keeps the salts from clumping', 'Real dried botanicals, not synthetic confetti', 'No dyes — the colour comes from the hibiscus'],
  },
  { name: 'Konjac Facial Sponge (2-Pack)', category: 'beauty-perfumes', type: 'PHYSICAL', price: 3500, seller: 'wellspring-wellness-co',
    material: 'Natural konjac root fiber', dimensions: 'Ø 7 cm each',
    colours: ['Natural', 'Charcoal'],
    features: ['Softens into a cloud after 3 minutes in water', 'Charcoal variant suits oilier skin days', 'Compostable at end of life', 'Two sponges rotate through weekly deep cleans'],
  },
  { name: 'Wide-Tooth Detangling Comb', category: 'beauty-perfumes', type: 'PHYSICAL', price: 3000, seller: 'wellspring-wellness-co',
    material: 'Seamless resin teeth', dimensions: '22 cm; detachable pick end',
    colours: ['Blush', 'Black'],
    features: ['Seamless teeth do not snap strands like moulded-seam combs', 'Two densities: wide for sectioning, medium for length', 'Detachable pick handles parting and styling', 'Survives being sat on in a handbag'],
  },
  { name: 'Cleansing Balm', category: 'beauty-perfumes', type: 'PHYSICAL', price: 8500, seller: 'wellspring-wellness-co',
    material: 'Shea, castor and sunflower oils', dimensions: '100 ml jar with spatula',
    features: ['Melts sunscreen and city grime without stripping', 'Emulsifies with water and rinses clean, no film', 'Comes with a tidy spatula — no finger-dipping', 'Fragrance-free option for sensitive skin'],
  },
  { name: 'Bamboo Charcoal Soap (Set of 3)', category: 'beauty-perfumes', type: 'PHYSICAL', price: 4500, seller: 'wellspring-wellness-co',
    material: 'Cold-processed soap, activated charcoal', dimensions: '3 × 100 g bars',
    colours: ['Charcoal', 'Charcoal + Shea'],
    features: ['Cold-process bars cure six weeks for a hard, long life', 'Charcoal suits post-gym and city-day deep cleans', 'Cures out gentle — no tight, squeaky aftermath', 'Paper-wrapped bars, no plastic'],
  },
  { name: 'Sleep Mask & Earplug Kit', category: 'health-wellness', type: 'PHYSICAL', price: 6500, seller: 'wellspring-wellness-co',
    material: 'Mulberry silk mask, foam plugs', dimensions: 'One size mask; 5 plug pairs',
    colours: ['Charcoal', 'Navy', 'Blush'],
    features: ['Contoured silk mask cups eyes without lash pressure', 'Memory-foam plugs in five sizes for a real fit', 'Adjustable strap skips hair tangles', 'Case keeps the kit together in a travel bag'],
  },

  // ── Brightpath — course & template expansion ────────────────────────
  { name: 'Interview Preparation Cohort (Live)', category: 'digital-education', type: 'DIGITAL', price: 29900, seller: 'brightpath-digital-academy',
    namedVariants: ['— Standard Cohort', '— Tech Roles Focus (₦32900)', '— Graduate Edition (₦24900)', '— With CV Rewrite Session (₦35900)'],
    format: '4 live sessions (recorded, 2 h each) + cohort Slack + mock interviews',
    contents: ['Live mock interviews with written feedback', 'Story bank building workshop for STAR answers', 'Take-home exercise drills with review', 'Offer and salary negotiation session'],
    audience: 'Candidates with interviews scheduled in the next two months',
    requirements: ['A specific role target and a working webcam'],
    outcome: 'Walk into interviews with rehearsed, feedback-tuned answers' },
  { name: 'Freelance Web Developer Starter Kit', category: 'digital-products', type: 'DIGITAL', price: 9500, seller: 'brightpath-digital-academy',
    format: 'Contract templates (DOCX) + proposal deck (PPTX) + client onboarding checklist (PDF) + pricing calculator (XLSX)',
    contents: ['Plain-language contract protecting scope and payment', 'Proposal deck that walks clients to a yes', 'Onboarding checklist covering access, assets and kickoff', 'Pricing calculator with Nigerian market rate bands'],
    audience: 'Developers moving from per-gig to structured client work',
    requirements: ['Word/PowerPoint/Excel or Google equivalents'],
    outcome: 'Client-ready paperwork from the first enquiry' },
  { name: 'Shopify & WooCommerce Launch Course', category: 'digital-education', type: 'DIGITAL', price: 17900, seller: 'brightpath-digital-academy',
    namedVariants: ['— Self-Paced', '— With Theme Setup Service (₦22900)', '— Multi-Currency Edition (₦19900)', '— With Product Photography Lab (₦18900)'],
    format: '32 lessons (MP4, 5 h) + theme setup checklist + product photography guide (PDF)',
    contents: ['Store setup the right way around: payments before themes', 'Product pages that answer the questions buyers actually ask', 'Local delivery and pickup options configured properly', 'Abandoned-cart recovery without paid apps'],
    audience: 'Sellers moving from WhatsApp and Instagram to a real storefront',
    requirements: ['A store plan and product photos (guide included)'],
    outcome: 'A launched store with test orders completed end to end' },
  { name: 'Presentation Design Masterclass', category: 'digital-education', type: 'DIGITAL', price: 11500, seller: 'brightpath-digital-academy',
    format: '22 lessons (MP4, 3.5 h) + 50 editable slide layouts (PPTX/Slides)',
    contents: ['Slide architecture: one idea per slide, proven with examples', 'Charts that stay legible when projected', 'Typography and alignment systems for non-designers', 'Delivering to a room and to a camera'],
    audience: 'Professionals presenting to boards, clients and classes',
    requirements: ['PowerPoint or Google Slides'],
    outcome: 'A deck you are not ashamed to present next week' },
  { name: 'Email Marketing Playbook', category: 'digital-education', type: 'DIGITAL', price: 9500, seller: 'brightpath-digital-academy',
    format: '20 lessons (MP4, 3 h) + 12 email templates + deliverability checklist',
    contents: ['List building without buying shady contacts', 'Welcome, nurture and launch sequences pre-written for editing', 'Deliverability: SPF, DKIM and the settings that matter', 'Metrics that predict revenue, not vanity opens'],
    audience: 'Small brands starting email without an agency',
    requirements: ['Any email platform (examples use free tiers)'],
    outcome: 'A running email programme with a growing, engaged list' },
  { name: 'Notion Client Portal Template', category: 'digital-products', type: 'DIGITAL', price: 6500, seller: 'brightpath-digital-academy',
    namedVariants: ['— Standard Portal', '— With Onboarding Video Series (₦9500)', '— Agency Multi-Client (₦12500)', '— With Invoice Automation (₦11500)'],
    format: 'Notion template (portal, tasks, files, invoices) + setup video (20 min)',
    contents: ['Branded client portal home with deliverables tracker', 'Shared task board with approval states', 'Invoice log with payment status', 'Kickoff questionnaire database'],
    audience: 'Freelancers and small agencies managing several clients',
    requirements: ['Free Notion account'],
    outcome: 'Clients self-serve status instead of pinging you daily' },
  { name: 'Photography Business Admin Pack', category: 'digital-products', type: 'DIGITAL', price: 8500, seller: 'brightpath-digital-academy',
    format: 'Booking form, shot-list, model release and invoice templates + pricing guide (PDF)',
    contents: ['Booking flow from enquiry to retainer paid', 'Shot lists for portraits, weddings and products', 'Model release in plain enforceable language', 'Session pricing worksheet with cost coverage'],
    audience: 'Photographers formalising a growing side business',
    requirements: ['Word/Excel or Google equivalents'],
    outcome: 'Bookings, releases and invoices handled without dread' },
  { name: 'Study Skills & Exam Technique Course', category: 'digital-education', type: 'DIGITAL', price: 7500, seller: 'brightpath-digital-academy',
    format: '18 lessons (MP4, 2.8 h) + revision planner (PDF) + past-paper strategy guide',
    contents: ['Spaced repetition and active recall, taught practically', 'Timetable that survives real life and NEPA', 'Past-paper technique for WAEC/JAMB style exams', 'Exam-day protocol: sleep, food, timing drills'],
    audience: 'Secondary and tertiary students preparing for major exams',
    requirements: ['None'],
    outcome: 'A revision system with measurable weekly recall gains' },
];

export function applyVariantExtensions(items: SeedItem[]): SeedItem[] {
  const out: SeedItem[] = [];
  for (const item of items) {
    const key: FamilyKey = `${item.seller}::${item.name}`;
    const extras = EXTRA_VARIANTS[key];
    if (extras?.length) {
      // namedVariants merge — extras come after the family's own
      const own = item.namedVariants ?? [];
      out.push({ ...item, namedVariants: [...own, ...extras] });
    } else {
      out.push(item);
    }
  }
  return [...out, ...WAVE2_ITEMS];
}
